### ISSUE TITLE
Type mismatch between make_stancode and make_standata

### ISSUE THREAD

**Issue by adamhaber** [paul-buerkner/brms#803] opened 2019-12-04 18:32 UTC
When calling:
```r
data <- make_standata(count ~ zAge + zBase * Trt + (1+Trt|visit),
                  data = epilepsy, family = "poisson")

code <- make_stancode(count ~ zAge + zBase * Trt + (1+Trt|visit),
                  data = epilepsy, family = "poisson")
```
I'm getting the following code:
```stan
// generated with brms 2.10.0
functions {
}
data {
  int<lower=1> N;  // number of observations
  int Y[N];  // response variable
  int<lower=1> K;  // number of population-level effects
  matrix[N, K] X;  // population-level design matrix
  // data for group-level effects of ID 1
  int<lower=1> N_1;  // number of grouping levels
  int<lower=1> M_1;  // number of coefficients per level
  int<lower=1> J_1[N];  // grouping indicator per observation
  // group-level predictor values
  vector[N] Z_1_1;
  vector[N] Z_1_2;
  int<lower=1> NC_1;  // number of group-level correlations
  int prior_only;  // should the likelihood be ignored?
}
transformed data {
  int Kc = K - 1;
  matrix[N, Kc] Xc;  // centered version of X without an intercept
  vector[Kc] means_X;  // column means of X before centering
  for (i in 2:K) {
    means_X[i - 1] = mean(X[, i]);
    Xc[, i - 1] = X[, i] - means_X[i - 1];
  }
}
parameters {
  vector[Kc] b;  // population-level effects
  // temporary intercept for centered predictors
  real Intercept;
  vector<lower=0>[M_1] sd_1;  // group-level standard deviations
  matrix[M_1, N_1] z_1;  // standardized group-level effects
  // cholesky factor of correlation matrix
  cholesky_factor_corr[M_1] L_1;
}
transformed parameters {
  // actual group-level effects
  matrix[N_1, M_1] r_1 = (diag_pre_multiply(sd_1, L_1) * z_1)';
  // using vectors speeds up indexing in loops
  vector[N_1] r_1_1 = r_1[, 1];
  vector[N_1] r_1_2 = r_1[, 2];
}
model {
  // initialize linear predictor term
  vector[N] mu = Intercept + Xc * b;
  for (n in 1:N) {
    // add more terms to the linear predictor
    mu[n] += r_1_1[J_1[n]] * Z_1_1[n] + r_1_2[J_1[n]] * Z_1_2[n];
  }
  // priors including all constants
  target += student_t_lpdf(Intercept | 3, 1, 10);
  target += student_t_lpdf(sd_1 | 3, 0, 10)
    - 2 * student_t_lccdf(0 | 3, 0, 10);
  target += normal_lpdf(to_vector(z_1) | 0, 1);
  target += lkj_corr_cholesky_lpdf(L_1 | 1);
  // likelihood including all constants
  if (!prior_only) {
    target += poisson_log_lpmf(Y | mu);
  }
}
generated quantities {
  // actual population-level intercept
  real b_Intercept = Intercept - dot_product(means_X, b);
  // group-level correlations
  corr_matrix[M_1] Cor_1 = multiply_lower_tri_self_transpose(L_1);
  vector<lower=-1,upper=1>[NC_1] cor_1;
  // extract upper diagonal of correlation matrix
  for (k in 1:M_1) {
    for (j in 1:(k - 1)) {
      cor_1[choose(k - 1, 2) + j] = Cor_1[j, k];
    }
  }
}
```
But in the resulting `data` object, `NC_1` is a double[1] 1.0.
Is this intentional? rstan seems to be OK with this, in the sense that calling 
```r
fit <- stan(model_code = code, data = data)
```
works. However, calling PyStan with the same code and a dictionary with the same types raises
```
RuntimeError: Exception: int variable contained non-int values; processing stage=data initialization;
 variable name=NC_1; base type=int  (in 'unknown file name' at line 16)
```
Thanks in advance!

**Comment by paul-buerkner** [comment] 2019-12-04 19:20
Thanks. I will fix it.

**Comment by adamhaber** [comment] 2019-12-04 19:41
Thanks! Regarding the discrepancy between rstan and PyStan - any idea what might cause this? It looks like an rstan bug but maybe I'm missing something...

**Comment by paul-buerkner** [comment] 2019-12-04 20:37
R (or rstan) just doesn't care and transforms double to integer when
necessary or the other way round. This is not a bug but expected behavior I
would say.

Adam Haber <notifications@github.com> schrieb am Mi., 4. Dez. 2019, 21:41:

**Comment by paul-buerkner** [comment] 2019-12-06 08:59
Should be fixed now.

**Closed by paul-buerkner** 2019-12-06 08:59 UTC

**Comment by adamhaber** [comment] 2019-12-06 11:55
Thanks!

**Comment by adamhaber** [comment] 2019-12-06 18:47
Hi,

Just want to update that the problem was solved in the case above (thanks again), but I encountered something very similar in a slightly different case. When I do `(1|visit)` instead of `(1+Trt|visit)` I get the following stan code:
```stan
// generated with brms 2.10.5
functions {
}
data {
  int<lower=1> N;  // number of observations
  int Y[N];  // response variable
  int<lower=1> K;  // number of population-level effects
  matrix[N, K] X;  // population-level design matrix
  // data for group-level effects of ID 1
  int<lower=1> N_1;  // number of grouping levels
  int<lower=1> M_1;  // number of coefficients per level
  int<lower=1> J_1[N];  // grouping indicator per observation
  // group-level predictor values
  vector[N] Z_1_1;
  int prior_only;  // should the likelihood be ignored?
}
transformed data {
  int Kc = K - 1;
  matrix[N, Kc] Xc;  // centered version of X without an intercept
  vector[Kc] means_X;  // column means of X before centering
  for (i in 2:K) {
    means_X[i - 1] = mean(X[, i]);
    Xc[, i - 1] = X[, i] - means_X[i - 1];
  }
}
parameters {
  vector[Kc] b;  // population-level effects
  // temporary intercept for centered predictors
  real Intercept;
  vector<lower=0>[M_1] sd_1;  // group-level standard deviations
  // standardized group-level effects
  vector[N_1] z_1[M_1];
}
transformed parameters {
  // actual group-level effects
  vector[N_1] r_1_1 = (sd_1[1] * (z_1[1]));
}
model {
  // initialize linear predictor term
  vector[N] mu = Intercept + Xc * b;
  for (n in 1:N) {
    // add more terms to the linear predictor
    mu[n] += r_1_1[J_1[n]] * Z_1_1[n];
  }
  // priors including all constants
  target += student_t_lpdf(Intercept | 3, 1, 10);
  target += student_t_lpdf(sd_1 | 3, 0, 10)
    - 1 * student_t_lccdf(0 | 3, 0, 10);
  target += normal_lpdf(z_1[1] | 0, 1);
  // likelihood including all constants
  if (!prior_only) {
    target += poisson_log_lpmf(Y | mu);
  }
}
generated quantities {
  // actual population-level intercept
  real b_Intercept = Intercept - dot_product(means_X, b);
}
```

but `make_standata` returns a list that contains a double NC_1=0. (not included in the model's data section), and a double Y (instead of int).

**Comment by paul-buerkner** [comment] 2019-12-06 18:54
There may be a lot of these things looming around as R doesn't care about it at all. I see why pythong would complain about double Y but why should an irrelevant variable in the data be a problem?

**Comment by paul-buerkner** [comment] 2019-12-06 19:01
After looking at the code, I think Y needs to be numeric as I always pass it as an array to allow for models with only a single observations (otherwise rstan will complain). And there are no integer arrays in R. So essentially what you report above is not fixable to my current knowledge and you have to do your adjustments yourself in python.

**Comment by adamhaber** [comment] 2019-12-06 19:03
The irrelevant variable isn't actually a problem - PyStan can fit the model as long as the "true data dictionary" is a subset of the data passed to .sample(); I just tried to find inconsistencies between the generated data and code and found this so I thought it might be helpful to report it.

> There may be a lot of these things looming around as R doesn't care about it at all and I will not have necessarily fix all such problems

Sure. I guess I can try to parse the data section in the Stan code, infer types and cast everything within python. Thanks for putting the time into this, and for the quick response!
