### ISSUE TITLE
LOO error

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#87] opened 2016-06-23 17:50 UTC
I consistently get this error when I use LOO to compare two models:
```
Error in vapply(seq_along(mapped), function(i) {: values must be length 1,
 but FUN(X[[1]]) result is length 0
```

**Comment by paul-buerkner** [comment] 2016-06-23 17:59
Does this happen for comparison of all your models? The problem is that the code you are quoting is not code of brms itself so I don't know what's happening. 

You could try updating brms (possible use the dev version from github) and install the latest version of the loo package (version 1.6). If the error persists I would be very grateful if you send me two of your models for which the error occurs so that I can find out what goes wrong.

**Comment by jgabry** [comment] 2016-06-23 18:28
Hmm, I haven't double checked but I'm pretty sure I don't have the code quoted in the error message in the **loo** package either.

**Comment by alireza202** [comment] 2016-06-23 18:39
I sent you the models by email.

**Comment by paul-buerkner** [comment] 2016-06-23 20:27
As discussed via email, the correct output of `LOO` is returned and printed _in addition_ to the error message, which obviously wasn't fatal in this case. When I run the same code on Windows and Mac, everything works fine so it is likely Linux (Ubuntu) specific.

**Comment by alireza202** [comment] 2016-06-23 21:40
So I think I found the culprit. I ran the same command on both Ubuntu and Mac, and when I do it in command mode, it runs ok on both systems. But when I use Jupyter, which is my to-go environment for R/Python, I get this error, again on both machines. It's really strange. I haven't seen that error anywhere else before, and I can't imagine what the connection can be...

**Comment by paul-buerkner** [comment] 2016-06-24 08:15
That's very intersting. I have no idea either. However, I don't think I can do anything about it on the brms side. Maybe you can ask the Jupyter developers about it. I am happy to help them debugging if necessary. Are you ok, if I close this issue?

**Comment by alireza202** [comment] 2016-06-24 17:15
Sure, go ahead.

**Closed** 2016-06-24 17:17 UTC
Labels: bug
