### ISSUE TITLE
fixef() doesnt work?

### ISSUE THREAD

**Issue by troettge** [paul-buerkner/brms#317] opened 2018-01-14 23:05 UTC
Error in fixef_pars() : could not find function "fixef_pars" 
ranef() and coef() work just fine.

**Comment by paul-buerkner** [comment] 2018-01-15 07:25
the function is called fixef ().

Am 15.01.2018 00:05 schrieb "troettge" <notifications@github.com>:

Error in fixef_pars() : could not find function "fixef_pars"
ranef() and coef() work just fine.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/paul-buerkner/brms/issues/317>, or mute the thread

**Comment by paul-buerkner** [comment] 2018-01-15 12:58
I realize, my previous answer stupid. Please ignore it. The function `fixef_pars` exists inside brms and it works for me. Can you show me a reproducible example.

**Comment by troettge** [comment] 2018-01-15 17:54
values_1 <- round(rnorm(100, 3, 0.5),0)
values_2 <- round(rnorm(100, 2.8, 0.5),0)
values_3 <- round(rnorm(100, 2.8, 0.5),0)
values_4 <- round(rnorm(100, 2.5, 0.5),0)

values <- c(values_1,values_2,values_3,values_4)

stuff <- c(rep("A",100),rep("B",100),rep("C",100),rep("D",100))

xdata <- data.frame(stuff,values)
xdata$num <- as.numeric(as.character(xdata$values))
xdata$values <- as.ordered(as.character(xdata$values))

xmdl_test <- brm(values ~  stuff, family = cumulative("logit"), data = xdata)

fixef(xmdl_test)

**Comment by paul-buerkner** [comment] 2018-01-15 18:05
Hmm. This works for me. Could you send me the output of `sessionInfo()`?

**Comment by troettge** [comment] 2018-01-15 18:09
okay, must be me then:

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shiny_1.0.5     dplyr_0.7.2     purrr_0.2.3     readr_1.1.0     tidyr_0.7.0     tibble_1.3.4    tidyverse_1.1.1
 [8] brms_2.0.1      ggplot2_2.2.1   Rcpp_0.12.12   

loaded via a namespace (and not attached):
  [1] TH.data_1.0-8        minqa_1.2.4          colorspace_1.3-2     modeltools_0.2-21    rprojroot_1.2        rsconnect_0.8.5     
  [7] estimability_1.2     htmlTable_1.9        markdown_0.8         base64enc_0.1-3      rstan_2.16.2         MatrixModels_0.4-1  
 [13] DT_0.2               lubridate_1.6.0      mvtnorm_1.0-6        xml2_1.1.1           coin_1.1-3           bridgesampling_0.3-0
 [19] codetools_0.2-15     splines_3.4.3        mnormt_1.5-5         knitr_1.17           shinythemes_1.1.1    bayesplot_1.3.0     
 [25] afex_0.17-8          jsonlite_1.5         Formula_1.2-1        nloptr_1.0.4         pbkrtest_0.4-7       broom_0.4.2         
 [31] cluster_2.0.6        httr_1.2.1           compiler_3.4.3       lsmeans_2.25-5       backports_1.0.5      assertthat_0.2.0    
 [37] Matrix_1.2-12        lazyeval_0.2.0       acepack_1.4.1        htmltools_0.3.6      quantreg_5.33        tools_3.4.3         
 [43] bindrcpp_0.2         lmerTest_2.0-33      igraph_1.1.2         coda_0.19-1          gtable_0.2.0         glue_1.1.1          
 [49] reshape2_1.4.2       cellranger_1.1.0     nlme_3.1-131         crosstalk_1.0.0      psych_1.7.5          stringr_1.2.0       
 [55] rvest_0.3.2          lme4_1.1-13          mime_0.5             miniUI_0.1.1         gtools_3.5.0         MASS_7.3-47         
 [61] zoo_1.8-0            scales_0.5.0         colourpicker_0.3     hms_0.3              Brobdingnag_1.2-4    parallel_3.4.3      
 [67] sandwich_2.3-4       inline_0.3.14        SparseM_1.77         shinystan_2.4.0      RColorBrewer_1.1-2   yaml_2.1.14         
 [73] gridExtra_2.3        loo_1.1.0            StanHeaders_2.16.0-1 rpart_4.1-11         latticeExtra_0.6-28  stringi_1.1.5       
 [79] dygraphs_1.1.1.4     checkmate_1.8.2      rlang_0.1.2          pkgconfig_2.0.1      matrixStats_0.52.2   evaluate_0.10.1     
 [85] lattice_0.20-35      bindr_0.1            rstantools_1.3.0     htmlwidgets_0.8      labeling_0.3         plyr_1.8.4          
 [91] magrittr_1.5         R6_2.2.2             Hmisc_4.0-2          multcomp_1.4-6       haven_1.0.0          foreign_0.8-69      
 [97] mgcv_1.8-22          xts_0.10-0           survival_2.41-3      abind_1.4-5          nnet_7.3-12          modelr_0.1.0        
[103] car_2.1-4            rmarkdown_1.6        readxl_1.0.0         data.table_1.10.4    forcats_0.2.0        threejs_0.3.1       
[109] digest_0.6.12        xtable_1.8-2         httpuv_1.3.5         stats4_3.4.3         munsell_0.4.3        shinyjs_0.9.1

**Comment by paul-buerkner** [comment] 2018-01-15 18:11
Hmm I have no idea what is happening. Could you try reinstalling brms from CRAN in a fresh R session and try it again?

**Comment by troettge** [comment] 2018-01-15 18:21
Thanks, I did, but still the same issue.

**Comment by paul-buerkner** [comment] 2018-01-15 18:40
What confuses me is that `coef()` works although it internally calls `fixef()` as well. Could you try it with the dev version of brms from github?

```R
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms", dependencies = TRUE)
```

**Comment by troettge** [comment] 2018-01-15 19:20
error remains, even with dev version. Yes, ranef() and coef() worked.

**Comment by paul-buerkner** [comment] 2018-01-15 20:16
Very weird. Ok let's look at the details. Can you tell me what happens if you type

```R
fixef
brms:::fixef.brmsfit
brms:::fixef_pars
```

**Comment by troettge** [comment] 2018-01-16 00:27
> fixef
function (object, ...) 
UseMethod("fixef")
<bytecode: 0x10f3b3980>
<environment: namespace:nlme>
> brms:::fixef.brmsfit
function (object, summary = TRUE, robust = FALSE, probs = c(0.025, 
    0.975), ...) 
{
    contains_samples(object)
    pars <- parnames(object)
    fpars <- pars[grepl(fixef_pars(), pars)]
    if (!length(fpars)) {
        stop2("The model does not contain population-level effects.")
    }
    out <- as.matrix(object, pars = fpars, exact_match = TRUE)
    colnames(out) <- gsub(fixef_pars(), "", fpars)
    if (summary) {
        out <- posterior_summary(out, probs, robust)
    }
    out
}
<environment: namespace:brms>
> brms:::fixef_pars
function () 
{
    "^b(|cs|mo|me|m)_"
}
<environment: namespace:brms>

**Comment by paul-buerkner** [comment] 2018-01-16 07:57
Thanks. All functions are in place, where they need to be. The only thing I can imagine is that is it not actually `brms:::fixef.brmsfit` that is called internally, when you run `fixef(xmdl_test)`. This is not a problem of brms really, but let's see if we can fix this anyway. Can you do 2 more things.

(1) call `brms:::fixef.brmsfit(xmdl_test)` and tell me if that works.

(2) Call `debug(fixef)` and `fixef(xmdl_test)` and click through the code until it fails. Then show me everything that was generated in the console during debugging.

**Comment by troettge** [comment] 2018-01-16 13:18
The former works indeed, so it must interfere with another package, right? Thank you for your patience.

**Comment by paul-buerkner** [comment] 2018-01-16 14:44
Yes, indeed, but I have currently no idea, which package it could be. Maybe the debugging I proposed might help you to find out what exactly happens.

**Comment by paul-buerkner** [comment] 2018-01-22 20:59
Closing this since it is not a brms issue.

**Closed by paul-buerkner** 2018-01-22 20:59 UTC
Labels: question
