### ISSUE TITLE
Spurious values in prediction samples

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#76] opened 2016-06-13 19:02 UTC
I'm modeling a hierarchical negative binomial model of this form:

```
brm(formula = y ~ p + (p | item), 
    data = training,
    family = "negbinomial",
    chains = 4,
    cluster = 4,
    prior = set_prior('normal(0, 5)', class = 'b'), 
    iter = 1200, 
    warmup = 500) -> fit_model
```

and I have a testing data set that I use to validate the model:

`predict(object = fit_model, newdata = testing)`

 In one of the items, I saw that the predicted estimate was over the roof (1245 when it should have been 0). Variable `p` was a normal value, like others. I got the actual draws using `summary = FALSE`, and I had 2741 zeros (out of 2800), but a few values as large as 2730000! How is this possible?

**Comment by alireza202** [comment] 2016-06-13 19:14
I ran the predict function another time, and it happened for the same item again.

**Comment by paul-buerkner** [comment] 2016-06-13 21:22
I am not sure, but maybe some samples are invalid (did the model converge / had divergent transitions?). 
It may also be a numerical problem, but it's hard to tell without seeing the model.
Would you mind sending me the fitted model (e.g. via email) so that I can investigate this further?

**Comment by alireza202** [comment] 2016-06-13 21:31
No, it didn't give any errors. I'll send the model, and dataset to you.

**Comment by alireza202** [comment] 2016-06-14 00:01
Just in case:
```
R version 3.2.1 (2015-06-18)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] brms_0.9.1       rstan_2.9.0-3    broom_0.3.7      tidyr_0.3.1     
[5] ggplot2_2.1.0    data.table_1.9.6 readr_0.2.2      dplyr_0.4.3     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      nloptr_1.0.4     plyr_1.8.3       base64enc_0.1-3 
 [5] tools_3.2.1      statmod_1.4.23   lme4_1.1-12      digest_0.6.9    
 [9] uuid_0.1-2       nlme_3.1-124     jsonlite_0.9.19  evaluate_0.9    
[13] gtable_0.2.0     lattice_0.20-33  Matrix_1.2-2     psych_1.5.8     
[17] IRdisplay_0.3    DBI_0.4-1        IRkernel_0.4     parallel_3.2.1  
[21] rzmq_0.7.7       gridExtra_2.0.0  coda_0.17-1      repr_0.4        
[25] stringr_1.0.0    stats4_3.2.1     inline_0.3.14    R6_2.1.2        
[29] minqa_1.2.4      reshape2_1.4.1   magrittr_1.5     MASS_7.3-44     
[33] splines_3.2.1    scales_0.4.0     assertthat_0.1   abind_1.4-3     
[37] mnormt_1.5-3     colorspace_1.2-6 labeling_0.3     stringi_1.0-1   
[41] lazyeval_0.1.10  munsell_0.4.3    chron_2.3-47
```

**Comment by paul-buerkner** [comment] 2016-06-14 09:13
Ok, so here is what I found. When I use the original data.frame `sub_training` I get reasonable results out of predict:

```R
pr1 <- predict(model, sub_training)
max(pr1[, 1])  # around 59
```

However, when I use the data.frame `sub_testing`, I get those overly large estimates you reported:

```R
pr2 <- predict(model, sub_testing)
max(pr2[, 1])  #  over 10000
```

I think it's a problem with the values of variable `p_norm` in `sub_testing`. In `sub_training` we have values of `p_norm` between -4 and 4 but in `sub_testing` I find values of above 30:

```R
hist(sub_training$p_norm)
hist(sub_testing$p_norm)
``` 

Based on what I have seen so far, I am not sure whether those > 30 values are really valid.

**Comment by alireza202** [comment] 2016-06-14 15:52
Yeah, you're right. I need to look into that. So what I'm doing is that since `p` values vary a lot, I'm normalizing them in the training period per item, and use the same scale and center to normalize them in testing. Since I can't predict what values of p I will have in the testing, this is inevitable, unless I normalize `p` in a more robust way.

I'm trying to understand how predict function works. Why when the `p_norm` values are really high, most of the draws for that item are zero, and the rest are really large?

**Comment by paul-buerkner** [comment] 2016-06-14 16:32
This is not a bug in the predictions as far as I can see. The problem is the following: The overall effect of `p_norm` is negative (around -0.66) and the effect of `p_norm` for item302 is still negative most of the time. Thus, because of the large values of `p_norm` in `sub_testing` the linear predictor will be strongly negative and the prediction is thus zero (since we use the log link for this model). However, some of the samples correspond to a positive effect of `p_norm` for item302. Due to the very large values of `p_norm`, the linear predictor will be strongly positive this time leading to very large predictions.

If you can't (or don't want to) get rid of those large values of `p_norm` in `sub_testing`, I suggest that you use the median of the predictions instead of the mean. You can simply do this via:

```R
pr2_raw <- predict(model, sub_testing, summary = FALSE)
pr_medians <- apply(pr2_raw, 2, "median")
```

**Comment by paul-buerkner** [comment] 2016-06-14 20:11
The dev version of brms from github now supports robust measures of central tendency and variability in predict and related methods. Just set argument `robust = TRUE`.

**Comment by paul-buerkner** [comment] 2016-06-15 16:56
@alireza202 Are you ok if I close this issue or do you want to leave it open for now?

**Comment by alireza202** [comment] 2016-06-15 16:57
Sure, you can close it!

**Closed** 2016-06-15 16:59 UTC
Labels: question

**Comment by alireza202** [comment] 2016-11-12 00:21
Do you think it makes sense to just filter the extreme outliers (like the one mentioned above), and then calculate mean? I ran into another example, where the samples of Intercept include a few really large numbers (I'm using variational inference). Do you think doing that will introduce bias?

**Comment by paul-buerkner** [comment] 2016-11-12 00:34
I don't know, probably it makes sense. Our you can just use the median instead of the mean. I am not sure where those values are coming from. Possibly those are outliers in the posterior samples that are due to problems in the sampler. In this case it may be reasonable to exclude them, but I can't tell you in general why this happens or what are the consequences of excluding them. After all, it will depend on the model at hand.

**Comment by alireza202** [comment] 2016-11-13 03:03
Thanks.
