### ISSUE TITLE
Speed issue with cor_lagsar

### ISSUE THREAD

**Issue by aslez** [paul-buerkner/brms#680] opened 2019-06-03 17:01 UTC
I recently tried to run a cor_lagsar model and found that it was prohibitively slow when working with data with even just a few hundred observations.  I took a look at the code found at least two sources of inefficiency, which I have since realized are not entirely unintentional.  

First, the code calculates the log of the Jacobian---W_tilde---using the log_determinant command.  An alternative approach going back to Ord (1975) is to take the sum of 1 minus the vector of eigenvalues associated with the spatial weights matrix W.  What I have come to realize is that Stan does not allow you to take the eigenvalues of an asymmetric matrix, which makes it difficult to apply the approximation on the fly without taking the eigenvectors as an argument in the normal_lagsar_lpdf function that is produced when brm generates the code for Stan.

Second, the model parameterization follows the discussion here: https://mc-stan.org/loo/articles/loo2-non-factorizable.html.  This makes sense, but it requires inverting W_tilde, which can really slow things down, especially as the number of observations grows.

I've include an R script that shows what happens if you rewrite the code to address these two points.  It seems to go much faster, but I'm wondering whether the change in parameterization will effect the ability to calculate the various LOO-related measures.
[stan_lagsar.zip](https://github.com/paul-buerkner/brms/files/3248636/stan_lagsar.zip)

**Comment by paul-buerkner** [comment] 2019-06-03 19:09
Thanks a lot! I will take a detailed look in the upcoming days!

**Comment by aslez** [comment] 2019-06-03 19:14
Paul,

I didn’t say this in my post, but I looked over the LOO link again and realized that the parameterization used in brm follows from there.  It makes sense to me now, but it is definitely going to be much slower than the usual approach.  Eyeballing the run times for the Columbus example, the brm version was taking 15 times longer per chain than the traditional parameterization.  I haven’t tried this with the bigger data yet.  

At the moment, I think the most reasonable way forward for my purposes may be to do everything using the alternative code and figure out how to get LOO to work by hand.

Thanks for taking a look at this.

Adam

Adam Slez 
Assistant Professor 
Department of Sociology 
University of Virginia 
aslez@virginia.edu

**Comment by paul-buerkner** [comment] 2019-07-07 17:57
Are the two implementations equivalent in terms of the implied likelihood? Because if they are, we could use the Ord (1975) parameterization in the Stan code and (at least for the time being) use the existing implementation for computing the log-likelihood values, even if this is slow.

**Comment by paul-buerkner** [comment] 2019-07-07 18:00
Another question: Why is it necessary to constrain the lagsar parameterization between the smallest and largest eigenvalue? Should, in theory, the same constrain also apply for the currently used parameterization?

**Comment by paul-buerkner** [comment] 2019-07-08 22:00
A test version of the improved lagsar model is now implemented on the "improve-lagsar" branch (without changing the bounds of rho or the `log_lik` implementation for now). Before I merge it, I just the clarifications on the questions I raised above.

**Comment by aslez** [comment] 2019-07-09 18:54
The likelihoods are equivalent.  I suspected as much given that the two representations of the model are equivalent, but I've attached some notes working this out.  

The proposed constraints---which can be shown to hold by definition---aren't strictly necessary, in the sense that bounding between 0 and 1 will work for most applications (assuming a SAR model with a row-standardized weights matrix).  These bounds should hold for the current brms parameterization as well.  While 0 and 1 should work just fine, my preference would be to use either the known bounds, or a real prior of some sort.  I can't remember what it is exactly, but I recall the slm model in INLA using something a little more informative than a flat, bounded prior.  If you are interested, I can point you to work being done on this front in the network analysis literature.

Last thing...

Would it be possible to update the t-distributed SAR models as well?  This is really what I am interested in, but I wanted to work out the code for the normal distribution first since this what I was most familiar with.
[likelihood_notes.pdf](https://github.com/paul-buerkner/brms/files/3374460/likelihood_notes.pdf)

**Comment by paul-buerkner** [comment] 2019-07-09 19:07
Thanks for working this out! Indeed, it was very plausible that both are equivalent but nice to know that this actually holds.

I will make some tests with the known bounds. 

I am happy to update the t-distributed SAR as well. Is there anything special I need to take into account? Ideally, could you work out the likelihood in Stan language for that as well? I know it should not be too complicated and I can do it myself, but I am drowning in brms-related stuff and I am thankful for people helping me out.

**Comment by aslez** [comment] 2019-07-09 19:20
I'm happy to try and take a crack at the code.  I've haven't worked with this version of the model before, but the basic setup is pretty straightforward.  I suspect that given an appropriately transformed input, it might be possible to just tack on the log of the determinant of the Jacobian to the output from multi_student_t_lpdf.  Is there any reason to think that this would slower than doing the whole thing from scratch?

**Comment by paul-buerkner** [comment] 2019-07-09 19:43
I would probably go the same route as you suggested.

**Comment by aslez** [comment] 2019-07-10 02:20
Revised version of previous code attached, this time with code for normal and Student's t models.  It ended up being easier just write the likelihood out by hand.  Do you want me to take a look at the error models as well?
[stan_lagsar_rev.zip](https://github.com/paul-buerkner/brms/files/3375481/stan_lagsar_rev.zip)

**Comment by paul-buerkner** [comment] 2019-07-10 09:21
Thanks a lot! If you have time, I would of course appreciate if you looked at the errorsar models as well!
In the mean time I get the student-t model working on the branch.

**Comment by paul-buerkner** [comment] 2019-07-10 09:33
I reviewed your proposed reparameterization. It looks correct to me and gives the same results also in my test cases. And wow, the speed increase is roughly an order of magnitude! The implemention is now available on the improve-sar github branch.

**Comment by paul-buerkner** [comment] 2019-07-10 10:43
Just had a quick look at the error-SAR models and realized that the required jacobian adjustment is the same as for the lag-SAR models. Thus, the required changes are actually trivial and I just push them to github. Still, would you mind doubling checking what I did? The PR is available at #704.

**Comment by aslez** [comment] 2019-07-10 14:16
I checked over the error code.  My response is over on the other thread.  The only thing that remains here is the initial question about calculating LOO-related measures using the new parameterization.  Is there still work to be done on that front?

**Comment by paul-buerkner** [comment] 2019-07-10 14:39
Ideally, we would love to speed up the loo computations as well, but since the two parameterizations are equivalent, we don't do any harm by just using the old one for the parameterization. The problem is that our non-factorizable solutions only holds for responses distributed according to `y ~ N(0, Sigma)`. I don't know how we can factorize the Jacobian adjusted determinant approach to yield the conditional distribution of y_i given y_{-i}. So, unless you have an idea on that front, I would just continue to use the old parameterization for the pointwise log_lik (and thus the LOO) computations.

**Comment by aslez** [comment] 2019-07-10 15:22
Sorry, I should have been clearer.  I get that the current proposal is to estimate the mode using the new parameterization and calculate the LOO measures using the old parameterization.  My question is whether the existing LOO commands will work correctly with the output produced using the models over on the "improve-lagsar" branch or whether the output from those models needs to be post-processed by hand to get the LOO measures.

I'm interested to see how slow the LOO calculations are, particularly in cases where you have bad k values and need to refit the model.  One quick and dirty solution would be to replace the inverse of W_tilde with an approximation.  The inverse in question is equal to an infinite series given by I_n + \rho W + \rho^2 W^2 + \rho^3 W^3 + ...  + \rho^\infty W^\infty.  The contribution of additional terms declines pretty quickly, so you wouldn't need to go that far to get close to the right answer.

**Comment by paul-buerkner** [comment] 2019-07-10 15:28
The existing LOO commands will work correctly to the best of my knowledge (and my tests). To be clear, when I talk about LOO, I mean approximate PSIS-LOO based on the full `log_lik` matrix and performed via the `loo` method. As discussed in the non-factorizable paper, exact LOO is not trivial as removing an observation changes the prior of the other observations and we need to keep the prior constant or otherwise the importance sampling weights will be incorrect. I am not sure if this answers youre questions or if we are misunderstanding each other here.

**Comment by aslez** [comment] 2019-07-10 15:42
I meant PSIS-LOO.  Looking at the code more carefully, I see that you aren't inverting W_tilde; rather, you are solving for X in W_tilde %*% X = eta.  If I figure something better out, I'll let you know.  Thanks for all of the help!

**Comment by paul-buerkner** [comment] 2019-07-10 15:45
And thank you for all your help as well!

**Closed by paul-buerkner** 2019-07-10 15:45 UTC
Labels: enhancement
