### ISSUE TITLE
Initial value rejection in cumulative-link model on brms 2.8.8

### ISSUE THREAD

**Issue by PhoenixB** [paul-buerkner/brms#659] opened 2019-05-04 11:34 UTC
Dear Paul,

After upgrading to the latest github version 2.8.8 my cumulative link model fails to start sampling with the following error:
> Chain 1: Rejecting initial value:
> Chain 1:   Error evaluating the log probability at the initial value.
> Chain 1: Exception: ordered_logistic: Cut-points is not a valid ordered vector. The element at 2 is -1.11252, but should be greater than the previous element, 1.8837  (in 'model93de5fbd270c_c18d60e8f2d8a070f7dd6d6aec297d45' at line 47)

After downgrading to 2.8.0 it works again.

Regards,
Pascal

**Comment by paul-buerkner** [comment] 2019-05-04 11:42
Hmm this works for me

```R
fit2 <- brm(rating ~ period + carry + treat,
            data = inhaler, family = cumulative("logit"),
            prior = set_prior("normal(0,5)"), chains = 2)
```

If this example fails for you, you may need to update brms from github once again.

Otherwise, can you please provide a minimial reproducible example?

**Comment by PhoenixB** [comment] 2019-05-04 14:09
This one works for me, too:
> ```r
> fit2 <- brm(rating ~ period + carry + treat,
>             data = inhaler, family = cumulative("logit"),
>             prior = set_prior("normal(0,5)"), chains = 2)
> ```

I'm now witnessing a very strange behaviour:
When I'm running my model in a interactive R session (on the computer cluster), there is no error. When I'm running the model the exact same way with a script on the same cluster, the error happens. When I downgrade to v2.8.0, the model runs in the interactive sessions as well as in the script…

**Comment by paul-buerkner** [comment] 2019-05-04 14:12
Possibly to different states of 2.8.8? I made a lot of minor fixes within 2.8.8 without changing the version number.

**Comment by PhoenixB** [comment] 2019-05-04 14:14
> Possibly two different states of 2.8.8? I made a lot of minor fixes within 2.8.8 without changing the version number.

I always installed via `install_github("paul-buerkner/brms")`, so I'm assuming it's the latest version…

**Comment by PhoenixB** [comment] 2019-05-04 14:39
FYI, the call for the model run is as follows (for both the interactive session and the script):
```
brm_arguments <-
  list(
    formula = bf(answer ~ 1),
    data = original_data,
    family = cumulative("logit", threshold = "flexible"),
    sample_prior = "yes",
    cores = 4,
    chains = 4,
    save_all_pars = TRUE,
    control = list(max_treedepth = 15),
    save_model = paste0("./R/models/brms.", "Model1-0-0_pred-answer_1.flex", ".txt")
  )

model <- do.call("brm", brm_arguments)
```

**Comment by paul-buerkner** [comment] 2019-05-07 21:24
This looks sensible and sufficiently simple. I don't see any reason why initializing the chains should fail. Did you find solution yet?

**Comment by PhoenixB** [comment] 2019-05-07 21:54
Not yet, although I haven‘t tested it again… I suppose there must be a problem with the cluster scheduler, because it works in the interactive session…
I leave it open and check again in a while, maybe reinstalling all packages.

**Comment by paul-buerkner** [comment] 2019-05-07 22:03
Thanks for the quick response. In any case I don't think it's a brms issue. If at all then one of Stan itself.
I will close this issue in order to keep the issue tracker clean, but feel free to post in the closed issue again if you have any updates.

**Closed by paul-buerkner** 2019-05-07 22:03 UTC

**Comment by PhoenixB** [comment] 2019-06-07 13:26
Dear Paul

With brms 2.9.0 the error still persists.
When I diff-compare the models generated with 2.8.0 (working) and 2.9.0 (not working), there is a striking difference in the `transformed data` section (picture attached). Is this maybe the problem?

![Capto_Capture 2019-06-07_03-23-02_PM](https://user-images.githubusercontent.com/514321/59107262-84298c00-8938-11e9-9af9-1bc38750d625.png)

Kindest regards, Pascal

**Comment by PhoenixB** [comment] 2019-06-07 14:24
Could maybe this be the problem:
When I execute `pkgbuild::has_build_tools(debug = TRUE)` in the interactive session, I get the following output:
```
pkgbuild::has_build_tools(debug = TRUE)
Running /software/R/3.5.1/lib64/R/bin/R CMD SHLIB foo.c
gcc -m64 -I"/software/R/3.5.1/include/R" -DNDEBUG   -I"/gpfs/homefs/students/pj03t351/R/x86_64-koji-linux-gnu-library/3.5/Rcpp/include/"  -I"/gpfs/vitalit/software/el7/R/3.5.1/lib64/R/library/RcppEigen/include/"  -I"/gpfs/vitalit/software/el7/R/3.5.1/lib64/R/library/RcppEigen/include/unsupported"  -I"/gpfs/vitalit/software/el7/R/3.5.1/lib64/R/library/BH/include" -I"/gpfs/homefs/students/pj03t351/R/x86_64-koji-linux-gnu-library/3.5/StanHeaders/include/src/"  -I"/gpfs/homefs/students/pj03t351/R/x86_64-koji-linux-gnu-library/3.5/StanHeaders/include/"  -I"/gpfs/homefs/students/pj03t351/R/x86_64-koji-linux-gnu-library/3.5/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -I/software/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -march=nocona -mtune=core2  -c foo.c -o foo.o
gcc -m64 -shared -L/software/R/3.5.1/lib64/R/lib -Wl,-z,relro -o foo.so foo.o -L/gpfs/homefs/students/pj03t351/R/x86_64-koji-linux-gnu-library/3.5/StanHeaders/lib/ -lStanHeaders -L/software/R/3.5.1/lib64/R/lib -lR
[1] TRUE
```

When I run a script through the cluster with `pkgbuild::has_build_tools(debug = TRUE)`, the output is as follows:
```
Trying to compile a simple C file
Running /software/R/3.5.1/lib64/R/bin/R CMD SHLIB foo.c
gcc -m64 -I"/software/R/3.5.1/include/R" -DNDEBUG   -I/software/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -march=nocona -mtune=core2  -c foo.c -o foo.o
gcc -m64 -shared -L/software/R/3.5.1/lib64/R/lib -Wl,-z,relro -o foo.so foo.o -L/software/R/3.5.1/lib64/R/lib -lR

[1] TRUE
```

When I compile the model with `chains = 0` in an interactive session and do a update with a cluster script, it seems to work!

Do you have any idea what I could do? Do you think it's an RStan or rather a cluster server problem?

Thank you very much!

**Comment by paul-buerkner** [comment] 2019-06-08 08:33
I don't know. This seems very strange. @bgoodri have you seen something like this before?

**Comment by PhoenixB** [comment] 2019-06-08 10:55
In the `parameters` section in the picture above, the temporary thresholds `temp_Intercept` are a `vector` in the newer version, when it was working, it was`ordered`. Maybe this the problem?

**Comment by paul-buerkner** [comment] 2019-06-08 16:11
This would indeed explain the problem. However, in all models I have tried so far with the latest version of brms, `temp_Intercept` correctly is `ordered`. See for instance 

```
make_stancode(rating ~ period + carry + treat,
            data = inhaler, family = cumulative("logit"))
```

So if it happens to be a `vector` for some of your models, I need a reproducible example from you in order to fix it.

**Comment by PhoenixB** [comment] 2019-06-08 21:45
After hours of trying and trying, while making a reprex for @paul-buerkner, I was finally able to resolve the problem by myself!
I was generating a model list with formulas, families and other arguments on my MacBook with `brms` 2.8.0, uploaded it to the cluster and running the models on `brms` 2.9.0 yielded the error.
Since updating `brms` to 2.9.0 on my MacBook, everything works like a charm!

And the morals of the story:
1) Keep packages updated on **all** computers
2) Always make a reprex :-)

**Comment by paul-buerkner** [comment] 2019-06-09 07:22
Glad you could solve the issue!

Pascal Jerney <notifications@github.com> schrieb am Sa., 8. Juni 2019,
23:45:
