### ISSUE TITLE
Error using cor_bsts

### ISSUE THREAD

**Issue by awellis** [paul-buerkner/brms#226] opened 2017-05-20 09:26 UTC
hi Paul,

I tried to estimate a state-space model using cor_bsts():
```
library(brms)

data <- data.frame(y = ordered(sample(1:10, replace = TRUE, size = 100)),
                   x = rnorm(100),
                   time = 1:100)


fit <- brm(y ~ x, data = data, 
           autocor = cor_bsts(),
           family = cumulative())
```
and I get this error message:

Warning messages:
1: There were 171 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth above 10. See
http://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded 
2: There were 4 chains where the estimated Bayesian Fraction of Missing Information was low. See
http://mc-stan.org/misc/warnings.html#bfmi-low 
3: Examine the pairs() plot to diagnose sampling problems
 
4: In x$fit@sim$fnames_oi[change$pos] <- change$fnames :
  number of items to replace is not a multiple of replacement length
5: In names(x$fit@sim$samples[[i]])[change$pos] <- change$fnames :
  number of items to replace is not a multiple of replacement length
6: In names(x$fit@sim$samples[[i]])[change$pos] <- change$fnames :
  number of items to replace is not a multiple of replacement length
7: In names(x$fit@sim$samples[[i]])[change$pos] <- change$fnames :
  number of items to replace is not a multiple of replacement length
8: In names(x$fit@sim$samples[[i]])[change$pos] <- change$fnames :
  number of items to replace is not a multiple of replacement length

I think I also get the same error using a normal model instead of an ordered logistic. Am I doing something wrong? Am I trying to model mu[n] as a random walk, and then use x as a predictor for the latent state (in the data generated above, the outcome is obviously not autocorrelated. Just imagine that the process generating the ordinal respones follows a random walk).

**Comment by paul-buerkner** [comment] 2017-05-21 01:05
Thanks Andrew, I will check what is going on!

**Comment by paul-buerkner** [comment] 2017-05-22 09:19
Actually, it turned out to be two problems.

(a) the `cor_bsts` structure should not be allowed for ordinal models: It replaces the population-level intercept for identifiablility, but it cannot do so in ordinal models, since the intercepts are an essential requirement of ordinal families.

(b) There was a problem in the parameter renaming caused by the `cor_bsts` structure.

Both should be fixed now. Thanks again for reporting this issue!

**Closed by paul-buerkner** 2017-05-22 09:19 UTC
Labels: bug

**Comment by awellis** [comment] 2017-05-22 18:45
hi Paul, 

after close inspection of the stan code this make sense, I hadn't really thought that one through ;-) 

Do you have any intuition as to whether it would be possible to code a state space model with an ordinal response variable at all (I mean with the predictor eta evolving as a function of time and constant cutpoints)?
