### ISSUE TITLE
import warning with rstan 2.18

### ISSUE THREAD

**Issue by bgoodri** [paul-buerkner/brms#501] opened 2018-08-17 18:21 UTC
I think it is going to be okay for me to release rstan 2.18 soon, but there is a small issue with the current brms during installation.

```
Warning: replacing previous import ‘rstan::loo’ by ‘loo::loo’ when loading ‘brms’
```
This seems to be due to the new `loo` method in rstan for a stanreg object. You may need to import and rexport `loo` in brms or something. It should be possible to install the develop branch of rstan from GitHub to see this warning.

**Comment by paul-buerkner** [comment] 2018-08-17 19:03
Thanks! I will fix this tomorrow.

bgoodri <notifications@github.com> schrieb am Fr., 17. Aug. 2018, 20:21:

**Comment by paul-buerkner** [comment] 2018-08-17 19:04
Hmm now that I think about it: are you sure that you are correctly
importing loo::loo in rstan?

Paul Buerkner <paul.buerkner@gmail.com> schrieb am Fr., 17. Aug. 2018,
21:02:

**Comment by bgoodri** [comment] 2018-08-17 23:27
No, but @jgabry should know

**Comment by paul-buerkner** [comment] 2018-08-18 08:34
From the code base of brms:

```
#' @importFrom loo loo
#' @export loo
```

Shouldn't we avaoid function masking by importing and rexporting generics from other packages?

**Comment by paul-buerkner** [comment] 2018-08-18 12:09
I think the issue is now solved in the github version of brms. Would you mind verifying this on your machine?

**Comment by paul-buerkner** [comment] 2018-08-20 19:30
Closing this now. If, for some reason, you still see the warning, @bgoodri please feel free to reopen this issue.

**Closed by paul-buerkner** 2018-08-20 19:30 UTC
Labels: code
