### ISSUE TITLE
Timeout of brm

### ISSUE THREAD

**Issue by hoangtt1989** [paul-buerkner/brms#101] opened 2016-07-20 14:32 UTC
I'm running a large number of models in a for loop using `brm`. Some fit nicely and are able to converge in a reasonable amount of time, and others will take anywhere from 20 minutes to an hour to run. I'd like to be able to use `withTimeout` from `R.utils` to stop the execution of a model when it reaches a pre-specified time limit. However, I've noticed that even after `withTimeout` stops a model, the chains from that model seem to keep running in further iterations of the for loop. I suppose this is due to the Stan code underneath `brm`, but is it possible to implement some kind of user interrupt?

**Comment by paul-buerkner** [comment] 2016-07-20 15:36
When I run for instance
```R
fit <- brm(rating ~ period + carry + cse(treat), 
            data = inhaler, family = sratio("cloglog"), 
            prior = set_prior("normal(0,5)"), chains = 0)
R.utils::withTimeout(fit <- update(fit, chains = 1), timeout = 10)
```
`withTimeout` appears to be stopping the model correctly after 10 seconds. Can you give me a reproducable example of your problem? Are you referring to parallel execution of chains?

**Comment by hoangtt1989** [comment] 2016-07-20 15:59
I am referring to parallel execution of chains. When I run the following example, when `fit3` starts running, the chains from `fit2` continue to run.

```
data(inhaler)

rstan_options(autowrite = T)
options(mc.cores = detectCores() - 1)




fit1 <- brm(rating ~ treat + period + carry,
            data = inhaler, family = sratio(),
            prior = set_prior("normal(0,5)"), iter = 2000)

fit2 <- withTimeout(update(fit1, iter = 10000), timeout = 10)

fit3 <- update(fit1, iter = 3000)
```

**Comment by paul-buerkner** [comment] 2016-07-20 16:34
I see. The problem is the following: Both ways of parallel execution working with brms (the `cores` argument of rstan you are currently using implicitiy  and the `cluster` argument of brm itself) call the line
`on.exit(stopCluster(cl))` that *should* stop the workers from running as soon as `brm` is terminated. Unfortunately, and for reasons I do not understand, `on.exit` does not appear to work when the execution is terminated by `withTimeout`. Thus, I am currently unable to do anything about it. Maybe it is worth asking the maintainer of the R.utils package if he knows a way to stop parallel workers when using  `withTimeout`.

**Comment by hoangtt1989** [comment] 2016-07-20 16:35
Thank you.

**Comment by paul-buerkner** [comment] 2016-07-20 18:41
I have asked the author of R.utils about this. Not sure if it is really related to that package, but maybe he has an idea on why this is happening.

**Comment by HenrikBengtsson** [comment] 2016-07-22 05:40
Not at a computer, and not sure exactly what you've tried, but does
```r
fit2 <- tryCatch({
  withTimeout(update(fit1, iter = 10000), timeout = 10)
}, finally = {
  stopCluster(cl)
})
```
do it?

**Comment by paul-buerkner** [comment] 2016-07-22 07:05
I like your idea @HenrikBengtsson. The problem is that `cl` is an internal object in the `brm` call and we cannot access it from the outside.

**Comment by HenrikBengtsson** [comment] 2016-07-24 12:01
Here's an example showing that `on.exit()` of a function is called also when there is a timeout interrupt.  Define:
```r
foo <- function() {
  on.exit(message("*** on.exit() called"))
  message(1)
  Sys.sleep(1)
  message(2)
  TRUE
}
```
such that
```r
> foo()
1
2
*** on.exit() called
[1] TRUE
```
Now, evaluating with timeout, we get (using `"silent"` for cleaner output; default "error" would not change `on.exit()`):
```r
> res <- R.utils::withTimeout(foo(), timeout=0.1, onTimeout="silent")
1
*** on.exit() called
> res
NULL
```
So, things should work as expected when it comes to `on.exit()`.


# What I think is the real problem
However, I suspect that the cluster your using in [`brm()`](https://github.com/paul-buerkner/brms/blob/934ff87b205d025bf6123871e7a163a581768754/R/brm.R) function ends up in an invalid state due to the interrupt - you'd get the same regardless of timeout interrupt or user interrupt ("Ctrl-C").

Basically, a 'parallel' cluster works by communicating messages back and forth between the master process and the workers.  The master sends a message (i.e. code to be evaluated) and then waits for the result message to be sent back.  If you get an interrupt between these two, then your `on.exit()` code come in and tries to send another message to the workers (telling them to stop), but the worker/workers are still sitting there trying to send the master process the result back and will wait until that is done before in can receive the next message.  On the other end, the master is now waiting to send.  So, the master and the worker(s) are out of sync and in a dead lock mode.   If `parallel::clusterExport()` and `parallel::clusterEvalQ()` would be atomic (either both of send and receive are done or none), then I think things would work as expected.

That's my best guess on what the problem is - it's a issue with the 'parallel' package.  I'm not sure there's an easy solution / fix to the problem, but it is certainly worth discussing on the R devel mailing list.  Maybe there is a way to at least lower the risk for ending up in this dead lock situation.  So, please post to R devel with a minimal reproducible example (ideally with 'brms' so that people could try it themselves) - that way you're increasing your chances for getting useful feedback.

**Comment by paul-buerkner** [comment] 2016-07-24 12:48
Thanks @HenrikBengtsson for your insights! You are right that it is very likely a problem of the parallel package. I will post the question on R devel.

**Comment by paul-buerkner** [comment] 2017-07-01 15:38
I currently don't see any chance of improving this from the **brms** side so I am closing this issue. Hopefully this will be tackled at some point in the **parallel** package

**Closed by paul-buerkner** 2017-07-01 15:38 UTC
Labels: enhancement
