### ISSUE TITLE
Compile error with custom non-linear function

### ISSUE THREAD

**Issue by rspadial** [paul-buerkner/brms#1178] opened 2021-06-09 13:00 UTC
When I try to run brms with a custom non-linear function that uses "integrate_1d" I get a compilation error regarding the arguments passed onto the function. Here is a simplified example:

`
```
stan_funs <- "
  real integrand(real x, real xc, real[] theta, real[] x_r, int[] x_i) {
	  real a = theta[1];
      real p = x_r[1];                	
    return x*exp(-(-log(p))^a);
  }
  real integralfun(data real p, real a, data int xi) {
  	  	return integrate_1d(integrand, 0.0, 1.0, {a}, {p}, {xi}, 0.01);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions") 

nlform <- bf(wtp ~ integralfun(prob, a, id),
             a ~ (1|id), nl = TRUE)
nlprior <- c(prior(lognormal(2, 1), lb=0,  nlpar = "a"))
        
fit2 <- brm(formula = nlform, data = wtpdata, family = zero_one_inflated_beta,
                 prior = nlprior, control = list(adapt_delta = 0.9), stanvars = stanvars)
`
```

I get the following error message:

> Error in compileCode(f, code, language = language, verbose = verbose) : 
                                          ^/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/arr/functor/integrate_1d.hpp:195:15: note: candidate function template not viable: no known conversion from 'vector<local_scalar_t__>' to 'const vector<double>' for 4th argumentinline double integrate_1d(              ^22 warnings and 1 error generated.make: *** [file5c9845fad7bc.o] Error 1
Error in sink(type = "output") : invalid connection

I've tried a couple of variations without success, like this one:
````
stan_funs <- "
  real integrand(real x, real xc, real[] theta, real[] x_r, int[] x_i) {
	        real p = x_r[1];                	
    return x*exp(-(-log(p)));
  }
  real integralfun(data real p, real[] a, data int xi) {
  		
  	  	return integrate_1d(integrand, 0.0, 1.0, a, {p}, {xi}, 0.01);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions") 

nlform <- bf(wtp ~ integralfun(prob, rep_array(a,1), id),
             a ~ (1|id), nl = TRUE)
nlprior <- c(prior(lognormal(2, 1), lb=0,  nlpar = "a"))
        
fit2 <- brm(formula = nlform, data = wtpdata, family = zero_one_inflated_beta,
                 prior = nlprior, control = list(adapt_delta = 0.9), stanvars = stanvars)
````

I get a slightly different error saying

> ...no known conversion from 'const vector<stan::math::var>' to 'const vector<double>' for 4th argumentinline double integrate_1d(

I have tried the same code without using "integrate_1d" and brms works fine.

**Comment by wds15** [comment] 2021-06-09 13:04
Have you ever managed to export a Stan function which uses integrate_1d to R? I think that is not possible; at least with rstan 2.21.

**Comment by rspadial** [comment] 2021-06-09 13:08
> Have you ever managed to export a Stan function which uses integrate_1d to R? I think that is not possible; at least with rstan 2.21.

This is my first time using brms and Stan so I've never tried this before. Does this mean that brms cannot be used to estimate a non-linear function involving numerical integration?

**Comment by wds15** [comment] 2021-06-09 13:13
Apologies... I misread. I thought you wanted to expose those functions to R.

No, what you do above will work if written down correctly. Can you please repost on the discourse forums? This is not a bug in brms, but rather an issue with how you call the integrate function. Other users will benefit from a discussion there. Thanks.

**Comment by paul-buerkner** [comment] 2021-06-09 14:15
Thanks @wds15 for your comments. I am closing this here but please ask on https://discourse.mc-stan.org/

**Closed by paul-buerkner** 2021-06-09 14:15 UTC
