### ISSUE TITLE
Right-censored data

### ISSUE THREAD

**Issue by simoncolumbus** [paul-buerkner/brms#1423] opened 2022-11-08 16:22 UTC
I am encountering a persistent error trying to fit a model with right censoring (but not left censoring). MWE:

```r
# Censoring example
set.seed(25)
n <- 5000
t1 <- 106 # Right censoring cutoff
t2 <- 94 # Left censoring cutoff

d <- tibble(y = rnorm(n, mean = 100, sd = 15),
            x = rnorm(n, 0, 1)) %>% 
  # Right censored variables
  mutate(y1   = if_else(y > t1, t1, y),
         cen1 = if_else(y > t1, "right", "none")) %>%
  # Left censored variables
  mutate(y2 = if_else(y < t2, t2, y),
         cen2 = if_else(y < t2, "left", "none"))

# Right censoring
brm(bf(y1 | cens(cen1) ~ x),
    data = d)

Compiling Stan program...
Start sampling
SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
Chain 1: Rejecting initial value:
Chain 1:   Log probability evaluates to log(0), i.e. negative infinity.
Chain 1:   Stan can't start sampling from this initial value.
...
Chain 1: Initialization between (-2, 2) failed after 100 attempts. 
Chain 1:  Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.
[1] "Error in sampler$call_sampler(args_list[[i]]) : Initialization failed."
[1] "error occurred during calling the sampler; sampling not done"
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: y1 | cens(cen1) ~ x 
   Data: d (Number of observations: 5000) 
```

This occurs across multiple datasets and different kinds of models (linear mixed model with one random factor; mixed-effects location scale model), and when init = 0.

In contrast, left-censoring works:

```r
# Left censoring
brm(bf(y2 | cens(cen2) ~ x),
    data = d)
```

I tested this on two machines. 

```r
# Machine 1
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] brms_2.17.0     Rcpp_1.0.9      forcats_0.5.1   stringr_1.4.0   dplyr_1.0.6     purrr_0.3.4     readr_1.4.0     tidyr_1.1.3     tibble_3.1.8   
[10] ggplot2_3.3.6   tidyverse_1.3.1

# Machine 2
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] brms_2.17.0     Rcpp_1.0.9      forcats_0.5.2   stringr_1.4.1   dplyr_1.0.9     purrr_0.3.4     readr_2.1.2     tidyr_1.2.0     tibble_3.1.8   
[10] ggplot2_3.3.6   tidyverse_1.3.2

```

**Comment by paul-buerkner** [comment] 2022-11-09 11:41
This is super strange. The brms generated Stan code looks correct to me. When I am changing the family from `gaussian` to `student` or `weibull` for example, it works without complains. Same with left-censoring as you say.

This leads me to believe that there might be a bug in Stan's `normal_lccdf`. Not sure who to tag but perhaps @wds15 has an idea.

**Comment by mvuorre** [comment] 2022-11-11 11:10
Weird, it doesn't work on my Mac either. I used to run these models without a problem ~3 months ago. Sorry I don't know what versions, but they would have been up to date then.

**Comment by realkrantz** [comment] 2022-11-11 12:08
But this e.g. works:

```
# Right censoring
dd<-d|>slice(4990:5000)
brm(bf(y1 | cens(cen1) ~ x),
    data = dd)
```

```
SAMPLING FOR MODEL '8703f9dc862d2b049085bf1c00a8d6d7' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 0 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)

....

Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 4: 
Chain 4:  Elapsed Time: 0.081 seconds (Warm-up)
Chain 4:                0.043 seconds (Sampling)
Chain 4:                0.124 seconds (Total)
Chain 4: 
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: y1 | cens(cen1) ~ x 
   Data: dd (Number of observations: 11) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    90.79      3.90    83.13    98.78 1.00     3411     2114
x            -5.06      5.09   -15.32     5.12 1.00     3097     2161

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma    13.23      3.19     8.54    20.73 1.00     2564     2511

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).

```

**Comment by simoncolumbus** [comment] 2022-11-11 12:29
@realkrantz If you are using the seed from the original MWE, this slice does not contain any right-censored cases:

```r
set.seed(25)
n <- 5000
t1 <- 106 # Right censoring cutoff
t2 <- 94 # Left censoring cutoff

d <- tibble(y = rnorm(n, mean = 100, sd = 15),
            x = rnorm(n, 0, 1)) %>% 
  # Right censored variables
  mutate(y1   = if_else(y > t1, t1, y),
         cen1 = if_else(y > t1, "right", "none")) %>%
  # Left censored variables
  mutate(y2 = if_else(y < t2, t2, y),
         cen2 = if_else(y < t2, "left", "none"))

dd<-d %>% slice(4990:5000)

dd
# A tibble: 11 x 6
       y       x    y1 cen1     y2 cen2 
   <dbl>   <dbl> <dbl> <chr> <dbl> <chr>
 1 105.  -1.65   105.  none  105.  none 
 2  95.4 -0.268   95.4 none   95.4 none 
 3 102.  -0.497  102.  none  102.  none 
 4  92.7  0.401   92.7 none   94   left 
 5  93.2 -0.321   93.2 none   94   left 
 6  67.5 -0.0766  67.5 none   94   left 
 7 102.   1.42   102.  none  102.  none 
 8  84.5  0.271   84.5 none   94   left 
 9  76.2  0.197   76.2 none   94   left 
10 103.  -1.24   103.  none  103.  none 
11  80.5  0.433   80.5 none   94   left 
```

A slice that contains such cases does not work:

```r
ddd <- d %>% slice(1:10)
ddd
# A tibble: 10 x 6
       y      x    y1 cen1     y2 cen2 
   <dbl>  <dbl> <dbl> <chr> <dbl> <chr>
 1  96.8 -0.870  96.8 none   96.8 none 
 2  84.4  1.94   84.4 none   94   left 
 3  82.7  2.13   82.7 none   94   left 
 4 105.   0.741 105.  none  105.  none 
 5  77.5  0.383  77.5 none   94   left 
 6  93.3 -0.490  93.3 none   94   left 
 7 126.  -0.396 106   right 126.  none 
 8 108.  -0.537 106   right 108.  none 
 9 101.   1.20  101.  none  101.  none 
10  99.1 -1.48   99.1 none   99.1 none 

brm(bf(y1 | cens(cen1) ~ x),
    data = ddd)
```

**Comment by realkrantz** [comment] 2022-11-11 12:54
True @simoncolumbus.

**Comment by paul-buerkner** [comment] 2022-12-15 12:20
I am closing this issue since, to the best of our understanding, it is not a bug in brms. I have written in the Stan math issue in the hope that someone will check it out from the Stan math side.

**Closed by paul-buerkner** 2022-12-15 12:20 UTC
Labels: bug
