### ISSUE TITLE
emmeans interface

### ISSUE THREAD

**Issue by rvlenth** [paul-buerkner/brms#418] opened 2018-04-29 16:43 UTC
I was alerted to some discussion on interfacing to the **emmeans** package in the Google group. I was going to contribute to the discussion there, but (based on browser warnings) was unable to find a way to securely log in. So I will comment on a few things here, in hopes that it will clarify some things

> **emmeans** primarily does frequentist analysis (even for Bayesian models) and I don’t want to actively support that kind of analysis. 

I admit that **emmeans** places a lot of emphasis on frequentist methods, but I want to adequately support Bayesian approaches as well.

> Also, most of emmeans summaries are frequentist ... there is some mcmc functionality implemented, but more as a side track than as a main feature I feel.

Please enlighten me. My impression has been that Bayesians already have the tools they need in packages like **bayesplot**, **coda**, etc., to do what they want, once they get a posterior sample; and that I do provide. So can you give me an idea of what else I could provide? I’d be happy to consider additional or alternative methods that are needed to make it more appealing to Bayesians. Perhaps the `summary()` method should display something different. I can believe that; describe what you'd like to see.

> I have been reading the documentation of extending **emmeans**. The problem I see is that we can only support a very minor class of **brms** models with **emmeans**, which implies a lot of special case coding and checking.

Is this really true? Most of what **emmeans** does for Bayesian models is very, very simple in concept: It just calculates a posterior sample of predictions at each node in the reference grid, which the user may then access via `as.mcmc()`. I have hardly looked at this package yet, but I find it pretty difficult to believe that it would be hard to support a good share of the models, assuming they are based on linear or generalized linear models -- especially since you don't really want all those frequentist results like variances and covariances. All it really needs to do is create a model matrix for the reference grid. One of the real advantages of Bayesian methods is that you don't get into thorny issues like standard errors and degrees of freedom.  I will take a look and see what I can do easily; and report back.

**Comment by rvlenth** [comment] 2018-04-29 16:56
One very simple idea: In the `summary()` method for `emmGrid` objects, it could check and if there is a posterior sample, it displays estimates and HPD intervals for each case. Then users who fitted a Bayesian model would see that summary instead of the frequentist one. Would `coda::HPDinterval()` be a good choice?

**Comment by paul-buerkner** [comment] 2018-04-29 17:04
Hi Russel, thanks for the feedback! Don't misunderstand what I wrote as a critque to **emmeans**. It does a lot of cool stuff both frequentist and Bayesian. I know (and think have also written it) that you are supporting posterior samples, which is really all what Bayesian models need, as you point out. 

So you are basically already providing everthing a Bayesian model needs. My concern is different. Since the main methods (`summary` in particular as you wrote) show the frequentist results, users will use these results primarily and much more likely than the Bayesian methods (`as.mcmc`) you provide. 

As I wrote that, you wrote your second post basically mirroing my ideas. Yes, showing the Bayesian results if posterior samples are available is a good idea. I think `coda::HPDinterval()` is a good way to go. Maybe, in this case, one coule think of **emmeans** not requiring the frequentist results to be present at all in the `emmGrid` object? (Don't know if this is compatible with the internal structure of **emmeans**)

With regard to the range of supported models, it depends on ones focus. Since **brms** supports a lot of advanced models in which all parameters of a distribution can be predicted (distributional regression), parameteric non-linear models and also multivariate models, the regression parameters have to be divided into subsets and each subset has to be passed to the methods of **emmeans** separately. This is a lot of work that needs to be done from my side, and I am currently hesitant to do given that I have currently very limited time to work on new feature for brms.

**Comment by paul-buerkner** [comment] 2018-05-01 14:25
Great, thanks! I think both mean and median is fine as long as it's documented. brms has the option to show either one of the two (mean is default). Other packages use the median as the default so I think it is up to you. It might be confusing naming the column `emmean` though if one uses the median.

**Comment by rvlenth** [comment] 2018-05-01 14:30
BTW, on not requiring frequentist results to be present in the `emmGrid` object -- that is certainly reasonable, and probably doable, but could open up a bigger can of worms than I expect. There are certainly several places where I'd have to work around not having conformable stuff in the `bhat` or `V` slot. I'll think about the tradeoff there.

**Comment by paul-buerkner** [comment] 2018-05-01 14:33
I don't want to push to hard on this. It's just something that came to my mind.

**Comment by paul-buerkner** [comment] 2018-06-22 07:29
I just wanted to check in and ask whether there is more to discuss in this issue? I think we now have an issue on the emmeans github page (https://github.com/rvlenth/emmeans/issues/34), which is probably the better place to discuss anything related to emmeans supporting brms. Would you be ok if I closed this issue, here?

**Comment by rvlenth** [comment] 2018-06-22 11:29
It’s ok with me to close this. I have not gotten around to extending the bend support for emmeans.

Sent from my iPhone

On Jun 22, 2018, at 2:29 AM, Paul-Christian Bürkner <notifications@github.com<mailto:notifications@github.com>> wrote:


I just wanted to check in and ask whether there is more to discuss in this issue? I think we now have an issue on the emmeans github page (rvlenth/emmeans#34<https://github.com/rvlenth/emmeans/issues/34>), which is probably the better place to discuss anything related to emmeans supporting brms. Would you be ok if I closed this issue, here?

**Comment by paul-buerkner** [comment] 2018-07-03 07:47
In the light of https://github.com/rvlenth/emmeans/issues/43 it makes sense to think about a brms supporting emmans natively at some point. Reopening this issue again.

**Comment by paul-buerkner** [comment] 2020-05-14 21:31
Implemented via PR #898

**Closed by paul-buerkner** 2020-05-14 21:31 UTC
Labels: feature, post-processing
