### ISSUE TITLE
Combining censoring with unstructured covariance matrices

### ISSUE THREAD

**Issue by bjoernholzhauer** [paul-buerkner/brms#1447] opened 2023-01-13 09:03 UTC
Combining censoring with `autocor = ~ unstr()` e.g. like this
```
brm( formula = bf( AVAL | cens(censor) ~ 0 + AVISIT + BASE + BASE:AVISIT + TRT01P + TRT01P:AVISIT,  
                   autocor=~unstr(time=AVISIT, gr=USUBJID), 
                   sigma ~ AVISIT, center=FALSE))
```
results  in "Error: Invalid addition arguments for this model." In contrast, removing the `autocor` argument. I tested that changing the formula to `0 + (AVISIT|USUBJID) + BASE + BASE:AVISIT + TRT01P + TRT01P:AVISIT` works  (that of course no longer gives us the desired covariance structure) and similarly, removing the censoring makes the code run. So, it seems like the issue is in the combination of the two features (censoring & `autocor=~unstr()`).

This combination of features is actually very interesting. E.g. in clinical trials/drug development we often have limits of quantification (LoQs) for biomarkers and PK concentrations. I.e. when we measure something, but for very low (or high) values we can only get something like <LLoQ (or >ULoQ) from the assay we use. At the moment, there's no software that conveniently enables a combination of censoring and repeated measures with an unstructured covariance matrix (of course, various packages for survival analysis can do simple random effects = compound symmetric covariance structure).

Reproducible example:
```
library(tidyverse)
library(mvtnorm)
library(brms)

#### Simulate data -----

apply_colnames <- function(x,y){
  colnames(x) <- y
  return(x)
}
months <- c(0, 0.5, 1, 3, 6, 9, 12)
corr_matrix <- expand_grid(month1 = months, month2 = months) %>%
  mutate(correlations = ifelse(month1==month2, 1,
                               plogis( 1.3 - 0.075*abs(month1-month2) - 0.01 * pmin(month1, month2) ))) %>%
  pivot_wider(id_cols="month1", names_from="month2", values_from="correlations") %>%
  dplyr::select(-month1) %>%
  as.matrix()
sds <- exp(-0.95 + months * 0.005)
cov_matrix <- diag(sds) %*% corr_matrix %*% diag(sds)

mean_vector <- 0.74 + months/12*0.02
N <- 1000
N_total <- 100
set.seed(2023)
excercise1 <- mvtnorm::rmvnorm(n=N, mean=mean_vector, sigma = cov_matrix) %>%
  apply_colnames(paste0("Month ", months)) %>%
  as_tibble() %>%
  filter(`Month 0` >=round(log(2.0), digits=2)) %>%
  filter(row_number()<=N_total) %>%
  mutate(USUBJID = row_number()) %>%
  pivot_longer(cols=starts_with("Month"), names_to = "AVISIT", values_to="AVAL") %>%
  mutate(ADY = as.integer(as.numeric(str_extract(AVISIT, "[0-9]+"))*365.25/12),
         TRT01P = ifelse(USUBJID<N_total/2, "Placebo", "Drug"),
         AVAL=exp(AVAL + log(0.6) * ADY/(ADY+30) * (TRT01P=="Drug")),
         AVALC = case_when(AVAL<1 ~ "<1",
                           AVAL>5.5 ~ ">5.5",
                           TRUE ~ as.character(round(AVAL,digits=2))),
         AVAL = case_when(AVAL<1 ~ NA_real_,
                          AVAL>5.5 ~ NA_real_,
                          TRUE ~ round(AVAL,digits=2)),
         PARAM = "Biomarker 1",
         PARAMCD = "BIOM1")

#### Modify data to prepare for modeling -----

excercise1a <- excercise1 %>%
  filter(AVISIT!="Month 0") %>%
  left_join(excercise1 %>% 
              filter(AVISIT=="Month 0") %>% 
              mutate(BASE = case_when(str_detect(AVALC, "<") ~ 0.5*as.numeric(str_extract(AVALC, "[0-9\\.]+")),
                                      str_detect(AVALC, ">") ~ 1.5*as.numeric(str_extract(AVALC, "[0-9\\.]+")),
                                      TRUE ~ AVAL)) %>%
              dplyr::select(USUBJID, BASE), 
            by="USUBJID") %>%
  mutate(AVAL = log(AVAL),
         BASE = log(BASE),
         PARAM = "log Biomarker 1",
         PARAMCD = "LOGBIOM1",
         censor = case_when(
           str_detect(AVALC, "<") ~ "left", 
           str_detect(AVALC, ">") ~ "right",
           TRUE ~ "none"),
         AVAL = ifelse(censor=="none", AVAL, 
                       log(as.numeric(str_extract(AVALC, "[0-9\\.]+")))),
         USUBJID = factor(USUBJID))

#### brms models -----

# Gives "Error: Invalid addition arguments for this model."
brm( formula = bf( AVAL | cens(censor) ~ 0 + AVISIT + BASE + BASE:AVISIT + TRT01P + TRT01P:AVISIT,  
                   autocor=~unstr(time=AVISIT, gr=USUBJID), sigma ~ AVISIT, center=FALSE),
     data = excercise1a,
     control = list(adapt_delta=0.99),
     prior= prior(class="b", student_t(3, 0, 25)))

# Works
brm( formula = bf( AVAL | cens(censor) ~ 0 + (AVISIT|USUBJID) + BASE + BASE:AVISIT + TRT01P + TRT01P:AVISIT,  
                   sigma ~ AVISIT, center=FALSE),
     data = excercise1a,
     control = list(adapt_delta=0.99),
     prior= prior(class="b", student_t(3, 0, 25)))
```

**System:** Microsoft Windows 10
**R version:** 4.1.1 (2021-08-10)
**brms version:** Current development version installed on 13 Jan 2023 via `remotes::install_github("paul-buerkner/brms")` (same on branch for the autocor-unstr feature)

**Comment by paul-buerkner** [comment] 2023-01-13 10:05
The problem is this: For unstr covariance matrix we have to use a multivariate (normal) likelihood. For censoring we need the CDF and CCDF functions, which we currently don't have for the multivariate normal in Stan to my unstanding. Unfortunately, I don't see a path to combine these features at the moment.

**Comment by paul-buerkner** [comment] 2024-01-26 17:32
I will close this issue for now to clean up the issue tracker a bit. Feel free to reopen it once the relevant Stan functionality becomes available.

**Closed by paul-buerkner** 2024-01-26 17:32 UTC
Labels: feature
