### ISSUE TITLE
A (not so) nice one (possible PRBCAK...)

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#503] opened 2018-08-19 12:24 UTC
I'm trying to generate prograpatically a set of models for the same data. Current state of my draft : 
```

DoAn2 <- function(Nom, Scale=1, Exp=3, Graine=1515) {
    Data <- Crits[[Nom]]
    F1 <- brmsformula(changement ~ s(prévision, by=Cis) + Cis,
                      family=gaussian, sigma ~ Cis)
    F2 <- brmsformula(changement ~ s(prévision, by=Cis),
                      family=gaussian, sigma ~ Cis)
    F3 <- brmsformula(changement ~ s(prévision) + Cis,
                      family=gaussian, sigma ~ Cis)
    F4 <- brmsformula(changement ~ s(prévision),
                      family=gaussian, sigma ~ Cis)
    P0 <- brmsformula(changement ~ Cis,
                      family=gaussian, sigma ~ Cis)
    L1 <- brmsformula(changement ~ prévision * Cis,
                      family=gaussian, sigma ~ Cis)
    L2 <- brmsformula(changement ~ prévision + prévision:Cis,
                      family=gaussian, sigma ~ Cis)
    L3 <- brmsformula(changement ~ prévision + Cis,
                      family=gaussian, sigma ~ Cis)
    L4 <- brmsformula(changement ~ prévision,
                      family=gaussian, sigma ~ Cis)
    P1 <- c(prior(student_t(3,0,10*Scale), class="b"),
            prior(student_t(3,0,10), class="sds"),
            prior(normal(0,3), coef="CisTRUE", dpar="sigma", class="b"))
    P0 <- c(prior(student_t(3,0,10*Scale), class="b"),
            prior(normal(0,3), coef="CisTRUE",  dpar="sigma", class="b"))
    do1M <- function(Data, F, P) {
        E <- Exp
        browser()
        ## Here we stop to examine, because the next statement will eturn to toplevel
        ## without returning anything.
        B <- brm(F, data=Data, prior=P, sample_prior=TRUE,
                 save_all_pars=TRUE, seed=Graine, iter=2000, warmup=1000, 
                 control=list(adapt_delta=1-0.8^E))
        while ((has_warning(summary(B)))&& (E<12)) {
            E <- E+1
            B <- update(B, control=list(adapt_delta=1-0.8^E))
        }
        B <- add_ic(B, ic=c("waic", "loo", "marglik", "r2"),
                    reloo=TRUE, silent=TRUE)
        return(B)
    }
    do1M(Data, F1, P1)
}
```
If we type manually `foo <- brm(F, P, data=Data, sample_prior=TRUE, save_all_pars=TRUE, seed=Graine, iter=2000, warmup=1000, control=list(adapt_delta=1-0.8^E))`, the model compiles and runs, but does not use the priors P : 
```
Browse[2]> prior_summary(foo)
                 prior     class                  coef group resp  dpar nlpar
1                              b                                             
2                              b               CisTRUE                       
3                              b sprévision:CisFALSE_1                       
4                              b  sprévision:CisTRUE_1                       
5                              b                                  sigma      
6                              b               CisTRUE            sigma      
7  student_t(3, 4, 10) Intercept                                             
8  student_t(3, 0, 10) Intercept                                  sigma      
9  student_t(3, 0, 10)       sds                                             
10                           sds   s(prévision,by=Cis)                       
   bound
1       
2       
3       
4       
5       
6       
7       
8       
9       
10      
```

Conversively, if we type : 
```
Browse[2]> foo <- brm(F, prior=P, data=Data, sample_prior=TRUE, save_all_pars=TRUE, seed=Graine, iter=2000, warmup=1000, control=list(adapt_delta=1-0.8^E))
Browse[2]> 
```
nothing **(NOTHING)** happens. Neither `foo` nor `print(foo` prints anything.

One can also check that when one uses an explicit (online) specification for the prior instead of a precomputed quantity, the prior is accounted for.

Tentative conclusion : there is a problem in the parsing...

Ouch !

**Comment by paul-buerkner** [comment] 2018-08-19 13:29
`foo <- brm(F, P, data=Data, sample_prior=TRUE, ...)` should indeed be `foo <- brm(F, prior = P, data=Data, sample_prior=TRUE, ...)` because else `P` will be used as argument `family`. 

Apart from that, I can't tell you much without having a reproducible example.

**Comment by paul-buerkner** [comment] 2018-08-19 14:41
It turns out to be an error in the stan code that is currently surpressed by `brm` (which shouldn't happen). Basically, it tells you that `Scale` cannot be found, which you will see when you replace `brm` with `make_stancode`.

**Comment by paul-buerkner** [comment] 2018-08-19 14:49
After installing the latest github version, you should be seeing the Stan parser error that causes `brm` to fail.

**Comment by EmmanuelCharpentier** [comment] 2018-08-19 16:04
> Basically, it tells you that Scale cannot be found...

<Donning a brown paperbag on face>

Turns out than in my edit fight, I dropped an all-important `stanvars=stanvar(Scale,"Scale", scode="real<lower=0> Scale;"),` option.

I've been editing this one too long : I can no longer see my mistakes...  

Thanks a lot !

I suppose that this can be closed now ?

**Comment by paul-buerkner** [comment] 2018-08-19 16:41
Yes, I think we can close this.

**Closed by paul-buerkner** 2018-08-19 16:41 UTC
Labels: code
