### ISSUE TITLE
New data with bayes_R2 doesn't work

### ISSUE THREAD

**Issue by ashwanijha1** [paul-buerkner/brms#1710] opened 2024-11-23 10:22 UTC
Thansk for this fantastic package!

I am getting exactly the same result for R2 the following three commands:

r2_d0_brms <- brms::bayes_R2(fit, newdata = NULL, ndraws=Ndraws, allow_new_levels=TRUE, summary=TRUE)
r2_dnew1_brms <- brms::bayes_R2(fit, newdata=data1[,1:10], ndraws=Ndraws, allow_new_levels=TRUE, summary=TRUE)
r2_dnew2_brms <- brms::bayes_R2(fit, newdata=new_dataset, ndraws=Ndraws, allow_new_levels=TRUE, summary=TRUE)

It seems that specifying newdata doesn't make a difference?

Thanks,
Ash

**Comment by paul-buerkner** [comment] 2024-11-23 13:48
Coud you please provide a minimal reproducible example?

**Comment by ashwanijha1** [comment] 2024-11-26 12:08
Yes sorry,

In the code below r2_iris_brms and r2_iris2_brms have the same value and they should be different. Also there is no effect of changing Ndraws.

#########
rm(list = ls()) 
library(tidyverse)
library(rstan)
library(brms)

data("iris")
head(iris)

iris$species_setosa <- as.integer(iris$Species=="setosa") # create binary outcome

# create fake dataset 2 (shuffle outcome only for demonstration) 
iris2 <- iris
iris2$species_setosa <- sample(iris2$species_setosa)

#  fit model
formula <- "species_setosa ~ 1 + Sepal.Length"
fit <- brm(formula, data = iris, family=bernoulli(), save_pars = save_pars(all = TRUE), control = list(adapt_delta =0.80), iter=2000, seed=123)
fit <- add_criterion(fit, "bayes_R2", save_fits = TRUE)

# generate R2 for training data (iris) and test data (iris2) - should be different
Ndraws=1000 # no effect of changing this on output below
r2_iris_brms <- brms::bayes_R2(fit, newdata=NULL, ndraws=Ndraws, allow_new_levels=TRUE, summary=TRUE)
r2_iris2_brms <- brms::bayes_R2(fit, newdata=iris2, ndraws=Ndraws, allow_new_levels=TRUE, summary=TRUE)

**Comment by paul-buerkner** [comment] 2024-11-26 12:55
The reason is that, once you have stored your `bayes_R2` results via `add_criterion`, it will always just get these results and ignore new arguments. 

I believe I had changed this behavior already for `loo` and friends, such that it would recompute as soon as you provide certain arguments. Perhaps I need to update `bayes_R2` too, to handle this case correctly. Will investigate.

**Comment by paul-buerkner** [comment] 2024-11-26 13:14
It was indeed a big. Fixed now. Thank you again!

**Closed by paul-buerkner** 2024-11-26 13:14 UTC
Labels: bug
