### ISSUE TITLE
Test speed advantage of using ulpdf instead of lpdf

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1017] opened 2020-10-15 18:59 UTC
brms uses always `target +=` instead of `~`. The tilde version uses log unnormalized pdf to avoid computation of constants that don't affect sampling. brms uses `target +=` with `*_lpdf` that are log normalized pdfs to support marginal likelihood computations, but then computes the constants also when not needed. The new Stan release 2.25 has support for `*_lupdf` that provide the log unnormalized pdf, so it would be possible to provide an option switch normalization off. It would be useful to make some speed tests with models that have expensive normalization terms and especially with for loops so that the normalization terms are computed many times. Unlikely of order of magnitude speed-ups but can be significant speed-ups for some models.

**Comment by wds15** [comment] 2020-10-15 19:03
Test poisson and you should see a difference (and also dropping those ccdf calls should help) in speed.

**Comment by andrjohns** [comment] 2020-11-09 09:49
Correct me if I'm wrong, but doesn't ```brms``` need to keep the ```_lpdf``` construction for compatibility with ```bridgesampling``` post-processing? Since that needs the normalising constants?

**Comment by andrjohns** [comment] 2020-11-09 09:50
As soon I hit comment I saw the part of the issue that mentioned the option to switch normalising on/off, never mind me

**Comment by andrjohns** [comment] 2020-11-09 14:22
Paul, I worked up an initial implementation on this [branch](https://github.com/paul-buerkner/brms/compare/master...andrjohns:feature/issue-1017-lupdf). It's currently only for simple outcome likelihoods but let me know if the basic approach is consistent with how you would tackle it, or if you'd prefer a different method.

As an example, calling:
```
make_stancode(rating ~ treat + period + carry,
              data = inhaler, normalise = FALSE)
```

Gives the model block:
```
  // likelihood including all constants
  if (!prior_only) {
    target += normal_id_glm_lupdf(Y | Xc, Intercept, b, sigma);
  }
  // priors including all constants
  target += student_t_lpdf(Intercept | 3, 1, 2.5);
  target += student_t_lpdf(sigma | 3, 0, 2.5)
    - 1 * student_t_lccdf(0 | 3, 0, 2.5);
}
```

Which compiles and samples under the ```cmdstanr``` backend

**Comment by paul-buerkner** [comment] 2020-11-09 14:59
Yes, this looks exactly like the approach I would have used!

**Comment by rok-cesnovar** [comment] 2020-11-09 15:05
The problem is again thie only works with stan2.25 and on.

**Comment by paul-buerkner** [comment] 2020-11-09 15:19
Yes, so we should only merge once rstan is at 2.25 as well or make the stan code generation conditional, which I personally want to avoid.

**Comment by paul-buerkner** [comment] 2020-11-09 15:19
Or just allow `normalize = FALSE` when cmdstanr with Stan 2.25+ is used, which would be fine and easy to check.

**Comment by andrjohns** [comment] 2020-11-10 03:58
Great! Will work on updating and testing the rest of the likelihoods

**Comment by andrjohns** [comment] 2020-11-10 07:46
Quick clarification for the priors, am I right in assuming that if ```normalise=TRUE``` gives:
```
  target += student_t_lpdf(Intercept | 3, 1, 2.5);
  target += student_t_lpdf(sigma | 3, 0, 2.5)
    - 1 * student_t_lccdf(0 | 3, 0, 2.5);
```
Then ```normalise = FALSE``` gives:
```
  target += student_t_lupdf(Intercept | 3, 1, 2.5);
  target += student_t_lupdf(sigma | 3, 0, 2.5);
```

In other words it no longer needs the ```lccdf``` adjustments for parameters with bounds, right?

**Comment by paul-buerkner** [comment] 2020-11-10 07:47
Correct.

Andrew Johnson <notifications@github.com> schrieb am Di., 10. Nov. 2020,
08:46:

**Comment by andrjohns** [comment] 2020-11-10 07:48
Thanks!

**Comment by andrjohns** [comment] 2020-11-30 04:39
Paul - got this pretty close to a PR-ready state ([on this branch](https://github.com/paul-buerkner/brms/compare/master...andrjohns:feature/issue-1017-lupdf)). I've tested the models in the ```tests.model_new.R``` file, and all looks good. Do you have any other models that this should be tested across before I move to a PR?

**Comment by paul-buerkner** [comment] 2020-11-30 07:51
Amazing, thank you! Testing all from `model_new` seems sufficient I think. Once you make a PR, I am happy to review it and perhaps make some edits.

**Comment by paul-buerkner** [comment] 2021-02-05 08:02
I realize we can close this isse since your PR has beem merged already. Thank you again for working in it!

**Closed by paul-buerkner** 2021-02-05 08:02 UTC
Labels: efficiency, feature, good first issue
