### ISSUE TITLE
Possible bug : can't have group-specific degrees of freedom in  `family=student`

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#512] opened 2018-08-29 21:17 UTC
Question : how to process data with (suspected) outliers. Cas of the
comparison of to means.

Tentative answer : model them as emanating from an outlier-tolerant
distribution. We’ll try Student’s *t* distribution, with degrees of
freedom estimated from the
data.

## Simulated data

[DataAndStanModels.zip](https://github.com/paul-buerkner/brms/files/2333786/DataAndStanModels.zip)

A set of 60 values in two groups has been simulated (`source` the `Sim.Rdata` (yes, my bad : I confused `dump` and `save`...) in the enclosed archive).

  - The “Ideal” dataset has been sampled from Normal(0,1) and
    Nprmal(1,1) distributions.

  - The “Reel” dataset has 10 of its value perturbated by N(0,5) noise,
    simulating outliers

These data can be easily visualized
:

<img src="ShowSimData-1.png" title="Données simulées" alt="Données simulées" style="display: block; margin: auto;" /><img src="ShowSimData-2.png" title="Données simulées" alt="Données simulées" style="display: block; margin: auto;" />

![showsimdata-1](https://user-images.githubusercontent.com/7955276/44815399-b3f47800-abdf-11e8-97fd-4853906c3666.png)
![showsimdata-2](https://user-images.githubusercontent.com/7955276/44815400-b3f47800-abdf-11e8-88c3-9f0d68ba817b.png)

The `t.test` function illustrates the impact of the outliers on the
comparison of means :

``` r
cat('"Normal" dataset :\n\n')
```

    ## "Normal" dataset :

``` r
t.test(Val~Grp, data=Sim[["Ideal"]])
```

    ## 
    ##  Welch Two Sample t-test
    ## 
    ## data:  Val by Grp
    ## t = -2.7674, df = 56.726, p-value = 0.007617
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -1.134728 -0.181913
    ## sample estimates:
    ## mean in group A mean in group B 
    ##       0.2177439       0.8760643

``` r
cat("\nDataset with sumulated outliers :\n\n")
```

    ## 
    ## Dataset with sumulated outliers :

``` r
t.test(Val~Grp, data=Sim[["Reel"]])
```

    ## 
    ##  Welch Two Sample t-test
    ## 
    ## data:  Val by Grp
    ## t = -0.39934, df = 37.474, p-value = 0.6919
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -1.2758039  0.8555527
    ## sample estimates:
    ## mean in group A mean in group B 
    ##       0.4723706       0.6824963

The same difficulties can be reproduced with a Stan model applied to
both datasets (see the enclosed `CmpMoy.stan` file in the enclosed archive) :

``` r
CmpMoy.M <- stan_model(file="CmpMoy.stan", model_name="Cmp.moy")
CmpMoy.F.I <- sampling(CmpMoy.M,
                       data=with(Sim[["Ideal"]],
                                 list(nObs=length(Val),
                                      Grp=as.integer(Grp),
                                      Val=Val)),
                       open_progress=FALSE, show_messages=FALSE, seed=1685)
CmpMoy.F.R <- sampling(CmpMoy.M,
                       data=with(Sim[["Reel"]],
                                 list(nObs=length(Val),
                                      Grp=as.integer(Grp),
                                      Val=Val)),
                       open_progress=FALSE, show_messages=FALSE, seed=1715)
```

``` r
CmpMoy.F.I
```

    ## Inference for Stan model: Cmp.moy.
    ## 4 chains, each with iter=2000; warmup=1000; thin=1; 
    ## post-warmup draws per chain=1000, total post-warmup draws=4000.
    ## 
    ##            mean se_mean   sd   2.5%    25%    50%    75%  97.5% n_eff Rhat
    ## mu[1]      0.22    0.00 0.19  -0.15   0.09   0.22   0.35   0.61  3840    1
    ## mu[2]      0.87    0.00 0.16   0.56   0.77   0.87   0.98   1.19  4000    1
    ## sigma[1]   1.01    0.00 0.14   0.78   0.91   1.00   1.10   1.32  3306    1
    ## sigma[2]   0.87    0.00 0.12   0.67   0.79   0.86   0.94   1.15  4000    1
    ## delta     -0.65    0.00 0.25  -1.13  -0.81  -0.66  -0.49  -0.14  4000    1
    ## lp__     -91.60    0.03 1.45 -95.28 -92.35 -91.26 -90.49 -89.78  1936    1
    ## 
    ## Samples were drawn using NUTS(diag_e) at Wed Aug 29 22:27:05 2018.
    ## For each parameter, n_eff is a crude measure of effective sample size,
    ## and Rhat is the potential scale reduction factor on split chains (at 
    ## convergence, Rhat=1).

``` r
CmpMoy.F.R
```

    ## Inference for Stan model: Cmp.moy.
    ## 4 chains, each with iter=2000; warmup=1000; thin=1; 
    ## post-warmup draws per chain=1000, total post-warmup draws=4000.
    ## 
    ##             mean se_mean   sd    2.5%     25%     50%     75%   97.5%
    ## mu[1]       0.47    0.01 0.50   -0.49    0.13    0.47    0.82    1.45
    ## mu[2]       0.68    0.00 0.20    0.29    0.55    0.68    0.81    1.05
    ## sigma[1]    2.75    0.01 0.37    2.15    2.49    2.72    2.97    3.60
    ## sigma[2]    1.06    0.00 0.14    0.83    0.96    1.05    1.15    1.39
    ## delta      -0.20    0.01 0.54   -1.25   -0.58   -0.20    0.16    0.84
    ## lp__     -127.65    0.03 1.44 -131.43 -128.29 -127.31 -126.63 -125.86
    ##          n_eff Rhat
    ## mu[1]     4000    1
    ## mu[2]     4000    1
    ## sigma[1]  4000    1
    ## sigma[2]  4000    1
    ## delta     4000    1
    ## lp__      1889    1
    ## 
    ## Samples were drawn using NUTS(diag_e) at Wed Aug 29 22:27:09 2018.
    ## For each parameter, n_eff is a crude measure of effective sample size,
    ## and Rhat is the potential scale reduction factor on split chains (at 
    ## convergence, Rhat=1).

Or with a simple `brm` call :

``` r
CmpMoy.B.I <- brm(Val~Grp, data=Sim[["Ideal"]],
                  control=list(max_treedepth=15), seed=1743,
                  silent=TRUE, refresh=0, open_progress=FALSE)
CmpMoy.B.R <- update(CmpMoy.B.I, newdata=Sim[["Reel"]], seed=1750,
                  silent=TRUE, refresh=0, open_progress=FALSE)
```

``` r
cat('"Normal" dataset :\n\n')
```

    ## "Normal" dataset :

``` r
CmpMoy.B.I
```

    ##  Family: gaussian 
    ##   Links: mu = identity; sigma = identity 
    ## Formula: Val ~ Grp 
    ##    Data: Sim[["Ideal"]] (Number of observations: 60) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##           Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## Intercept     0.22      0.17    -0.12     0.55       3600 1.00
    ## GrpB          0.66      0.24     0.18     1.12       3428 1.00
    ## 
    ## Family Specific Parameters: 
    ##       Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## sigma     0.94      0.09     0.78     1.13       3249 1.00
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    ## is a crude measure of effective sample size, and Rhat is the potential 
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

``` r
cat("\nDataset with simulated outliers :\n")
```

    ## 
    ## Dataset with simulated outliers :

``` r
CmpMoy.B.R
```

    ##  Family: gaussian 
    ##   Links: mu = identity; sigma = identity 
    ## Formula: Val ~ Grp 
    ##    Data: Sim[["Reel"]] (Number of observations: 60) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##           Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## Intercept     0.48      0.38    -0.27     1.25       3497 1.00
    ## GrpB          0.21      0.54    -0.85     1.25       3588 1.00
    ## 
    ## Family Specific Parameters: 
    ##       Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## sigma     2.08      0.20     1.72     2.51       3745 1.00
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    ## is a crude measure of effective sample size, and Rhat is the potential 
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

The idea is to fit a model where `Val` is supposed to be a sample of
`student_t`-distributed populations, whose parameters are to be
estimated from the sample. This is easily done with `Stan` (see the
enclosed `CmpMoyT.stan` file) :

``` r
CmpMoyT.M <- stan_model(file="CmpMoyT.stan", model_name="Cmp.moyT")
CmpMoyT.F.I <- sampling(CmpMoyT.M,
                       data=with(Sim[["Ideal"]],
                                 list(nObs=length(Val),
                                      Grp=as.integer(Grp),
                                      Val=Val)),
                       open_progress=FALSE, show_messages=FALSE, seed=1685)
CmpMoyT.F.R <- sampling(CmpMoyT.M,
                       data=with(Sim[["Reel"]],
                                 list(nObs=length(Val),
                                      Grp=as.integer(Grp),
                                      Val=Val)),
                       open_progress=FALSE, show_messages=FALSE, seed=1715)
```

``` r
CmpMoyT.F.I
```

    ## Inference for Stan model: Cmp.moy.
    ## 4 chains, each with iter=2000; warmup=1000; thin=1; 
    ## post-warmup draws per chain=1000, total post-warmup draws=4000.
    ## 
    ##            mean se_mean      sd    2.5%    25%    50%    75%   97.5% n_eff
    ## mu[1]      0.22    0.00    0.19   -0.14   0.09   0.22   0.34    0.60  4000
    ## mu[2]      0.84    0.00    0.17    0.50   0.72   0.84   0.96    1.17  4000
    ## sigma[1]   0.96    0.00    0.15    0.68   0.86   0.95   1.06    1.30  4000
    ## sigma[2]   0.82    0.00    0.14    0.58   0.73   0.82   0.91    1.11  4000
    ## num1[1]  235.35   37.00 1642.99    1.31   7.80  23.60  83.11 1682.75  1972
    ## num1[2]  345.26  100.88 4961.40    1.14   6.91  19.79  74.57 1562.83  2419
    ## nu[1]    236.35   37.00 1642.99    2.31   8.80  24.60  84.11 1683.75  1972
    ## nu[2]    346.26  100.88 4961.40    2.14   7.91  20.79  75.57 1563.83  2419
    ## delta     -0.62    0.00    0.25   -1.13  -0.78  -0.62  -0.46   -0.11  4000
    ## lp__     -98.28    0.05    1.93 -102.99 -99.33 -97.95 -96.85  -95.69  1523
    ##          Rhat
    ## mu[1]       1
    ## mu[2]       1
    ## sigma[1]    1
    ## sigma[2]    1
    ## num1[1]     1
    ## num1[2]     1
    ## nu[1]       1
    ## nu[2]       1
    ## delta       1
    ## lp__        1
    ## 
    ## Samples were drawn using NUTS(diag_e) at Wed Aug 29 22:28:02 2018.
    ## For each parameter, n_eff is a crude measure of effective sample size,
    ## and Rhat is the potential scale reduction factor on split chains (at 
    ## convergence, Rhat=1).

``` r
CmpMoyT.F.R
```

    ## Inference for Stan model: Cmp.moy.
    ## 4 chains, each with iter=2000; warmup=1000; thin=1; 
    ## post-warmup draws per chain=1000, total post-warmup draws=4000.
    ## 
    ##             mean se_mean     sd    2.5%     25%     50%     75%   97.5%
    ## mu[1]       0.41    0.00   0.21    0.00    0.27    0.41    0.54    0.82
    ## mu[2]       0.69    0.00   0.18    0.34    0.57    0.69    0.82    1.05
    ## sigma[1]    0.82    0.00   0.22    0.48    0.67    0.80    0.94    1.33
    ## sigma[2]    0.89    0.00   0.18    0.54    0.76    0.89    1.01    1.27
    ## num1[1]     0.40    0.01   0.59    0.00    0.06    0.23    0.56    1.64
    ## num1[2]    75.69   12.08 677.27    0.32    2.26    5.55   17.80  521.17
    ## nu[1]       1.40    0.01   0.59    1.00    1.06    1.23    1.56    2.64
    ## nu[2]      76.69   12.08 677.27    1.32    3.26    6.55   18.80  522.17
    ## delta      -0.28    0.01   0.28   -0.83   -0.47   -0.29   -0.10    0.27
    ## lp__     -119.57    0.05   1.88 -123.97 -120.54 -119.25 -118.22 -116.97
    ##          n_eff Rhat
    ## mu[1]     2680    1
    ## mu[2]     2986    1
    ## sigma[1]  2222    1
    ## sigma[2]  2427    1
    ## num1[1]   2256    1
    ## num1[2]   3141    1
    ## nu[1]     2256    1
    ## nu[2]     3141    1
    ## delta     2830    1
    ## lp__      1413    1
    ## 
    ## Samples were drawn using NUTS(diag_e) at Wed Aug 29 22:28:07 2018.
    ## For each parameter, n_eff is a crude measure of effective sample size,
    ## and Rhat is the potential scale reduction factor on split chains (at 
    ## convergence, Rhat=1).

The results look sensible ; the disparity in degrees of freedom in the
“Reel” dataset can be explained by the larger importance of the
simulated outliers in the first group of this dataset.

However, this seems to be difficult to reproduce with `brm`. One can
easily get an estimate of the means, postulating identical variances and
degree of freedom :

``` r
CmpMoy.T1.I <- brm(bf(Val~0+Grp, family=student), data=Sim[["Ideal"]],
                  control=list(max_treedepth=15), seed=1743,
                  silent=TRUE, refresh=0, open_progress=FALSE)
CmpMoy.T1.R <- update(CmpMoy.T1.I, newdata=Sim[["Reel"]],
                  control=list(max_treedepth=15), seed=1750,
                  silent=TRUE, refresh=0, open_progress=FALSE)
```

``` r
cat('"Normal" dataset : \n\n')
```

    ## "Normal" dataset :

``` r
CmpMoy.T1.I
```

    ##  Family: student 
    ##   Links: mu = identity; sigma = identity; nu = identity 
    ## Formula: Val ~ 0 + Grp 
    ##    Data: Sim[["Ideal"]] (Number of observations: 60) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## GrpA     0.22      0.17    -0.12     0.57       4000 1.00
    ## GrpB     0.86      0.17     0.53     1.21       4000 1.00
    ## 
    ## Family Specific Parameters: 
    ##       Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## sigma     0.91      0.10     0.74     1.12       3742 1.00
    ## nu       25.18     14.52     6.56    61.56       4000 1.00
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    ## is a crude measure of effective sample size, and Rhat is the potential 
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

``` r
cat("\nDataset with simulated outliers :\n\n")
```

    ## 
    ## Dataset with simulated outliers :

``` r
CmpMoy.T1.R
```

    ##  Family: student 
    ##   Links: mu = identity; sigma = identity; nu = identity 
    ## Formula: Val ~ 0 + Grp 
    ##    Data: Sim[["Reel"]] (Number of observations: 60) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## GrpA     0.41      0.22    -0.02     0.83       3835 1.00
    ## GrpB     0.69      0.20     0.31     1.08       3326 1.00
    ## 
    ## Family Specific Parameters: 
    ##       Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## sigma     0.89      0.15     0.63     1.23       3005 1.00
    ## nu        2.69      0.98     1.37     5.07       3204 1.00
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    ## is a crude measure of effective sample size, and Rhat is the potential 
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

One can also model heteroskedasticity :

``` r
CmpMoy.T2.I <- brm(bf(Val~0+Grp, family=student, sigma~0+Grp),
                   data=Sim[["Ideal"]],
                  control=list(max_treedepth=15), seed=1743,
                  silent=TRUE, refresh=0, open_progress=FALSE)
CmpMoy.T2.R <- update(CmpMoy.T2.I, newdata=Sim[["Reel"]],
                  control=list(max_treedepth=15), seed=1750,
                  silent=TRUE, refresh=0, open_progress=FALSE)
```

``` r
cat('"Normal" dataset : \n\n')
```

    ## "Normal" dataset :

``` r
CmpMoy.T2.I
```

    ##  Family: student 
    ##   Links: mu = identity; sigma = log; nu = identity 
    ## Formula: Val ~ 0 + Grp 
    ##          sigma ~ 0 + Grp
    ##    Data: Sim[["Ideal"]] (Number of observations: 60) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##            Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## GrpA           0.22      0.20    -0.16     0.61       4000 1.00
    ## GrpB           0.86      0.16     0.55     1.17       4000 1.00
    ## sigma_GrpA    -0.03      0.14    -0.29     0.27       4000 1.00
    ## sigma_GrpB    -0.19      0.14    -0.46     0.11       4000 1.00
    ## 
    ## Family Specific Parameters: 
    ##    Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## nu    25.30     14.14     6.59    60.40       4000 1.00
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    ## is a crude measure of effective sample size, and Rhat is the potential 
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

``` r
cat("\nDataset with simulated outliers :\n\n")
```

    ## 
    ## Dataset with simulated outliers :

``` r
CmpMoy.T2.R
```

    ##  Family: student 
    ##   Links: mu = identity; sigma = log; nu = identity 
    ## Formula: Val ~ 0 + Grp 
    ##          sigma ~ 0 + Grp
    ##    Data: Sim[["Reel"]] (Number of observations: 60) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##            Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## GrpA           0.41      0.24    -0.08     0.90       4000 1.00
    ## GrpB           0.68      0.18     0.34     1.04       4000 1.00
    ## sigma_GrpA     0.05      0.26    -0.47     0.57       2634 1.00
    ## sigma_GrpB    -0.29      0.20    -0.68     0.11       4000 1.00
    ## 
    ## Family Specific Parameters: 
    ##    Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    ## nu     2.96      1.52     1.34     6.48       2398 1.00
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    ## is a crude measure of effective sample size, and Rhat is the potential 
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

But I have been unable to model group-specific degrees of freedom.
Notwithstanding very small values of `adapt_delta` and very large valus
of `max_treedepth`, the following (here left unevaluated) is *extremely*
slow and leads to nonsensical extremely large values of `Rhat`.

``` r
CmpMoy.T3.I <- brm(bf(Val~0+Grp, family=student, sigma~0+Grp, nu~0+Grp),
                   data=Sim[["Ideal"]],
                  control=list(max_treedepth=15), seed=1743,
                  silent=TRUE, refresh=0, open_progress=FALSE)
CmpMoy.T3.R <- update(CmpMoy.T3.I, newdata=Sim[["Reel"]],
                  control=list(max_treedepth=15), seed=1750,
                  silent=TRUE, refresh=0, open_progress=FALSE)
```

Since such a model *can* be built and fit in “pure `Stan`”, with
seemingly sensible results, I *suppose* that there may be a bug in the
translation done by `brm`.

**Comment by paul-buerkner** [comment] 2018-08-29 22:49
That's not a bug. It's just the DFs tend to be not identified by data alone and so you need to specify proper priors on the coeffiecients related to the DFs.

**Comment by EmmanuelCharpentier** [comment] 2018-08-31 17:30
[DataAndModel.zip](https://github.com/paul-buerkner/brms/files/2340992/DataAndModel.zip)

I still think that there might be a bug in the prior specification of
`brm`

`Stan` and `brms` use the so called “shape-rate” parameterization of the `gamma` distribution. With a little fiddling with[Sage](http://www.sagemath.org/), one gets the expression of the method-of-moments estimators for shape alpha and rate beta :

alpha = m²/v, beta=m/v 

This shows us that, in order to express (quasi-)ignorance *a priori* on nu, we may choose a “large” alpha and a “small” beta. One can graphically confirm that alpha=1+epsilon, beta=epsilon give us a distribution with a slight preference for “small” values, and essentially flat close to 0, which is what we seek for nu-1 (see PDF picture) :

[plot-0.pdf](https://github.com/paul-buerkner/brms/files/2340982/plot-0.pdf)

We use the same data as before (see in enclosed archive) :

``` r
## Same data as before (and same confusion....)
source("Sim.RData")
```

The Stan model reflects what we have learned *supra* (see enclosed files) : 
The Stan model fits easily :

``` r
CmpMoyTbis.M <- stan_model(file="CmpMoyTbis.stan", model_name="Cmp.moyTbis")
CmpMoyTbis.F.I <- sampling(CmpMoyTbis.M,
                       data=with(Sim[["Ideal"]],
                                 list(nObs=length(Val),
                                      Grp=as.integer(Grp),
                                      Val=Val)),
                       open_progress=FALSE, show_messages=FALSE, seed=1685)
CmpMoyTbis.F.R <- sampling(CmpMoyTbis.M,
                       data=with(Sim[["Reel"]],
                                 list(nObs=length(Val),
                                      Grp=as.integer(Grp),
                                      Val=Val)),
                       open_progress=FALSE, show_messages=FALSE, seed=1715)
```

Results are sensible, both for the “Ideal” dataset :

|            |    mean |     sd |    2.5% |     50% |   97.5% |  n\_eff | Rhat |
| ---------- | ------: | -----: | ------: | ------: | ------: | ------: | ---: |
| mu\[1\]    |    0.22 |   0.18 |  \-0.14 |    0.22 |    0.58 | 4000.00 |    1 |
| mu\[2\]    |    0.86 |   0.16 |    0.53 |    0.86 |    1.18 | 4000.00 |    1 |
| sigma\[1\] |    1.00 |   0.14 |    0.76 |    0.98 |    1.31 | 4000.00 |    1 |
| sigma\[2\] |    0.86 |   0.12 |    0.66 |    0.85 |    1.13 | 4000.00 |    1 |
| num1\[1\]  |  110.80 | 102.07 |    7.73 |   80.81 |  382.52 | 4000.00 |    1 |
| num1\[2\]  |  107.58 | 100.35 |    7.16 |   76.23 |  379.23 | 4000.00 |    1 |
| nu\[1\]    |  111.80 | 102.07 |    8.73 |   81.81 |  383.52 | 4000.00 |    1 |
| nu\[2\]    |  108.58 | 100.35 |    8.16 |   77.23 |  380.23 | 4000.00 |    1 |
| delta      |  \-0.64 |   0.24 |  \-1.11 |  \-0.64 |  \-0.17 | 4000.00 |    1 |
| lp\_\_     | \-94.65 |   1.78 | \-99.12 | \-94.32 | \-92.24 | 1881.53 |    1 |

and the “Reel” dataset :

|            |     mean |    sd |     2.5% |      50% |    97.5% |  n\_eff | Rhat |
| ---------- | -------: | ----: | -------: | -------: | -------: | ------: | ---: |
| mu\[1\]    |     0.40 |  0.22 |   \-0.04 |     0.41 |     0.85 | 4000.00 |    1 |
| mu\[2\]    |     0.69 |  0.19 |     0.30 |     0.69 |     1.07 | 4000.00 |    1 |
| sigma\[1\] |     0.94 |  0.26 |     0.54 |     0.91 |     1.54 | 2502.60 |    1 |
| sigma\[2\] |     1.02 |  0.15 |     0.74 |     1.01 |     1.34 | 2799.19 |    1 |
| num1\[1\]  |     1.19 |  5.77 |     0.05 |     0.80 |     3.30 | 2699.13 |    1 |
| num1\[2\]  |    90.71 | 94.71 |     3.48 |    59.88 |   344.25 | 4000.00 |    1 |
| nu\[1\]    |     2.19 |  5.77 |     1.05 |     1.80 |     4.30 | 2699.13 |    1 |
| nu\[2\]    |    91.71 | 94.71 |     4.48 |    60.88 |   345.25 | 4000.00 |    1 |
| delta      |   \-0.29 |  0.30 |   \-0.88 |   \-0.29 |     0.29 | 4000.00 |    1 |
| lp\_\_     | \-121.71 |  1.89 | \-126.30 | \-121.34 | \-119.19 | 1319.08 |    1 |

Again, the discrepancy in degrees of freedom in this second set makes
sense : the first sample has more and more important (simulated)
outliers than the second, which is “almost” normal.

However; I have been unable to get the very similar `brms` model to
converge (left unevaluated…) :

``` r
CmpBrm.I <- brm(bf(Val~0+Grp, family=student, sigma~0+Grp, nu~0+Grp),
                data=Sim[["Ideal"]],
                prior=c(
                    prior(student_t(3,0,10), class="b"),
                    prior(lognormal(0,3), class="b", dpar="sigma", lb=0),
                    prior(gamma(1.01,0.01), class="b", dpar="nu", lb=1)),
                control=list(max_treedepth=20,adapt_delta=0.99999999))
```
Depending of the run (`seed` is voluntarily not used), one or two chains might converge more or less quickly (with usually a “slow” warmup and a “fast” sampling).

The (proper, but vague) prior given to nu-1 in the Stan mode seems enough to get sensible results. the fact that the credible intervals of unperturbed or little-perturbed datasets are quite large is here *reasonable* : these datasets are quasi-normal (assimilable to a *t* distributin with *infinite* degrees of freedom). On the other hand, the short (and low) credible interval given to the degrees of freedom of the perturbed dataset  is also reasonable, signing the presence of large outliers.

The only reason I can see is that we are specifying a prior directly for nu, whereas the Stan model has a specification for nu-1, but the `lb=1` argument of the `prior` call for nu should take care of that.

So I still *think* that semething is ajar either in the translation of the `prior` call for \(\nu\) or in the generated code…

**Comment by paul-buerkner** [comment] 2018-09-01 02:37
By default nu is modeled on the log-scale. to turn that off go for family =
student(link_nu = "identity")

EmmanuelCharpentier <notifications@github.com> schrieb am Fr., 31. Aug.
2018, 20:30:

**Comment by paul-buerkner** [comment] 2018-09-04 12:03
Just a quick follow up to find out whether my recommendation did the trick?

I still don't think that there is a bug, but I am happy to be convinced otherwise.

**Comment by EmmanuelCharpentier** [comment] 2018-09-04 12:06
Sorry, Paul : I'm a bit overwhenmed ATM. I *think* that I checked it "informally" and wanted to formalize it, but I'm afraid to have had a few NMIs since. Is tonigt soon enough ?

(BTW : ditto for the paper, which i did **not** forgot !).

**Comment by paul-buerkner** [comment] 2018-09-04 12:08
All good! Tonight is more than enough :-)

**Comment by EmmanuelCharpentier** [comment] 2018-09-06 07:15
Okay. I checked that when modeling sigma and/or nu, priors are expressed for log(sigma) (resp. log(nu-1)). 

I think I've been fooled by the fact that, wnen **not** modeling sigma (resp mu), `brm` outputs *discretely* change the default links for them to "identity" and give results on the natural scale of the parameter. This confusion is compounded by the fact that, when modeling nu and sigma, the parameters  are called `sigma-GrpA` and `sigma_GrpB` (resp. `nu_GrpA` and `nu_GrpB`), *but the values are on the **link** scale*.

It would have been more straightforward ("honest") to name them, for example, `logsigma_GrpA` or `logm1_GrpB`, and possibly to add generated quantities giving the distributions on the natural scale, but it's probably way too late to introduce such a change...

Alternative solution, give big fat examples of using an explicit specification of the link(s) on the natural scale. Easy for sigma, no-so-easy for nu (a prior of the form `gamma(1+epsilon, 1/epsilon)` is a reasonable prior for unknown degrees of freedom, but justifying it requires a bit of analytic work...).

I think we can close the issue, unless you have other suggestions...

**Comment by paul-buerkner** [comment] 2018-09-06 07:59
That confusion is understandable. You are not to first to stumble upon this. I guess I need to better document this behavior... Closing this issue.

**Closed by paul-buerkner** 2018-09-06 07:59 UTC
