### ISSUE TITLE
monotonic effect sampling error

### ISSUE THREAD

**Issue by torkar** [paul-buerkner/brms#789] opened 2019-11-14 15:41 UTC
See https://discourse.mc-stan.org/t/monotonic-effect-sampling-error/11911/2 for background.

In short, using this [data](https://www.dropbox.com/s/q880emh84j6mae0/data.csv?dl=0) and converting the variable `f4f_rls` and then running a model ends with an error:
```
df$f4f_rls_oc <- factor(adf$f4f_rls, 
                          levels=c("1", "2", "3", "4", "5", "6", "7", "8"), 
                          ordered=TRUE)
brm(outcome ~ mo(f4f_rls_oc), family = bernoulli, data = df)
```

```
Compiling the C++ model
Start sampling
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: model11ee323291e98_795c055e16168b7b61dd7fef18a57b7a_namespace::model11ee323291e98_795c055e16168b7b61dd7fef18a57b7a: Jmo[i_0__] is 1, but must be greater than or equal to 2  (in 'model11ee323291e98_795c055e16168b7b61dd7fef18a57b7a' at line 24)
failed to create the sampler; sampling not done
```

I use the latest GitHub version.

**Comment by paul-buerkner** [comment] 2019-11-14 19:26
Thank you! I will take a look asap!

Richard Torkar <notifications@github.com> schrieb am Do., 14. Nov. 2019,
17:41:

**Comment by paul-buerkner** [comment] 2019-11-15 08:05
Hmm, the problem is that the variable you use is constant. A special case I had not though of. Not sure if anything reasonable would come out of such a case.

**Comment by paul-buerkner** [comment] 2019-11-15 08:10
It should now be fixed on github. Thanks for reporting this issue!

**Closed by paul-buerkner** 2019-11-15 08:10 UTC
Labels: bug
