### ISSUE TITLE
Fix parameters via the 'prior' argument

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#783] opened 2019-11-06 07:54 UTC
The ability to fix parameters has been requested in several places, for instance, in https://discourse.mc-stan.org/t/fixing-gp-parameters-in-brms/10928/4. 

Fixing parameters to certain values is a special case of prior specification with a point mass (delta distribution basically) and so the prior argument seems a natural place to put this feature in.

@bbbales2 proposed to use the `fixed()` prior name as in

```R
set_prior("fixed(1.5)", class = "sd")
```

which seems reasonable to me. As this feature touches a lot of other features, the internal interface created for this purpose needs to be carefully designed and take special cases into account where we want to fix only certian values of a parameter vector, for example.

**Comment by lindeloev** [comment] 2019-11-06 10:08
I am putting the final touches on an R package which does this. Users input a numerical value rather than character, i.e., equating to `set_prior(1.5, class = "sd")`. Another "fixed" functionality is equating parameters with something that would equate to `set_prior("b0", coef = "b2")`, i.e., just estimate one less parameter. I'm unsure whether this is meaningful for `brms`. 

I've documentet "my" implementation here: https://lindeloev.github.io/mcp/articles/priors.html. `mcp` is *heavily* inspired by `brms` in many ways, although of course way more limited in scope. I'm hoping that using the two packages will feel similar. So if you have any thoughts, I'd be thrilled to hear them.

**Comment by paul-buerkner** [comment] 2019-11-06 10:49
Thanks! These are definitely things to keep in mind when deciding the fixation interface. Equality constraints are something I would like to implement as well and it probably makes sense to do it all on one shot. Now I just need to better understand the requirement for an interface for equating parameters, which I am not sure is easily possible given the flexibility of brms models.

**Comment by bbbales2** [comment] 2019-11-06 13:26
> Users input a numerical value rather than character, i.e., equating to set_prior(1.5, class = "sd"). Another "fixed" functionality

Yeah good point. Using the word "fixed" again in a context where there's already fixed effects might not be a great idea.

Thanks for looking at this!

**Comment by paul-buerkner** [comment] 2019-11-06 14:10
Putting numeric values directly into `set_prior` is not a good idea as we loose a lot of clarity in the internal interfaces. It is better to have a function (perhaps called `fixed` or something else) to handle of the checking and providing a consistent output. I am using this approach in other priors such as `set_prior("horseshoe(...)")` where `horseshoe` is an actual function being called internally. I am not worried about the name clash with fixed effects since we moved away from these terms anyway and currently I don't see a more intuitive name. We could call with `delta` or something to refer to the dirac delta distribution but this is way less clear for most users.

**Comment by bbbales2** [comment] 2019-11-06 14:48
How about calling them something like ```constant(1.0)```?

**Comment by paul-buerkner** [comment] 2019-11-06 17:18
I like the name 'constant()' let's go for that one!

Ben Bales <notifications@github.com> schrieb am Mi., 6. Nov. 2019, 16:48:

**Comment by jgabry** [comment] 2019-11-08 03:46
I think it’s a good idea to offer this feature, but I also think it would be good to make clear in the doc that it’s not full Bayes and really shouldn’t be encouraged (at least for final inferences) unless the problem is computationally impractical  otherwise.

**Comment by stephensrmmartin** [comment] 2019-11-13 20:58
> I think it’s a good idea to offer this feature, but I also think it would be good to make clear in the doc that it’s not full Bayes and really shouldn’t be encouraged (at least for final inferences) unless the problem is computationally impractical otherwise (or is a special case like a meta analysis where full data isn’t available like sd(y) in eight schools).

There are some cases where one just wants a model with a particular parameter set to a constant. As in - It isn't something to be inferred anyway, you just want to include a constant for some utility purpose. E.g., I had a situation (https://discourse.mc-stan.org/t/mi-with-non-linear-model/11227) where I really needed to define a variable (t2) as `0 + 1 * mi(time2)`. I had to manually change the model to fix the 'coefficient' to 1, but if brms permitted fixing params, I could have just specified that beta coefficient is constant at 1 - As in, it's not something to be estimated, because I am defining, not modeling, a parameter.

**Comment by jgabry** [comment] 2019-11-14 03:13
@stephensrmmarti Yeah that’s a good use case for this I wasn’t thinking about. Thanks for sharing!

**Comment by bbbales2** [comment] 2019-11-20 22:04
@paul-buerkner would this be impossible for me to do? I grep'd for horseshoe and it looks like it's involved in R/priors.R, R/stan-prior.R, and R/stan-predictor.R.

R/priors.R is the interface stuff and I'd assume I'd copy the horseshoe stuff there. I think this needs to be a special prior cause it doesn't directly translate to Stan code.

R/stan-prior.R and R/stan-predictor.R do code generation. It looks like the group level variances are here (which is what we wanna put the constant priors on): https://github.com/paul-buerkner/brms/blob/ff018cbef41572db88216f2874562e32ebc50682/R/stan-predictor.R#L613

The special priors are generated a little separately. Is there anything else I'd need to know? Or is this a bad idea?

**Comment by paul-buerkner** [comment] 2019-11-20 22:47
In principal you have the right directions. However, this feature is not only about random effects SDs but about all parameters and to do it in a nice and extensible manner it requires substantial refactor that I am not sure I want to bother someone with as it touches so many places of the stan code generation and possibly also post-processing, which we didn't think about yet.

**Comment by paul-buerkner** [comment] 2020-01-21 14:47
Just a heads up that I am going to work on this feature starting tomorrow. I will start by implementing it for whole parameter variables, that is, do not support setting `constant()` priors on specific coefficients. The reason is that fixing specific coefficients but not others would require mixing data and parameters within one object and I currently don't have the time to handle all the necessary indexing. Would the reduced version of this feature also be sufficient for you, @bbbales2, for the time being?

**Comment by stephensrmmartin** [comment] 2020-01-21 19:32
@paul-buerkner So this would work for, say, 'non-linear' models where you have y ~ b0 + b1*x1 + b2*x2; where nl = TRUE, and you set b1 to be constant? Or is that not the case?

**Comment by paul-buerkner** [comment] 2020-01-21 21:31
Not quite. It allows to set parameters to constants which appear in the prior argument. So we can fix `b1`, say, by fixing its implied intercept.

**Comment by paul-buerkner** [comment] 2020-01-23 12:00
This feature is now avaible on github. Here is an example:

```R
bprior <- prior(constant(1), class = "b") +
    prior(constant(2), class = "b", coef = "zBase") +
    prior(constant(0.5), class = "sd")
  
fit <- brm(count ~ zAge + zBase + (1 | patient),
             data = epilepsy, prior = bprior)

summary(fit)
conditional_effects(fit)
```

The only thing that does not work yet is combining estimates and fixed parameter values within the same vector as it requires a little bit more fiddeling with indexing for which I didn't have time yet.

@bbbales2 (and others as well of course), would you mind trying out this feature and see if it fulfills your needs?

**Comment by paul-buerkner** [comment] 2020-01-23 22:32
With the changes I just pushed, it is now possible to combine estimated and fixed parameter values within the same vector. Here is an example:

```R
bprior <- prior(normal(0, 1), class = "b") +
    prior(constant(2), class = "b", coef = "zBase") +
    prior(constant(0.5), class = "sd")
  
fit <- brm(count ~ zAge + zBase + (1 | patient),
             data = epilepsy, prior = bprior)

summary(fit)
conditional_effects(fit)
```

I would consider this feature as fully implemented but I leave this issue open for a day or two until someone else has tried it out as well.

**Comment by bbbales2** [comment] 2020-01-23 22:33
Oh wow thanks! I'll give this a try!

**Comment by bbbales2** [comment] 2020-01-23 23:04
I think I found a couple errors, but maybe I'm using the priors wrong.

Generate some data:
```
library(brms)

N = 10
x = seq(0.0, pi, length = N)
y = rnorm(N, sin(x), 0.1)

data = tibble(N = 10,
              x = x,
              y = y)
```

This works and does what I'd expect:
```
make_stancode(y ~ x,
              data,
              prior = set_prior("constant(1)", class = "b"))
```

But this gives an error:
```
make_stancode(y ~ gp(x),
              data,
              prior = set_prior("constant(1)", class = "b", coef = "x"))
```

(it does the same with the ```prior(constant(1), class = "b", coef = "x")``` syntax)

This moves the gp lengthscale parameter from the parameters block into transformed parameters, but doesn't assign it:
```
make_stancode(y ~ gp(x),
              data,
              prior = set_prior("constant(1)", class = "lscale"))
```

This looks like it's working properly:
```
make_stancode(y ~ gp(x),
              data,
              prior = set_prior("constant(1)", class = "lscale", coef = "gpx"))
```

**Comment by paul-buerkner** [comment] 2020-01-24 06:40
Thanks for looking into this! 

The model `y ~ gp(x)` has no `b` coefficients, since the intercept has its own prior class `Intercept`. This is visible when you call `get_prior` with your formula and data.

The fact that 

```R
make_stancode(y ~ gp(x),
              data,
              prior = set_prior("constant(1)", class = "lscale"))
```

doesn't assign it is expected but unfortunate behavior, since every `lscale` paramter has its own default prior, which is prioritized over the global prior. I need to make this result in an error I guess,
also to prevent the moving of the parameter to the transformed parameters block, which is definitely a bug here.

**Comment by paul-buerkner** [comment] 2020-01-24 09:39
I think I fixed it.

```R
make_stancode(y ~ gp(x),
              data,
              prior = set_prior("constant(1)", class = "lscale"))
```

will now correctly define `lscale` in the parameters block and through a warning about ignoring the global prior.

**Comment by paul-buerkner** [comment] 2020-01-24 09:41
@bbbales2 Can you double check on this again?

**Comment by bbbales2** [comment] 2020-01-24 15:33
Oh yeah it's working now!

And I see my typo on the other one, 

```
make_stancode(y ~ x,
              data,
              prior = set_prior("constant(1)", class = "b", coef = "x"))
```

Works fine (I'd been trying ```gp(x)```) too. Thanks!

**Closed** 2020-02-01 16:46 UTC
Labels: feature

**Comment by tfjaeger** [comment] 2020-04-29 21:07
Paul, this is super helpful! Further up in this thread you also mention that you wanted to allow equality constraints. Are you still working on that? And would this allow constraints that set one parameter to a simple *function* of another parameter (like b_x1 = b_x2 * 2)?

It occurred to me that this would also address (some) questions like the one I asked about hypothesis tests about relations between parameters of the model (https://discourse.mc-stan.org/t/comparing-two-point-hypotheses-over-brm-model/13756/2).

**Comment by paul-buerkner** [comment] 2020-04-30 07:28
Would you mind opening a new issue for it so that I don't forget about this idea?

**Comment by rosskempner** [comment] 2021-02-01 01:47
@paul-buerkner If " it is now possible to combine estimated and fixed parameter values within the same vector", then should this be updated in the documentation?

The documentation still says it is not possible:

“A limitation
of the current implementation is that the same parameter vector cannot contain estimated and fixed
values at the same time, but this will be possible in the future.”

**Comment by paul-buerkner** [comment] 2021-02-01 12:21
Thanks. Fixed the doc.

**Comment by rosskempner** [comment] 2021-02-01 12:29
Awesome, thank you!
