### ISSUE TITLE
Model comparisons with WAIC or LOO with AR1 noise not providing expected results

### ISSUE THREAD

**Issue by kgoldfeld** [paul-buerkner/brms#757] opened 2019-09-17 13:55 UTC
I am seeing something odd when l compare models based on estimations using brms. I am generating longitudinal data with AR1 correlations, and I can get back the parameters of the data generation process using brms estimation. That is good. But, when I fit a model that ignores the AR1 correlation and I compare that to the “correct” model, I think I would need to conclude that the simpler, non-AR1 model is sufficient. It doesn’t seem to matter whether I use WAIC or LOO. When I estimated mixed effects models using nlme, a comparison of AIC leads me to conclude that the AR1 model is indeed a better fit. 

```{r}
library(simstudy)

### Define data

defI <- defData(varname = "ieffect", formula = 0, variance = 9)

defc <- defCondition(condition = "period == 0", 
   formula = "20 + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 1", 
   formula = "30 + 40*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 2",
   formula = "25 + 25*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 3", 
   formula = "25 + 15*rx + ieffect", dist = "nonrandom")

## Generate data

set.seed(3821)

dd <- genData(300, defI)
dd <- trtAssign(dd, grpName = "rx") 

dp <- addPeriods(dd, nPeriods = 4) 
dp <- addCondition(defc, dp, "mu") 
dp[, sigma2 := 6^2]

dx <- addCorGen(dp, "id", nvars = 4, dist = "normal", param1 = "mu", 
   param2 = "sigma2", rho = 0.4, corstr = "ar1", cnames = "y")
dx <- genFactor(dx, "period") 
dx <- genFactor(dx, "rx")
````

"Correct" model:

```{r}
library(brms)
brmfit1 <- brm(y ~ fperiod + frx:fperiod + (1|id), data = dx,
   autocor=cor_ar(formula = ~ 1 | id, p = 1),
   cores = 4,
   prior = c(set_prior("normal(0, 5)", class = "b"),
                  set_prior("cauchy(0, 2)", class = "sd")),
   warmup = 1000, iter = 5000, chains = 4,
   control = list(max_treedepth = 10) , silent = TRUE
)
````

Fit model without AR1 correlation

```{r}
brmfit2 <- brm(y ~ fperiod + frx:fperiod + (1|id), data = dx,
   cores = 4,
   prior = c(set_prior("normal(0, 5)", class = "b"),
       set_prior("cauchy(0, 2)", class = "sd")),
   warmup = 1000, iter = 5000, chains = 4, 
   control = list(max_treedepth = 10), silent = TRUE
)
````

Compare two models

```{r}
brmfit1 <- add_criterion(brmfit1, "waic")
brmfit1 <- add_criterion(brmfit1, "loo", reloo = TRUE)

brmfit2 <- add_criterion(brmfit2, "waic")
brmfit2 <- add_criterion(brmfit2, "loo", reloo = TRUE)
````

```{r}
loo_compare(brmfit1, brmfit2, criterion = "waic")
loo_compare(brmfit1, brmfit2, criterion = "loo")
````

**Comment by paul-buerkner** [comment] 2019-09-17 14:04
Thank you so much for posting it here! I have not yet an explanation for this behavior but would think it is probably a bug in the post-processing of the model. I will try to fix this as soon as I find the time to dive into this a litte deeper.

**Comment by paul-buerkner** [comment] 2019-09-18 11:47
I agree that the behavior is weird but it seems more and more to me that it is not actually a bug. 
When running the model with pure stan and saving `mu` in the generated quantities block and then comparing it with the predictions of brms, the result it the same:

```R
brmfit1 <- brm(y ~ fperiod + frx:fperiod + (1|id), 
              data = dx, 
              autocor=cor_ar(formula = ~ period | id, p = 1),
              prior = c(set_prior("normal(0, 50)", class = "b"),
                        set_prior("cauchy(0, 10)", class = "sd")
                        ),
              seed = 1234
)

scode <- "
// generated with brms 2.10.1
functions {
}
data {
  int<lower=1> N;  // number of observations
  vector[N] Y;  // response variable
  int<lower=1> K;  // number of population-level effects
  matrix[N, K] X;  // population-level design matrix
  // data needed for ARMA correlations
  int<lower=0> Kar;  // AR order
  int<lower=0> Kma;  // MA order
  // number of lags per observation
  int<lower=0> J_lag[N];
  // data for group-level effects of ID 1
  int<lower=1> N_1;  // number of grouping levels
  int<lower=1> M_1;  // number of coefficients per level
  int<lower=1> J_1[N];  // grouping indicator per observation
  // group-level predictor values
  vector[N] Z_1_1;
  int prior_only;  // should the likelihood be ignored?
}
transformed data {
  int Kc = K - 1;
  matrix[N, Kc] Xc;  // centered version of X without an intercept
  vector[Kc] means_X;  // column means of X before centering
  int max_lag = max(Kar, Kma);
  for (i in 2:K) {
    means_X[i - 1] = mean(X[, i]);
    Xc[, i - 1] = X[, i] - means_X[i - 1];
  }
}
parameters {
  vector[Kc] b;  // population-level effects
  // temporary intercept for centered predictors
  real Intercept;
  real<lower=0> sigma;  // residual SD
  vector[Kar] ar;  // autoregressive effects
  vector<lower=0>[M_1] sd_1;  // group-level standard deviations
  // standardized group-level effects
  vector[N_1] z_1[M_1];
}
transformed parameters {
  // actual group-level effects
  vector[N_1] r_1_1 = (sd_1[1] * (z_1[1]));
}
model {
  // initialize linear predictor term
  vector[N] mu = Intercept + Xc * b;
  // objects storing residuals
  matrix[N, max_lag] Err = rep_matrix(0, N, max_lag);
  vector[N] err;
  for (n in 1:N) {
    // add more terms to the linear predictor
    mu[n] += r_1_1[J_1[n]] * Z_1_1[n];
  }
  // include ARMA terms
  for (n in 1:N) {
    err[n] = Y[n] - mu[n];
    for (i in 1:J_lag[n]) {
      Err[n + 1, i] = err[n + 1 - i];
    }
    mu[n] += head(Err[n], Kar) * ar;
  }
  // priors including all constants
  target += normal_lpdf(b | 0, 50);
  target += student_t_lpdf(Intercept | 3, 30, 15);
  target += student_t_lpdf(sigma | 3, 0, 15)
    - 1 * student_t_lccdf(0 | 3, 0, 15);
  target += cauchy_lpdf(sd_1 | 0, 10)
    - 1 * cauchy_lccdf(0 | 0, 10);
  target += normal_lpdf(z_1[1] | 0, 1);
  // likelihood including all constants
  if (!prior_only) {
    target += normal_lpdf(Y | mu, sigma);
  }
}
generated quantities {
  // actual population-level intercept
  real b_Intercept = Intercept - dot_product(means_X, b);
  // initialize linear predictor term
  vector[N] mu_gen = Intercept + Xc * b;
  // objects storing residuals
  matrix[N, max_lag] Err_gen = rep_matrix(0, N, max_lag);
  vector[N] err_gen;
  for (n in 1:N) {
    // add more terms to the linear predictor
    mu_gen[n] += r_1_1[J_1[n]] * Z_1_1[n];
  }
  // include ARMA terms
  for (n in 1:N) {
    err_gen[n] = Y[n] - mu_gen[n];
    for (i in 1:J_lag[n]) {
      Err_gen[n + 1, i] = err_gen[n + 1 - i];
    }
    mu_gen[n] += head(Err_gen[n], Kar) * ar;
  }
}
"

library(rstan)
stanfit1 <- stan(model_code = scode, data = standata(brmfit1), seed = 1234)
mu_stan <- as.matrix(stanfit1, pars = "mu_gen")

mu_brms <- fitted(brmfit1, summary = FALSE)

all.equal(mu_stan, mu_brms, check.attributes = FALSE)
> TRUE
```

So whatever mistake I may have made, I have made it twice in Stan and in the R post-processing. Since the posterior estimates of the parameters look reasonable,  the Stan code (and thus the R post-processing code) is likely correct. 

If you want to use the AR formulation that nlme uses, which is likely also what makes up the data generating process in the simstudy package, go for `cor_ar(formula = ~ period | id, p = 1, cov = TRUE)`. When using this AR formulation, I get LOO and WAIC results in the expected direction. The `cov` formulation is less efficient usually but for very short time-series (as in your case) it does not really matter I would say.

**Comment by kgoldfeld** [comment] 2019-09-18 13:12
Thanks for working through this.

**Comment by paul-buerkner** [comment] 2019-09-18 13:34
Some more insights. 

This strange behavior only occurs when also modelling the varying intercepts. Without them, the AR model (in whatever formulation) is clearly favorable. The varying intercepts appear to make up for some of the variation caused by the AR term and so may partly adjust for it even in its absense. 

Moreover, the AR model starts being favorable when using more simulating more observations per person for instance via the following amended data generating mechanism:

```R
library(simstudy)

### Define data

defI <- defData(varname = "ieffect", formula = 0, variance = 9)

defc <- defCondition(condition = "period == 0", 
                     formula = "20 + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 1",
                     formula = "30 + 40*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 2",
                     formula = "25 + 25*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 3",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 4",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 5",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 6",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 7",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 8",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 9",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")
defc <- defCondition(defc, condition = "period == 10",
                     formula = "25 + 15*rx + ieffect", dist = "nonrandom")

## Generate data

set.seed(3821)

dd <- genData(300, defI)

dd <- trtAssign(dd, grpName = "rx")
dp <- addPeriods(dd, nPeriods = 11)
dp <- addCondition(defc, dp, "mu")
dp[, sigma2 := 6^2]

dx <- addCorGen(dp, "id", nvars = 11, dist = "normal",
                param1 = "mu", param2 = "sigma2", 
                rho = 0.4, corstr = "ar1", cnames = "y")

dx <- genFactor(dx, "period")
dx <- genFactor(dx, "rx")
```


Both of these points to a statistical reason for this strange behavior and not actually a bug in the code. AR models are weird and I continue to be surprised by their properties...

**Comment by paul-buerkner** [comment] 2019-09-22 09:18
Closing this issue as I cannot possibly find any bug in the code and results match our intuition for more than a few time points.  Someone may need to do some proper research on this perhaps.

In any case, using the `cov` argument produces the same behavior as nlme and is feasible computationally for a few time points, so I guess we have a solution for your immediate problem at hand.

**Closed by paul-buerkner** 2019-09-22 09:18 UTC
Labels: bug
