### ISSUE TITLE
Windows - R crashes with repeated runs of the same model

### ISSUE THREAD

**Issue by andrjohns** [paul-buerkner/brms#994] opened 2020-09-02 00:49 UTC
A user [posted on the forums](https://discourse.mc-stan.org/t/rstan-on-windows/16673/173) about their R package (a wrapper around ```brms```) crashing R on Windows when they tried to test multiple models in a single session.

I was able to replicate the crashes locally with their package and also with 'pure' ```brms```.

I've attached a list of the ```brms``` options here: [test_brm.RData](https://www.dropbox.com/s/y3ojlqnqod288vt/test_brm.RData?dl=1)

And you can (hopefully) replicate the crashes with the following code:
```
options(mc.cores=4)
library(brms)
load("test_brm.RData")

out = do.call(brm,test_brm)
out = do.call(brm,test_brm)
out = do.call(brm,test_brm)

#Crashes on this call:
out = do.call(brm,test_brm)
```

**Comment by andrjohns** [comment] 2020-09-02 00:55
@dbarneche Forgot to update you in the discourse thread before I closed it (sorry!). You can follow the issue here

**Comment by BrianBucher2** [comment] 2020-09-02 04:56
I've had this happen (crash with C stack trace details as posted on Stan discourse forums) several times using the ulam() function from the rethinking package. For curiosity's sake, I played around a bit with the brms example and found that this crashes:

```
options(mc.cores=4)
library(brms)
load("test_brm.RData")
out = do.call(brm,test_brm)
out = do.call(brm,test_brm)
out = do.call(brm,test_brm) #crashes here
```
It crashes on the third call both a) Using R within Rstudio, and also b) Just using R without Rstudio

But this does not crash (after restarting R, of course):
```
options(mc.cores=4)
library(brms)
load("test_brm.RData")
out1 = do.call(brm,test_brm)
out2 = do.call(brm,test_brm)
out3 = do.call(brm,test_brm)
out4 = do.call(brm,test_brm)
out5 = do.call(brm,test_brm)
out6 = do.call(brm,test_brm)
out7 = do.call(brm,test_brm)
```
I am not very experienced in these matters, but thought I'd post this just in case it helped with troubleshooting.

**Comment by paul-buerkner** [comment] 2020-09-02 06:33
Thank you! This issue is not related to brms but to rstan. However, we have been seeing these crashes for years without being able to pinpoint it. @bgoodri might be interested in this issue. Can you both please show your `sessionInfo()` of the session where R crashed eventually?

**Comment by andrjohns** [comment] 2020-09-02 06:42
Oh right, that would make sense! I'll extract the Stan code from the ```brms``` call and open an issue over in the RStan repo

**Comment by andrjohns** [comment] 2020-09-02 06:48
Thanks @BrianBucher2 for the added debugging, that's very helpful! @dbarneche it looks like you should be able to get your vignette/actions to finish if you assign the result of each ```bnec``` call to a different object as a temporary workaround

**Comment by dbarneche** [comment] 2020-09-02 07:02
Cheers @andrjohns and @BrianBucher2 , I'll have a go at that and see if it works. Would you mind pasting the link to the new rstan forum post here as well? I'm curious to learn why these crashes are happening, and how they might be resolved in the future.

**Comment by andrjohns** [comment] 2020-09-02 08:15
@dbarneche Another workaround that I've found is to manually trigger R's garbage collection before running the next model:
```
options(mc.cores=4)
library(brms)
load("test_brm.RData")

out = do.call(brm,test_brm)
gc()
out = do.call(brm,test_brm)
gc()
out = do.call(brm,test_brm)
gc()
out = do.call(brm,test_brm)
gc()
out = do.call(brm,test_brm)
gc()
out = do.call(brm,test_brm)
gc()
out = do.call(brm,test_brm)
#No crashes
```

**Comment by dbarneche** [comment] 2020-09-02 08:28
Thanks @andrjohns I might have to do that actually because the ubuntu VM is not handling the memory allocation
https://github.com/open-AIMS/bayesnec/runs/1060220017?check_suite_focus=true

**Comment by dbarneche** [comment] 2020-09-02 09:24
Actually this did fail in Windows again.
I think I'll use the previous solution (i.e. naming all objects differently), but reducing the number of examples, so the Ubuntu VM doesn't crash either.

**Comment by BrianBucher2** [comment] 2020-09-02 15:11
Sure thing, I can post my sessionInfo().  Here it is:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] brms_2.13.5 Rcpp_1.0.5 

loaded via a namespace (and not attached):
 [1] Brobdingnag_1.2-6    jsonlite_1.7.0       gtools_3.8.2        
 [4] StanHeaders_2.21.0-6 RcppParallel_5.0.2   threejs_0.3.3       
 [7] shiny_1.5.0          assertthat_0.2.1     stats4_4.0.2        
[10] backports_1.1.8      pillar_1.4.6         lattice_0.20-41     
[13] glue_1.4.1           digest_0.6.25        promises_1.1.1      
[16] colorspace_1.4-1     htmltools_0.5.0      httpuv_1.5.4        
[19] Matrix_1.2-18        plyr_1.8.6           dygraphs_1.1.1.6    
[22] pkgconfig_2.0.3      rstan_2.21.2         purrr_0.3.4         
[25] xtable_1.8-4         mvtnorm_1.1-1        scales_1.1.1        
[28] processx_3.4.3       later_1.1.0.1        tibble_3.0.3        
[31] bayesplot_1.7.2      generics_0.0.2       ggplot2_3.3.2       
[34] ellipsis_0.3.1       DT_0.15              withr_2.2.0         
[37] shinyjs_1.1          cli_2.0.2            magrittr_1.5        
[40] crayon_1.3.4         mime_0.9             ps_1.3.4            
[43] fansi_0.4.1          nlme_3.1-148         xts_0.12-0          
[46] pkgbuild_1.1.0       colourpicker_1.0     rsconnect_0.8.16    
[49] tools_4.0.2          loo_2.3.1            prettyunits_1.1.1   
[52] lifecycle_0.2.0      matrixStats_0.56.0   stringr_1.4.0       
[55] V8_3.2.0             munsell_0.5.0        callr_3.4.3         
[58] compiler_4.0.2       rlang_0.4.7          grid_4.0.2          
[61] ggridges_0.5.2       htmlwidgets_1.5.1    crosstalk_1.1.0.1   
[64] igraph_1.2.5         miniUI_0.1.1.1       base64enc_0.1-3     
[67] codetools_0.2-16     gtable_0.3.0         inline_0.3.16       
[70] abind_1.4-5          curl_4.3             markdown_1.1        
[73] reshape2_1.4.4       R6_2.4.1             gridExtra_2.3       
[76] rstantools_2.1.1     zoo_1.8-8            bridgesampling_1.0-0
[79] dplyr_1.0.2          fastmap_1.0.1        shinystan_2.5.0     
[82] shinythemes_1.1.2    stringi_1.4.6        parallel_4.0.2      
[85] vctrs_0.3.2          tidyselect_1.1.0     coda_0.19-3
```

**Comment by andrjohns** [comment] 2020-09-03 00:58
@dbarneche can try running the ```gc()``` command immediately before the repeated runs?

Where you currently have:
```
out <- bnec(...)
gc()
...other commands...
out <- bnec(...)
```

Can you try it as:
```
out <- bnec(...)
...other commands...
gc()
out <- bnec(...)
```

**Comment by dbarneche** [comment] 2020-09-03 02:13
Thanks @andrjohns , I just tried that but it also failed :(

I think for the sake of simplicity I'll name each object differently, and then split this vignette into multiple, smaller ones to hopefully have it work across the multiple os. At the end of the day it is probably not ideal to have a vignette that needs 30+ min to build at the user end anyway...

**Comment by andrjohns** [comment] 2020-09-03 05:03
Hmm odd, can you try placing them even closer? I can see that you have:

```
{r, warning = FALSE, message = FALSE, echo = FALSE}
gc()
```

```
{r, warning = FALSE}
set.seed(333)
out <- bnec(data = measure_data, x_var = "raw_x",
            y_var = "measure", model = "nec3param")
```

Is it any different if you have it as:

```
{r, warning = FALSE}
set.seed(333)
gc()
out <- bnec(data = measure_data, x_var = "raw_x",
            y_var = "measure", model = "nec3param")
```

Just trying to see why it's not helpful in this case but it is for me

**Comment by andrjohns** [comment] 2020-09-03 05:08
Also, if you add a ```Makevars```/```Makevars.win``` file  with ```CXX14FLAGS += -O3``` to your instances, you'll cut the runtime down by a significant amount

**Comment by dbarneche** [comment] 2020-09-03 09:13
Thanks for this extra suggestion, I'll incorporate it now. As for the vignette, please see alternative version following your suggestion to test locally (sorry had to zip it to attach it here). We didn't upload this to the repo because I didn't want to include the `gc()` statements into the visible code chunks on the vignette. But hopefully the attached is self-contained for local tests. Let me know if there's anything else I can provide to help understand this, and thanks again for your time.
[example.Rmd.zip](https://github.com/paul-buerkner/brms/files/5167506/example.Rmd.zip)

**Comment by paul-buerkner** [comment] 2021-03-10 15:51
Since these crashes are not caused by brms itself, and I don't think I can solve them from within brms, I will close this issue for now to keep the issue tracker clean. If there is any new information coming up that links this issue to something fixable in brms, please post here and suggest to reopen this issue.

**Closed by paul-buerkner** 2021-03-10 15:51 UTC
Labels: bug
