### ISSUE TITLE
Polytomous response variables with IRT 2PL and GRM models

### ISSUE THREAD

**Issue by mspezio** [paul-buerkner/brms#538] opened 2018-10-24 09:19 UTC
Paul, I have been trying the cumulative() family with a 2PL item response model having 4 possible levels. However, I keep seeing the error that non-linear models are not allowed for ordinal models.

Here is the code, adapted from Issue 203:

fit2 = brm(brmsformula(YResponse ~ exp(disc)*eta,
                       disc ~ 0 + (1 | Item),
                       eta ~ 0 + Item + (1|PptID),
                       nl = TRUE),
           data = UseData2,
           family = cumulative(link="logit"),
           prior = set_prior(disc ~ normal(0,1)),
           chains = nchains,
           cores = ncores,
           iter = niter,
           warmup = nwarmup,
           control = list(adapt_delta = adapt_delta))

Is there a possibility of implementing 2PL and 3PL and Rasch models for polytomous response data?

Thanks very much.

-- Michael

**Comment by paul-buerkner** [comment] 2018-10-24 09:28
This is because of how intercepts have to be treated in ordinal models. Enabling non-linear formulas in ordinal models requires quite a lot of special case coding and I am not sure about a good default behavior for that. 

However, you can already fit 2PL ordinal models using the `disc` parameter of the ordinal families. See https://cran.r-project.org/web/packages/brms/vignettes/brms_distreg.html for instructions how to use the distributional regression approach in brms.

**Comment by paul-buerkner** [comment] 2018-10-26 07:58
From what I see, the `disc` parameter solves your 2PL modeling problem. Thus, I am closing this issue.

**Closed by paul-buerkner** 2018-10-26 07:58 UTC
