### ISSUE TITLE
Continuous category Gaussian Process (sensu McElreath, 2016:410)

### ISSUE THREAD

**Issue by ecologics** [paul-buerkner/brms#300] opened 2017-12-14 23:41 UTC
A feature request, following discussion with Paul by email.

Richard McElreath in _Statistical Rethinking_ implements a very useful varying intercept where categories covary based on a continuous variable.  In his example he uses the Euclidean distance among the geographic coordinates of the groups where data were measured to model the covariance.

In `bf()` formula syntax it might be:

`y ~ (1 | continuousCategoricalVariable)` 

where groups would be defined on the fly as elements that have the same value of `continuousCategoricalVariable`, and a distance matrix among these automatically assembled.  I can imagine that this might be the default behaviour when a non factor is supplied as the grouping variable after the `|`.  There would also need to be a way of specifying the model for covariance.

Just an idea.  Thanks for considering.

**Comment by paul-buerkner** [comment] 2017-12-15 09:06
I like the idea. If `x` is our continuous variable providing the groups and their distance, I think a good syntax would be `~  (1 | co(x))` or even `~  (1 | gp(x))`, if we devide to always use GPs for it. This nicely integrates in the existent framework, since we already have two such functions: `gr()` for the default behavior (automatically added if not specified) and `mm()` for multimemebership models. 

We cannot make `co()` the default for continuous variables, though, as this would be a huge break in backwards compatibility and be very confusing to the vast majority of brms users (and surely even myself a week after implementing that).

With "model for covariance", do you mean the covariance kernel? We could simply add an argument to `co` to control the type of covariance kernel.

**Comment by ecologics** [comment] 2017-12-16 18:15
Yes--covariance kernel is what I mean.

Another thing to think about is what happens when you have two or more variables that are continuous (i.e. as in McElreath's spatial coo-rdinate example. .  This might favour the `~ (1 | gp(x1, x2)` kind of syntax.

**Comment by paul-buerkner** [comment] 2017-12-25 18:52
After reading through the rethinking chapter again, I realized that the desired functionality is already available via the `gp()` function of brms (and I wonder why I did not see this immediately...). The continuous category intercept model Richard describes is simply specified in brms via `gp(longitude, latitude)`, where `longitude` and `latitude` indicate the 2-dimensional positions of each island. So if I am not mistaken, we do not even need a new feature for such a model.

**Comment by paul-buerkner** [comment] 2018-01-07 15:36
I am closing this for now. If you find an application that cannot already be treated using ordinary `gp()` terms in **brms**, please feel free to reopen it!

**Comment by ecologics** [comment] 2018-01-14 22:49
I apologize that I should not have originally proposed this feature.  I believe (if I understand all the nuances) that the `cov_ranef=` option in `brm()` actually achieves this.  That McElreath calls it a Gaussian Process has been rather confusing.

In such case closing it is appropriate.  And if I am correct, other's finding this note can give `cov_ranef'` a try, checking out Paul's example in `vignette("brms_phylogenetics")` if they want to replicate the analysis in McElreath Chapter 13.2.

**Comment by paul-buerkner** [comment] 2018-01-15 08:06
Richard is right when he calls this a Gaussian process, because it is one. The `cov_ranef` argument does something *very different* in that you have to specify the whole correlation matrix a-priori instead of estimating it on the fly via a Gaussian process.

As I said above, you can fit such a Gaussian process via the `gp()` function of brms. The only drawback of this approach is that it is less computationally efficients (as compared to Richard's code) in case of multiple observations per location.

**Comment by paul-buerkner** [comment] 2018-06-26 18:39
Reopening this issue. I think we should add a `gr` argument (short for "group") to `gp()` to simplify the computation if the GP-covariates are constant within groups. This could actually make GPs feasible in many situatutions where it is currently impossible to fit them in reasonable time.

**Comment by paul-buerkner** [comment] 2018-06-28 18:37
This issue can now be closed after merging PR #464. With this PR, we get the option to auto-group observations sharing the same covariate values. For instance, if we have Richards example data of the islands in long format, we can use the GP term `gp(longitude, latitude, gr = TRUE)`. This will internally group all observations with the same longitude and latitute values (i.e. the same islands), which then receive a single latent variable to be put into the GP. This will increase sampling efficiency drastically in cases with many observation per location (or time-point or whatever else our covariates are).

**Closed by paul-buerkner** 2018-06-28 18:37 UTC
Labels: feature

**Comment by ecologics** [comment] 2018-06-28 18:57
This is very exciting Paul! You know it may have also have been possible to gps using s(bs="gp") through  mgcv, although  I haven't tried it. But I do know that I am having great difficulty in getting fancy mgcv based models to sample well in brms. So this is excellent.

**Comment by paul-buerkner** [comment] 2018-06-28 19:00
I know, but I think it is also great to support real GPs built natively in Stan. That's why I not only rely on mgcv to fit GPs using spline approximations.

**Comment by ASKurz** [comment] 2020-04-11 22:56
Hi @ecologics, were you ever able to reproduce McElreath’s spatial GP model with **brms**? My attempts using @paul-buerkner's `gp(longitude, latitude, gr = TRUE)` syntax haven't quite hit the mark.
