### ISSUE TITLE
file for add_ic

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#478] opened 2018-07-23 10:20 UTC
The new `file` command in `brm()` is very useful. It might be useful to have a similar command for `add_ic`/`add_loo` etc. given how long this can take to calculate. I suppose such a command would have to check whether or not the corresponding rds file has the loo info already included.

**Comment by paul-buerkner** [comment] 2018-07-23 10:36
What do you think of the following hypothetical behavior?

```
fit <- add_ic(fit, ic = "loo", file = "fit.rds")
# If "fit.rds" does not exist, store fit in "fit.rds" after computing loo if necessary
# Else load "fit.rds", compute loo if necessary, and store the updated model in "fit.rds"
```

**Comment by andymilne** [comment] 2018-07-23 10:38
Yes, that makes sense!

**Comment by rubenarslan** [comment] 2018-08-04 06:56
Would it be possible for `add_ic` to recycle the file argument from the `brm` call? I usually had a two-step procedure (run model & save, try computing LOO/WAIC, then save over first). This would allow me to write simpler code.

**Comment by rubenarslan** [comment] 2018-08-04 08:47
Yes, iff the brm call also had a file argument.

**Comment by paul-buerkner** [comment] 2018-08-04 10:25
We need to think through the implications of using `file` anywhere else than in `brm`. 

For `brm` the behavior is straight forward and intuitive in the sense that we take the stored fitted model object if it exists and otherwise fit the model and save it to disk.

However, as soon as we have the fitted model loaded and do some post processing (e.g. via `add_ic`) a reasonable and intuitive behavior of `file` is no longer straigt forward. For instance, if the file exists, should it be loaded and returned regardless of whether it contains a pre-computed `loo` object? 

The thing is that if I pass an object to `add_ic` I expect this object to be returned in any case just with `loo` added to it. If however, the file accidently contains another brmsfit object, this will be returend so we may silently changing the model through `add_ic`. Maybe, we need to make sure that the loaded model is actually the same as the model currently loaded in workspace.

In any case, we should have a clear understanding of a good interaction between fitted model loaded in workspace and file saved to disk to make it save and intuitive to use.

**Comment by rubenarslan** [comment] 2018-08-04 10:34
You mean in a case, where there is a model with a file argument, the file
is overwritten in a separate process, and then the model is passed to
add_ic in the first process? I guess it could happen on a cluster. Is there
a quick way (hash?) to check that nothing going into the model has changed?
But adding ICs and caching is definitely a use case I had quite often.

Btw. could add_ic also take a future argument?

**Comment by paul-buerkner** [comment] 2018-08-04 10:36
Exactly. I have no doubt about the use case, I just want it to be save. Maybe hashing could be something to consider. Let me think about it.

Using futures to compute loo had to be implemented inside the **loo** package I guess and is a bit off-topic in this issue.

**Comment by paul-buerkner** [comment] 2018-09-23 22:44
In the new github version of brms, `add_ic` now has a `file` argument. In contrast to `brm`, `add_ic` will only **save** but not **load** fitted model objects to avoid a whole lot of weird situations some of which we discussed above. 

@andymilne and @rubenarslan would you mind testing my implementation?

**Comment by rubenarslan** [comment] 2018-09-28 10:38
It seems to be working as intended. The implementation is reasonable: I like that it just saves, but doesn't load. My request was that `add_ic` recycles the file argument, just to keep things DRY.

Rather than write
```r
fit_sleep2 <- brm(Reaction ~ 0 + Subject + Subject:Days, 
                  data = sleepstudy, file = "fit_sleep2") %>% 
  add_ic("loo", file = "fit_sleep2")
```

I'd like to be able to write simply
```r
fit_sleep2 <- brm(Reaction ~ 0 + Subject + Subject:Days, 
                  data = sleepstudy, file = "fit_sleep2") %>% 
  add_ic("loo")
```

or maybe
```r
fit_sleep2 <- brm(Reaction ~ 0 + Subject + Subject:Days, 
                  data = sleepstudy, file = "fit_sleep2") %>% 
  add_ic("loo", file = "fit_sleep2", file = TRUE)
```

The reason is simply that I know if I'm fitting lots of models and giving them unique names, I will make mistakes and there will be mismatches occasionally. It's not a biggie. I think if I'm fitting a model with a `file` argument and then I `add_ic`, it's pretty clear I also want that to carry over to the model on disk. At least that's the code I was writing manually before.

It's not super important of course, but I guess it also would not be that much trouble to implement.

**Comment by paul-buerkner** [comment] 2018-09-28 10:47
That suggestion looks reasonable to me. This requires brmsfit object to have an additional "file" slot to recycle, whch is currently not the case. 

The behavior could be as follows: If `file` was specified in `brm()`, it is stored and used in `add_ic` by default with a message that this is happening. You may be accidently overwriting other model objects if your naming was not careful enough, but at least you are being informed that this happend. If `file` is specified inside `add_ic` it will overwrite the file name stored in the brmsfit object.

@rubenarslan Do you think that's a reasonable behavior?

**Comment by rubenarslan** [comment] 2018-09-28 10:49
Yes, that seems smart!

**Comment by paul-buerkner** [comment] 2018-09-28 11:31
This should now be working in the github version of brms. Can you please quickly check it with some of your own models?

**Comment by rubenarslan** [comment] 2018-09-28 16:12
works great!

**Comment by andymilne** [comment] 2018-10-01 13:20
If I do `brm(Mdl1, ..., file = "Mdl1")` then do `Mdl2 <- add_loo(Mdl1)`, I get an incorrect message saying `Automatically saving the model object in 'Mdl1.rds'`. Presumably, it should instead say `Automatically saving the model object in 'Mdl2.rds'`.

**Comment by rubenarslan** [comment] 2018-10-01 13:57
No, the message is correct. `add_loo` recycles the file argument from the previous call. It doesn't see the variable name it is assigned to. It also doesn't really make sense to rename the model when you add ICs, does it?

**Comment by paul-buerkner** [comment] 2018-10-01 16:34
Ruben is right. The current behavior is intended and the recommended workflow is to overwrite the existing object not create a new one with a different name. For instance:

```
Mdl1 <- brm(..., file = "Mdl1")
Mdl1 <- add_loo(Mdl1)
```

**Comment by paul-buerkner** [comment] 2018-10-01 20:06
I think we can close this issue now.

**Closed by paul-buerkner** 2018-10-01 20:06 UTC
Labels: enhancement

**Comment by andymilne** [comment] 2018-10-01 20:39
Yes, but if you try it you will see that the loo info does not get added to Mdl1 but does get added to Mdl2, so the message is incorrect. In my view, what brms does here is correct, it is just the message that is wrong.

**Comment by paul-buerkner** [comment] 2018-10-01 20:43
`add_loo` (or any function for that matter) cannot now to what it's result will be assigned to. It only
knows what is passed to it as arguments and you are passing `Mdl1`. So the messaging you are suggesting
to be issued is impossible to generate.

**Comment by andymilne** [comment] 2018-10-01 21:39
Say I have fitted a model `Mdl1`. Then I do `Mdl1 <- add_loo(Mdl1, nsamples = 500)`. Then I decide I wanted to redo the loo but with a different number of samples. Is this possible? For example, if I do `Mdl1 <- add_loo(Mdl1, nsamples = 1000)`, nothing is calculated. Can there be a check within `add_loo` for if any of the loo parameters have changed -- if they have `add_loo` is run again?

**Comment by andymilne** [comment] 2018-10-01 21:42
BTW, it was precisely for this reason that I did a call like `Mdl2 <- addloo(Mdl1, nsamples = 500)`, because I wanted to allow for myself to be able to later on redo the loo on Mdl1, with a different number of samples, if necessary.

**Comment by paul-buerkner** [comment] 2018-10-01 21:43
If you take a closer look at the documentation, you will see there is a `overwrite` argument that allows you to overwrite already existing criterion objects. I don't think such checks would be feasible due to the sheer number of option.

**Comment by andymilne** [comment] 2018-10-01 21:45
I didn't know about the overwrite option, that's great!
