### ISSUE TITLE
Problems using emmeans with brms for Ordinal regression

### ISSUE THREAD

**Issue by nvanzuy** [paul-buerkner/brms#980] opened 2020-08-13 11:04 UTC
Hi,

We are using brms to run some ordinal regression analyses and want to estimate the marginal means from the model.  The model we are running is similar to the one given below. 

Would it be possible to get some feedback on this issue ?  It seems to be related to:  https://github.com/rvlenth/emmeans/issues/113

Here is some code which reproduces the problem:

library(tidyverse)
library(emmeans)
library(brms)
library(tidybayes)
library(dplyr)

####
data(mtcars)
#####

mtcars <- mtcars %>%
  mutate(carb=as.ordered(carb),cyl=as.factor(cyl))

model <- brm(
  carb ~ cyl,
  family = cumulative(link = probit,
                      threshold = "flexible"),
  prior = c(
    set_prior(prior = "normal(0, 1)",
              class = "Intercept"),
    set_prior(prior = "normal(0, 1)",
              class = "b")
  ), data=mtcars)

emmeans_model <- emmeans(model,trt.vs.ctrl ~ cyl)

 Error in vcov(object)[nm, nm, drop = FALSE] : subscript out of bounds
 In addition: Warning message:
  In model.matrix.default(trms, m, contrasts.arg = contr) :
   variable 'carb' is absent, its contrast will be ignored

If this requires some work I'm happy to have a look at it if you can point me to the function that needs to be amended.

Thanks,
Natalie

**Comment by paul-buerkner** [comment] 2020-08-14 06:44
The problem is likely with the handling of the ordinal thresholds as they are part of the fixed effects and thus of `vcov` but I haven't looked in detail yet. Tagging @rvlenth to make him aware of this issue as well.

**Comment by rvlenth** [comment] 2020-08-15 17:02
I agree with @paul-buerkner 's assessment. Ordinal models have an intercept for each cut point. The way this is handled in **emmeans** support for other ordinal models (e.g., `ordinal::clm`) is to create a pseudo-factor named `cut` and an expanded model matrix that has a block for each level of `cut` with the intercept in the corresponding position.

There is also the matter of what one means by "marginal means" in this context. The marginal means of the linear predictor for each cut point? The average of these over cut points (which I support for `cld` as `mode = "latent"`)? The cumulative probabilities? The probabilities between cut points?

The **emmeans** support for `clm`, `clmm`, and `polr` models is in https://github.com/rvlenth/emmeans/blob/master/R/ordinal-support.R. It is among the most complex of any code in the package, because of the many possibilities mentioned above. But I think what is probably needed is a fairly straightforward adaptation of all or part of this code. Some of the supported modes require post-processing via functions named in, e.g., `misc$postGridHook`.

**Comment by paul-buerkner** [comment] 2020-08-15 18:25
Thank you @rvlenth! This is really helpful in ensuring that ordinal brms models will be supported in emmeans at some point (once I find the time to dig into the details of the code you linked to).

**Comment by nvanzuy** [comment] 2020-08-18 11:05
Thank you both for your response. I look forward to the updates.

**Comment by rvlenth** [comment] 2021-03-11 23:09
Hmmm. I don't think I changed anything that would affect this. I was also able to get through this without an actual error, though it crashed my R session the first try (who knows why). I also got a warning message about ignoring the contrast matrix for `carb`. 
```r
> EMM <- emmeans(model, ~ cyl)
Warning message:
In model.matrix.default(terms, data, ...) :
  variable 'carb' is absent, its contrast will be ignored

> EMM
 cyl emmean lower.HPD upper.HPD
 4     0.00     0.000      0.00
 6     1.02     0.125      1.92
 8     1.25     0.396      2.06

Point estimate displayed: median 
Results are given on the probit (not the response) scale. 
HPD interval probability: 0.95 
```
I assume that happens because `carb` is a factor, but it is also the response variable. The way to avoid that would be to strip off the response variable from `attr(object, "contrasts")` in about the 14th line of `emm_basis.brmsfit`. 

Currently `emm_basis.brmsfit` does not have a mode for separating-out the intercepts for the ortdinal model, and my guess is that what we are seeing is somewhat akin to the `"latent"` mode in the **emmeans** support for such as `ordinal::clm` models. On the latent scale, the origin and scale parameter are not uniquely identified, but it still allows one to assess comparisons among factor levels.
```r
> contrast(EMM, "trt.vs.ctrl")
Note: Use 'contrast(regrid(object), ...)' to obtain contrasts of back-transformed estimates
 contrast estimate lower.HPD upper.HPD
 6 - 4        1.02     0.125      1.92
 8 - 4        1.25     0.396      2.06

Note: contrasts are still on the probit scale 
Point estimate displayed: median 
HPD interval probability: 0.95 
```
The way this is scaled, the Dunnett-style comparisons are the same as the EMMs, because the first level is a hard zero.

**Comment by paul-buerkner** [comment] 2021-03-12 07:51
Thanks for your input! I am glad sometimes things appear to solve themselves. :-D 

I agree that we are now doing the latent approach. I have relabled this issue a feature and leave it open so that we will be reminded of implemented the per-threshold option as well at some point.

**Comment by paul-buerkner** [comment] 2024-01-27 20:09
Closing this issue for now to reduce the load of the issue tracker. If someone has time and wants to work on this, feel free to write here and I am happy to reopen.

**Closed by paul-buerkner** 2024-01-27 20:09 UTC
Labels: feature, post-processing

**Comment by rvlenth** [comment] 2024-04-04 19:05
I can't really comment on this because the actual results from `emmeans` are masked by filtering them through `as.tibble` and `pander` (whatever that is). I am not ` "tidy" person, and all this filtering of the results destroys the annotations that were so carefully added by my `summary` methods before you even get to see them.


All that said, I think what we see here is like apples compared with oranges. By default, the `emmeans` results for an ordinal model are on the latent scale (though, that said, I'm confused by why they are not all near zero). I suspect you might get more comparable results by adding `mode = "mean.class"` to the `emmeans()` call.

PS -- I am unable to fit the model for some reason, even though I reinstalled it immediately beforehand:
```
> m <- brm(y~x, data=df, family = cumulative)
Compiling Stan program...
Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! Command 'mingw32-make.exe' not found @win/processx.c:982 (processx_exec)
```

**Comment by benwhalley** [comment] 2024-04-04 20:58
Yes, by default emmeans results are on the latent scale, with a reference category set to zero.
I added `type="response"` to try and get responses on the original ordered scale. I'm not sure what that actually produced. 

FWIW I think it would be perfectly reasonable for emmeans to just refuse to work with `type="response"`, but it if it does produce numbers it should be clear what they are. I suspect it might be quite a common case that people have ordered responses on a 1-7 or 1-10 scale and would like to reconstruct those response for a given set of predictors after modelling, and even take summaries like the mean.  I can see that it's not all that well defined, though.

**Comment by rvlenth** [comment] 2024-04-04 21:46
> but it if it does produce numbers it should be clear what they are

Exactly. Which is why it's so sad that so many users throw away that information when they think they are "tidying" up the output. Package developers write `print` and `summary` methods for a reason.

**Comment by benwhalley** [comment] 2024-04-04 22:11
I can  see you wouldn't want people to lose the messages, but you do see them interactively even when coercing to a tibble.   However, they aren't super-informative in this specific case. Running `emmeans(m, "x", type="response") `  produces this:

```
Warning: brms' emmeans support for ordinal models is experimental and currently ignores the threshold parameters.Warning: brms' emmeans support for ordinal models is experimental and currently ignores the threshold parameters. x response lower.HPD upper.HPD
 a    0.500     0.500     0.500
 b    0.498     0.434     0.565
 c    0.520     0.454     0.583

```

I get that it's experimental, but I'm not really sure what "currently ignores the threshold parameters" means.  You get exactly the same message if you omit the `type="response"` argument, so it's not an effective warning that the results are on a latent scale (default) or somewhat undefined.

Also, as an aside, as a package  user it's always pretty annoying to me that tabular result isn't either dataframe or can be treated like a dataframe.  I don't exclusively use the tidyverse, but the pattern of treating the output of modelling and similar functions as data to be manipulated is great.
It's so common to want to aggregate results from different models and print them in a consistent way. (e.g. in Rmarkdown).  I don't think that pattern is incompatible with printing nice messages to the console. The brms `hypothesis` function would be a good example here — it outputs text messages and information, but returns actual results as values in a df.

**Comment by rvlenth** [comment] 2024-04-04 22:44
> Also, as an aside, as a package user it's always pretty annoying to me that tabular result isn't either dataframe or can be treated like a dataframe. 

You seem to be making an assumption that this is not true. In fact, `summary.emmGrid()` produces an annotated object that 
inherits from `data.frame` and whose `print` method displays the data frame with unexaggerated precision along with the annotations. For ordinal models fitted with **ordinal**, **MASS*, and some others, there are several post-processing options that include probabilities, cumulative probabilities, reverse cumulative, and means on the `1,2,...,k` scale of the ordinal response (see https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#ordinal). Those post-processing options are not currently incorporated in the **brmsfit** support.

It would create utter chaos among my users if I changed the column names to some tidy "standard". I do know that the **broom** package has methods for `emmGrid` and `emm_summary` objects and can be used to rename output to conform to some kind of standard. But I know of no "tidy" standards for including informative annotations, which is something I have worked hard to include in my summaries.

**Comment by benwhalley** [comment] 2024-04-05 08:25
Sorry - I really hadn't mean to drag this down into bikeshedding about return formats. I really do appreciate the concise print methods that emmeans has, and it's not so hard to convert to df when aggregating results over multiple runs. Agreed that it would be nice to have a tidy (or any) standard for adding annotations to returned objects. I tend to do this informally in my own code quite a lot.

I think my questions at this point are i) what does emmeans actually return when applied to brms ordinal models as I did above, and ii) is it possible to get the cool modes like `='prob'` and `mode = "mean.class"` for brms models, as described in that vignette? Perhaps @paul-buerkner is best placed to answer though?

**Comment by venpopov** [comment] 2024-04-05 09:39
btw @benwhalley you are confusing the print output format of emmeans with the object that it produces. The return value of emmeans is a complex S4 objects, but when you print it, it internally calls `summary()`, which does produce a data.frame:

<img width="828" alt="image" src="https://github.com/paul-buerkner/brms/assets/12783882/9e6c938a-2aba-40e2-8728-5384fca10dd5">

So you can in fact do operations like `filter`, but you have to do it on `summary(emmeans(...))`. 

When you do `as.data.frame(emmeans(...))`, you get the same result as from `summary()` - an annotated data.frame with attributes which store additional information such as the scale

<img width="830" alt="image" src="https://github.com/paul-buerkner/brms/assets/12783882/4a76847d-b061-4dd1-9159-3106ff26b61d">

The reason you missed those messages is because `as.tibble()` strips the `summary_emm` class, and does not know that it should print the extra info:

<img width="820" alt="image" src="https://github.com/paul-buerkner/brms/assets/12783882/62b11891-962e-4c99-869a-a430a6f3c13c">

So your note that "you see the warnings" interactively was only partially correct - you miss other important information that @rvlenth pointed out

**Comment by rvlenth** [comment] 2024-04-05 15:38
More and more, I am recalling that there really is no ordinal-model-specific `emmeans` support for `brmsfit` models. What we see here is just what comes out in the wash when we treat it as a glm, and that turns out to be an interpretation of the model coefficients, which comes out pretty much on the latent scale, but with the reference class constrained at zero rather than the grand mean set to zero as in `emmeans`'s methods for `ordinal::clm` and `MASS::polr` models. However, be careful, because often, cumulative logit models have their signs reversed, so that the class with the highest latent mean will actually have the lowest estimate. The sign reversal is related to modeling the cumulative probabilities via $\mathrm{logit}(y - \eta)$ with $\eta$ being the linear predictor.

If summarized with `type = "response"`, the estimates are simply back-transformed with the link function. The special ordinal-support code uses a `mode` (not `type`) argument to delineate them.

**Comment by rvlenth** [comment] 2024-04-05 16:44
FWIW, here is what we get on the latent and mean.class scale for @benwhalley's example
```
> df.clm <- ordinal::clm(y ~ x, data = df)
> emmeans(df.clm, "x", mode = "latent")
 x   emmean     SE  df asymp.LCL asymp.UCL
 a -0.00405 0.0943 Inf   -0.1889     0.181
 b  0.11893 0.0967 Inf   -0.0706     0.308
 c -0.07594 0.0973 Inf   -0.2666     0.115

Confidence level used: 0.95 

> emmeans(df.clm, "x", mode = "mean.class")
 x mean.class    SE  df asymp.LCL asymp.UCL
 a       3.99 0.110 Inf      3.77      4.20
 b       4.13 0.113 Inf      3.91      4.35
 c       3.90 0.113 Inf      3.68      4.12

Confidence level used: 0.95 
```
I do not get the same raw means that @benwhalley shows though:
```
> df %>% 
+     group_by(x) %>% 
+     summarise(mean(y_num))
# A tibble: 3 × 2
  x     `mean(y_num)`
  <chr>         <dbl>
1 a              3.98
2 b              4.13
3 c              3.91
```
These are in close correspondence to the `emmeans` results. I don't know whether to trust his `emmeans` results.
