### ISSUE TITLE
posterior_predict error with binomial model

### ISSUE THREAD

**Issue by mansillo** [paul-buerkner/brms#493] opened 2018-08-09 06:39 UTC
I think I found an error with the posterior_predict function with binomial models implemented in brms - or I have misunderstood the documentation (which I followed pretty closely, but I still include it as a distinct possibility).

I have been endeavouring to implement [multi-level regression and post-stratification (MRP) with the brms package](https://timmastny.rbind.io/blog/multilevel-mrp-tidybayes-brms-stan/). I had previously been implementing MRP with the [arm package](https://cran.r-project.org/web/packages/arm/arm.pdf) as per the [Kastellec, Lax & Phillips MRP primer/cookbook](http://www.princeton.edu/~jkastell/MRP_primer/mrp_primer.pdf) but I decided to move over to implement a full Bayesian model in Stan to include informative priors and brms always a very convenient method to model the data with more subtle features than what the [lme4 package](https://cran.r-project.org/web/packages/lme4/lme4.pdf) allows. The size of the data I am working with does vary between n=700,000 and n=1,400,000 and has a hierarchical structure. Since micro-level, binary data can often be aggregated to form group-level binomial data and since this can often lead to tremendous gains in computational efficiency, I have a pretty clear motivation to stack the individual-level binary data (which becomes about n=160,000 or between a fourth or ninth of the size) to estimate a binomial-logit model rather than a Bernoulli-logit model.

Given the need to maintain academic integrity, I've reproduced the error with some fake data. The R code I use to implement the binomial model is below (with [Simon Jackman's code to collapse covariates classes](https://www.wiley.com/en-us/Bayesian+Analysis+for+the+Social+Sciences-p-9780470011546)):

```R
library(brms)


# make fake data
y = sample( c(0,1), 10000, replace=TRUE, prob=c(0.95,0.05)  )


div <- paste0("div.",seq(1, 150, by=1))
division  <- sample( div, 10000, replace=TRUE )
div.X <- data.frame(division=div,
                    swing=rnorm(150, mean = 0, sd = 1),
                    divinc=rnorm(150, mean = 0, sd = 1),
                    divenggap=rnorm(150, mean = 0, sd = 1))

inc <- paste0("inc.",seq(1, 4, by=1))

inc <- c(inc,"inc.ns")
income  <- sample( inc, 10000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.25,0.15)  )

X <- data.frame(division = division,
                gender = sample( c("male","female"), 10000, replace=TRUE, prob=c(0.5,0.5)  ),
                birthplace=sample(c("western","nonwestern"), 10000, replace=TRUE, prob=c(0.8,0.2)  ),
                income = income,
                education=sample( c("edu.1","edu.2","edu.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6)  ),
                age = sample( c("age.1","age.2","age.3","age.4"), 10000, replace=TRUE, prob=c(0.4, 0.2, 0.2, 0.2)  ),
                religion=sample( c("relig.1","relig.2","relig.3","relig.4"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.4)  ),
                f1 = sample( c("f1.1","f1.2","f1.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6)  ),
                f2 = sample( c("f2.1","f2.2","f2.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6) ),
                f3 = sample( c("f3.1","f3.2","f3.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6) ),
                privhealth=as.numeric(sample( c(1,2,3,4,5), 10000, replace=TRUE, prob=c(0.4, 0.35, 0.15, 0.03,0.02)  ))
)
library(dplyr)
X <- left_join(X,div.X)

# Format data for binomial model

X <- apply(X,1,paste,collapse=":")
covClasses <- match(X,unique(X))
covX <- matrix(unlist(strsplit(unique(X),":")),ncol=14,byrow=TRUE)
r <- tapply(y,covClasses,sum)
n <- tapply(y,covClasses,length)
groupedData <- list(n=n,r=r,
                    division=as.character(covX[,1]),
                    gender=as.character(covX[,2]),
                    birthplace=as.character(covX[,3]),
                    income=as.character(covX[,4]),
                    education=as.character(covX[,5]),
                    age=as.character(covX[,6]),
                    religion=as.character(covX[,7]),
                    f1=as.character(covX[,8]),
                    f2=as.character(covX[,9]),
                    f3=as.character(covX[,10]),
                    swing=as.numeric(covX[,11]),
                    # unemploy=as.numeric(covX[,12]),
                    divinc=as.numeric(covX[,12]),
                    divenggap=as.numeric(covX[,13]),
                    #ssmnonres=as.numeric(covX[,15]),
                    privhealth = as.numeric(covX[,14]),
                    #GDP = as.numeric(covX[,15]),
                    NOBS=length(n))

library(brms)

# make priors

priors <- get_prior(r | trials(n)  ~ (1|division) + (1|gender)+(1|birthplace) + (1|income) + (1|education) + (1+privhealth|age) + (1|religion) +
                      (1|f1) + (1|f2) + (1|f3) +
                      swing +
                      t2(divinc,divenggap,by=f2,k=4)
                    ,
                    data=groupedData,
                    family=binomial("logit"))


# Priors

priors$prior[2] <- "normal(0.045,0.5)" # 
priors$prior[3] <- "normal(0,1)" # 
priors$prior[4] <- "normal(0,0.1)" # 
priors$prior[5] <- "normal(0,1)" # 

priors$prior[6] <- "normal(0,1)" # 
priors$prior[7] <- "normal(0,1)" # 
priors$prior[8] <- "normal(0,1)" # 

priors$prior[9] <- "normal(0,1)" # 
priors$prior[10] <- "normal(0,1)" # 
priors$prior[11] <- "normal(0,1)" # 

priors$prior[13] <- "lkj_corr_cholesky(1.2)" 
priors$prior[14] <- "student_t(3,-1.5,15)" # 

priors$prior[17] <- "inv_gamma(3,0.5)" # 
priors$prior[18] <- "inv_gamma(3,0.5)" # 
priors$prior[20] <- "inv_gamma(3,0.5)" # 
priors$prior[22] <- "inv_gamma(4,1)" # 
#priors$prior[22] <- "cauchy(0.2,3)" #
priors$prior[24] <- "inv_gamma(2,0.5)" # 


priors$prior[26] <- "inv_gamma(4,1)" # 
priors$prior[28] <- "inv_gamma(3,2)" # 
priors$prior[30] <- "inv_gamma(3,1)" #


priors$prior[32] <- "inv_gamma(6,0.8)" # 
priors$prior[34] <- "inv_gamma(5,1)" # 
priors$prior[36] <- "inv_gamma(4,1)" # 

priors$prior[38] <- "inv_gamma(3,2)" # 

# Run model

model <- brm(r | trials(n)  ~ (1|division) + (1|gender)+(1|birthplace) + (1|income) + (1|education) + (1+privhealth|age) + (1|religion) +
               (1|f1) + (1|f2) + (1|f3) +
               swing +
               t2(divinc,divenggap,by=f2,k=4)
             ,
             data=groupedData,
             prior=priors,
             family=binomial("logit"),
             #inits = 0,
             chains = 2,
             iter = 500,
             sparse = TRUE,
             silent = FALSE,
             cores=2,
             control=list(adapt_delta =0.8,
                          max_treedepth=30))

# Make poststratificstion frame

division  <- sample( div, 1000000, replace=TRUE )

income  <- sample( inc, 1000000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.20,0.20)  )

census.X <- data.frame(division = division,
                       gender = sample( c("male","female"), 1000000, replace=TRUE, prob=c(0.5,0.5)  ),
                       birthplace=sample(c("western","nonwestern"), 1000000, replace=TRUE, prob=c(0.7,0.3)  ),
                       income = income,
                       education=sample( c("edu.1","edu.2","edu.3"), 1000000, replace=TRUE, prob=c(0.4, 0.2, 0.4)  ),
                       age = sample( c("age.1","age.2","age.3","age.4"), 1000000, replace=TRUE, prob=c(0.25, 0.25, 0.25, 0.25)  ),
                       religion=sample( c("relig.1","relig.2","relig.3","relig.4"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.4)  ),
                       f1 = sample( c("f1.1","f1.2","f1.3"), 1000000, replace=TRUE, prob=c(0.3, 0.3, 0.4)  ),
                       f2 = sample( c("f2.1","f2.2","f2.3"), 1000000, replace=TRUE, prob=c(0.3, 0.3, 0.4) ),
                       f3 = sample( c("f3.1","f3.2","f3.3"), 1000000, replace=TRUE, prob=c(0.3, 0.3, 0.4) ),
                       privhealth=as.numeric(sample( c(1,2,3,4,5), 1000000, replace=TRUE, prob=c(0.4, 0.35, 0.15, 0.03,0.02)  ))
)
library(dplyr)
census.X <- left_join(census.X,div.X)

frame <- census.X %>% 
  group_by(division,gender,birthplace,income,education,age,religion,f1,f2,f3,privhealth,swing,divinc,divenggap)%>% 
  summarise(N=n())

# poststratiify

pp <- posterior_predict(model,newdata=frame)

library(tidybayes)

add_predicted_draws(model, newdata=frame, allow_new_levels=TRUE, 
                    n=500, summary=FALSE)
`

This produces this error:

`Error: The following variables are missing in 'data':
'n'`

This also was the error that occurred with the posterior_linpred function.

I implemented the model as a Bernoulli-logit model with the following code with success:

`library(brms)


# make fake data
y = sample( c(0,1), 10000, replace=TRUE, prob=c(0.95,0.05)  )


div <- paste0("div.",seq(1, 150, by=1))
division  <- sample( div, 10000, replace=TRUE )
div.X <- data.frame(division=div,
                    swing=rnorm(150, mean = 0, sd = 1),
                    divinc=rnorm(150, mean = 0, sd = 1),
                    divenggap=rnorm(150, mean = 0, sd = 1))

inc <- paste0("inc.",seq(1, 4, by=1))

inc <- c(inc,"inc.ns")
income  <- sample( inc, 10000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.25,0.15)  )

X <- data.frame(division = division,
                gender = sample( c("male","female"), 10000, replace=TRUE, prob=c(0.5,0.5)  ),
                birthplace=sample(c("western","nonwestern"), 10000, replace=TRUE, prob=c(0.8,0.2)  ),
                income = income,
                education=sample( c("edu.1","edu.2","edu.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6)  ),
                age = sample( c("age.1","age.2","age.3","age.4"), 10000, replace=TRUE, prob=c(0.4, 0.2, 0.2, 0.2)  ),
                religion=sample( c("relig.1","relig.2","relig.3","relig.4"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.4)  ),
                f1 = sample( c("f1.1","f1.2","f1.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6)  ),
                f2 = sample( c("f2.1","f2.2","f2.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6) ),
                f3 = sample( c("f3.1","f3.2","f3.3"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.6) ),
                privhealth=as.numeric(sample( c(1,2,3,4,5), 10000, replace=TRUE, prob=c(0.4, 0.35, 0.15, 0.03,0.02)  ))
)
library(dplyr)
X <- left_join(X,div.X)
df <- data.frame(X,y)

# # Format data for binomial model
# 
# X <- apply(X,1,paste,collapse=":")
# covClasses <- match(X,unique(X))
# covX <- matrix(unlist(strsplit(unique(X),":")),ncol=14,byrow=TRUE)
# r <- tapply(y,covClasses,sum)
# n <- tapply(y,covClasses,length)
# groupedData <- list(n=n,r=r,
#                     division=as.character(covX[,1]),
#                     gender=as.character(covX[,2]),
#                     birthplace=as.character(covX[,3]),
#                     income=as.character(covX[,4]),
#                     education=as.character(covX[,5]),
#                     age=as.character(covX[,6]),
#                     religion=as.character(covX[,7]),
#                     f1=as.character(covX[,8]),
#                     f2=as.character(covX[,9]),
#                     f3=as.character(covX[,10]),
#                     swing=as.numeric(covX[,11]),
#                     # unemploy=as.numeric(covX[,12]),
#                     divinc=as.numeric(covX[,12]),
#                     divenggap=as.numeric(covX[,13]),
#                     #ssmnonres=as.numeric(covX[,15]),
#                     privhealth = as.numeric(covX[,14]),
#                     #GDP = as.numeric(covX[,15]),
#                     NOBS=length(n))

library(brms)

# make priors

priors <- get_prior(y  ~ (1|division) + (1|gender)+(1|birthplace) + (1|income) + (1|education) + (1+privhealth|age) + (1|religion) +
                      (1|f1) + (1|f2) + (1|f3) +
                      swing +
                      t2(divinc,divenggap,by=f2,k=4)
                    ,
                    data=df,
                    family=bernoulli("logit"))


# Priors

priors$prior[2] <- "normal(0.045,0.5)" # 
priors$prior[3] <- "normal(0,1)" # 
priors$prior[4] <- "normal(0,0.1)" # 
priors$prior[5] <- "normal(0,1)" # 

priors$prior[6] <- "normal(0,1)" # 
priors$prior[7] <- "normal(0,1)" # 
priors$prior[8] <- "normal(0,1)" # 

priors$prior[9] <- "normal(0,1)" # 
priors$prior[10] <- "normal(0,1)" # 
priors$prior[11] <- "normal(0,1)" # 

priors$prior[13] <- "lkj_corr_cholesky(1.2)" 
priors$prior[14] <- "student_t(3,-1.5,15)" # 

priors$prior[17] <- "inv_gamma(3,0.5)" # 
priors$prior[18] <- "inv_gamma(3,0.5)" # 
priors$prior[20] <- "inv_gamma(3,0.5)" # 
priors$prior[22] <- "inv_gamma(4,1)" # 
#priors$prior[22] <- "cauchy(0.2,3)" #
priors$prior[24] <- "inv_gamma(2,0.5)" # 


priors$prior[26] <- "inv_gamma(4,1)" # 
priors$prior[28] <- "inv_gamma(3,2)" # 
priors$prior[30] <- "inv_gamma(3,1)" #


priors$prior[32] <- "inv_gamma(6,0.8)" # 
priors$prior[34] <- "inv_gamma(5,1)" # 
priors$prior[36] <- "inv_gamma(4,1)" # 

priors$prior[38] <- "inv_gamma(3,2)" # 

# Run model

model <- brm(y ~ (1|division) + (1|gender)+(1|birthplace) + (1|income) + (1|education) + (1+privhealth|age) + (1|religion) +
               (1|f1) + (1|f2) + (1|f3) +
               swing +
               t2(divinc,divenggap,by=f2,k=4),
             data=df,
             prior=priors,
             family=bernoulli("logit"),
             #inits = 0,
             chains = 2,
             iter = 500,
             sparse = TRUE,
             silent = FALSE,
             cores=2,
             control=list(adapt_delta =0.8,
                          max_treedepth=30))

# Make poststratificstion frame

division  <- sample( div, 1000000, replace=TRUE )

income  <- sample( inc, 1000000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.20,0.20)  )

census.X <- data.frame(division = division,
                       gender = sample( c("male","female"), 1000000, replace=TRUE, prob=c(0.5,0.5)  ),
                       birthplace=sample(c("western","nonwestern"), 1000000, replace=TRUE, prob=c(0.7,0.3)  ),
                       income = income,
                       education=sample( c("edu.1","edu.2","edu.3"), 1000000, replace=TRUE, prob=c(0.4, 0.2, 0.4)  ),
                       age = sample( c("age.1","age.2","age.3","age.4"), 1000000, replace=TRUE, prob=c(0.25, 0.25, 0.25, 0.25)  ),
                       religion=sample( c("relig.1","relig.2","relig.3","relig.4"), 10000, replace=TRUE, prob=c(0.2, 0.2, 0.2, 0.4)  ),
                       f1 = sample( c("f1.1","f1.2","f1.3"), 1000000, replace=TRUE, prob=c(0.3, 0.3, 0.4)  ),
                       f2 = sample( c("f2.1","f2.2","f2.3"), 1000000, replace=TRUE, prob=c(0.3, 0.3, 0.4) ),
                       f3 = sample( c("f3.1","f3.2","f3.3"), 1000000, replace=TRUE, prob=c(0.3, 0.3, 0.4) ),
                       privhealth=as.numeric(sample( c(1,2,3,4,5), 1000000, replace=TRUE, prob=c(0.4, 0.35, 0.15, 0.03,0.02)  ))
)
library(dplyr)
census.X <- left_join(census.X,div.X)

frame <- census.X %>% 
  group_by(division,gender,birthplace,income,education,age,religion,f1,f2,f3,privhealth,swing,divinc,divenggap)%>% 
  summarise(N=n())

# poststratiify

pp <- posterior_predict(model,newdata=frame)

library(tidybayes)

add_predicted_draws(model, newdata=frame, allow_new_levels=TRUE, 
                    n=500, summary=FALSE)
```

With the Bernoulli model the posterior_predict function would work thankfully.

I noticed that the posterior_predict function produced a binary 0 or 1. I was expecting like the posterior_sample function which produces a logit probability and needs to be converted to the scaled inverse-logit link with inv_logit_scaled(x, lb = 0, ub = 1). I know the posterior_sample function extracts the posterior samples for each parameter and I've previously done this with the glmer objects from the lme4 package and I had a while ago done so with the brms objects but had to renamed each of the parameters from brms but there is a lot of hard coding involved. Now I've got a tensor product field smooth which varied by group if the posterior_predict function had an option to predict the logit-scaled probability for a given set of new data. Since I've only seen posterior_linpred with the aforementioned error, would the posterior_linpred function enable me to get around this issue?

**Comment by paul-buerkner** [comment] 2018-08-09 06:57
Thanks for the detailed example. Going forward, please make your examples minimally reproducible so that they only contain code relevant for the error. That way, I don't need to execute so much code to see what's going on. 

I didn't run the code yet, but maybe I see the problem, already. In your model, you write `trials(n)` but it seems as if `frame`, which you pass as `newdata` to `posterior_predict` contains the variable name `N` instead of `n`. What happens if you use

```R
frame <- census.X %>% 
  group_by(division,gender,birthplace,income,education,age,religion,f1,f2,f3,privhealth,swing,divinc,divenggap)%>% 
  summarise(n=n())
```

With regard to computing success probabilities, either use `posterior_linpred(..., transform = TRUE)` or `fitted(...)`.

**Comment by mansillo** [comment] 2018-08-09 08:04
Thanks @paul-buerkner,

I implemented the `posterior_predict` with the variable containing `n` as opposed to `N` and it was successful. 

It now occurs to me that this was not the original error message I was producing which made me create the fake data. I was using my `n` variable in my initial post-stratification frame as a numeric variable which was not an integer since it was the joint probability from an [xgboost](https://xgboost.readthedocs.io/en/latest/) model where I imputed the probability of characteristics into census counts. Since the counts being given to the model were not integers the `resp_trials` function I suspect disagreed since despite `n` being numeric, `n` was [not a whole number](https://www.rdocumentation.org/packages/brms/versions/2.3.1/topics/brmsformula):
```
resp_trials <- function(x) {
  # trials for binomial models
  if (!is.numeric(x)) {
    stop2("Number of trials must be numeric.")
  }
  if (any(!is_wholenumber(x) || x < 1)) {
    stop2("Number of trials must be positive integers.")
  }
  x
}

```
To check this, this ran without error

`frame <- census.X %>% 
  group_by(division,gender,birthplace,income,education,age,religion,f1,f2,f3,privhealth,swing,divinc,divenggap)%>% 
  summarise(n=n())
pp <- posterior_predict(model,newdata=frame)

`

but


`frame <- census.X %>% 
  group_by(division,gender,birthplace,income,education,age,religion,f1,f2,f3,privhealth,swing,divinc,divenggap)%>% 
  summarise(n=n())
frame$n[1] <- frame$n[1]+0.1
pp <- posterior_predict(model,newdata=frame)

`
Produced this error:
`Error: Number of trials must be positive integers.`


The `posterior_predict` function (and for that matter the `posterior_linpred ` function) were designed to check the implied outcomes of the model from the posterior. The number of `trails` is not one of the variables with which to predict the posterior probability but it is a scalar to multiply the predicted outcome by. 

Do you have any recommendations to implement `posterior_predict` and `posterior_linpred` for non-standard binomial post-stratification cases which have counts that are not whole numbers but decimal numbers because these scalars are the result of another model's probabilities being post-stratified onto population counts?

**Comment by paul-buerkner** [comment] 2018-08-09 08:12
You may scompute the expected probabilities by first setting `n = 1` and then multiplying the output of `posterior_linpred(..., transform = TRUE)` by your corresponding approximate sample size.

However, I am not sure how to appropriately sample new responses for this kind of model since it is not longer a generative model. That's not a problem of implementation but of the model you are implementing.

**Comment by paul-buerkner** [comment] 2018-08-09 08:26
That's what you get using my workaround. Since this turned out to be rather a question than a bug in brms, I would like to close this issue. If you have further questions, please ask them on http://discourse.mc-stan.org/.

**Closed by paul-buerkner** 2018-08-09 08:26 UTC
