### ISSUE TITLE
[FR] Ordinal Regression with a Latent Zero-Augmented Beta

### ISSUE THREAD

**Issue by amynang** [paul-buerkner/brms#932] opened 2020-06-23 13:25 UTC
It would be really useful if the approach suggested in [Irvine et al. (2016)](https://link.springer.com/article/10.1007/s13253-016-0265-2#Sec8) "an ordinal beta hurdle model that directly models ordinal category probabilities with a biologically realistic beta-distributed latent variable", could be implemented in brms.

**Comment by hansvancalster** [comment] 2020-06-23 14:00
I happen to have done this before. So, yes, this is already possible. Something along the following lines:

````
 brm(bf(response | cens(censoring, upper) ~ 1, 
                        phi ~ 1,
                        zi ~ 1),
                        family = "zero_inflated_beta",
                        data = data)
````

So you need a dataset that has columns `response`, which contains the lower bound of the cover class, `censoring`, which indicates the kind of censoring ("none", "left", "interval", "right"), and `upper`, which indicates the upper bound of the cover class. For cover class data (to which the paper you refer to applies), the lowest cover class is left censored, intermediate cover classes are interval censored and the highest cover class is right censored when we assume a latent beta distribution.

**Comment by amynang** [comment] 2020-06-23 14:26
@hansvancalster Thanks for the tip and the explanation! I will try this asap.

**Comment by amynang** [comment] 2020-06-24 08:51
@hansvancalster  Now that I have tried your suggestion (it works in the sense that I get results), I wonder if it does what I think it does. I am not familiar with the brms package (I was using the frequentist glmmTMB so far and looked into brms precisely because it supports ordinal regression). I am not sure how what you suggest differs in the end form fitting a discrete response with beta regression, as if it were continuous. Where does the ordinal regression come into this?

**Comment by hansvancalster** [comment] 2020-06-24 09:31
> @hansvancalster Thanks for the tip and the explanation! I will try this asap.
> So to be clear, the 0s in the `response` would get "none" for `censoring`?

yes, that is correct.

> @hansvancalster Now that I have tried your suggestion (it works in the sense that I get results), I wonder if it does what I think it does. I am not familiar with the brms package (I was using the frequentist glmmTMB so far and looked into brms precisely because it supports ordinal regression). I am not sure how what you suggest differs in the end form fitting a discrete numeric response with beta regression, as if it were continuous. Where does the ordinal regression come into this?

The ordinal may sound confusing, because the output you get differs from a proportional odds model (cumulative logit model). That is because the approach directly models the latent zero inflated (=hurdle) beta distribution. So you estimate directly mu, phi and zi parameters (regression coefficients if you add covariates). This differs from a discrete numeric response with beta regression, because in that case you would have to assign one value to a cover class range (for instance, a cover class of 10 - 30%, would be assigned to midpoint 20%), which is wrong because these observations are censored (we observe a range between 10 and 30%) and the brm() formulation I showed acknowledges this (the contribution to the likelihood will be calculated as the difference between the cumulative beta distribution function from 0 to 0.30 and the cumulative beta distribution function from 0 to 0.10).

**Comment by amynang** [comment] 2020-06-24 15:58
@hansvancalster Thanks once again for the clear explanation.

**Comment by paul-buerkner** [comment] 2020-06-24 19:07
So do I understand it correctly, that this issue has been resolved?

**Closed** 2020-06-24 21:34 UTC
