### ISSUE TITLE
Error in `marginal_effects` with an interaction term

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#65] opened 2016-04-14 12:06 UTC
I'm getting an error when I try to generate the marginal effects of an interaction term:

```r
> plt_dat <- marginal_effects(fit, effects = "image_model:comparison_type")
Error in tcrossprod(b, X) : non-conformable arguments
```

I don't have a small reproducible example right now, sorry. I've checked that this term does indeed appear as one of the valid effects in the model.

**Comment by paul-buerkner** [comment] 2016-04-14 12:08
I am having a lecture right now, but I will take a look at it later on today.

**Comment by paul-buerkner** [comment] 2016-04-14 14:43
I am having trouble reproducing the problem. I assume that both predictors as factors, right? 
If so, how many factor levels do they have, and how are the exact names of the levels?

**Comment by tomwallis** [comment] 2016-04-14 14:46
Yep, both levels are factors (image_model has 6 levels, comparison_type has 2). Do you mean the names of the levels in the dataframe or in the fit object? In the fit object they're just numbered:

```r
eta_image_model1:comparison_type1                  1.22      0.31     0.72     1.95        822 1.00
eta_image_model2:comparison_type1                  0.01      0.15    -0.29     0.32       3222 1.00
eta_image_model3:comparison_type1                 -0.16      0.15    -0.44     0.13       1422 1.00
eta_image_model4:comparison_type1                 -0.18      0.15    -0.47     0.12       2366 1.00
eta_image_model5:comparison_type1                 -0.46      0.13    -0.73    -0.20       2405 1.00
```

**Comment by paul-buerkner** [comment] 2016-04-14 14:48
Ok, factor level names are looking fine. I will run more tests. Maybe I can sort it out.

**Comment by paul-buerkner** [comment] 2016-04-14 14:52
Does the following example work for you?

```R
y <- rnorm(90)
x <- factor(rep(1:3, 30))
z <- factor(rep(1:3, each = 30))
dat <- data.frame(y=y, x=x, z=z)

fit <- brm(y~ eta , nonlinear = eta ~ x*z, data = dat,
           prior = set_prior("normal(0,5)", nlpar = "eta"))
marginal_effects(fit)
```

I am wondering why factor names in your data frame are different than the fitted model. Do you use any special coding for the factors? Also, are the two factors fully crossed? That is, are all levels of factor 1 combined with all levels of factor 2?

**Comment by tomwallis** [comment] 2016-04-14 18:45
Hi, the example code worked fine.

Those factors are fully crossed, but there are other factors in the model (being marginalised over in the above code) that are not fully crossed. No special coding for the factors. I presume the levels are different in the fit object for brevity: the factor levels in the data frame are informative (i.e. a bit long) strings. Printing those levels in the summary table would be unwieldy. Does that help?

**Comment by paul-buerkner** [comment] 2016-04-14 22:04
I am afraid, that I am currently not able to reproduce the error. It is unlikely, but maybe it's worth that you install the latest dev version as I potentially have already fixed it. 

Otherwise a reproducible example (with fake data if you want) would really help me. At least, can you show me your full call to the `brm` function and maybe explain which of the predictors are factors?

**Comment by tomwallis** [comment] 2016-04-15 10:37
I just send the data and fit object to your email address (as R binaries; I hope that's ok).

**Comment by paul-buerkner** [comment] 2016-04-15 12:24
Thanks a lot for providing the example! The problem is that (for reasons I currently do not understand) the factor levels in the model are appreviated by numbers, while they appear with their full names in the model.frame and internally generated design matrices. This leads to a mismatch between the fixed effects design matrix and the extracted fixed effects parameters.

I have no idea, why factor levels for the parameters were abbreviated in the first place, because the names are taken specifically from the design matrix, which apparently uses the full level names. When I refit the model with the latest dev version from github, factor levels appear with their full names in the model and `marginal_effects` works as expected. 

Accordingly, I would recommend that you try to refit your model witht the latest dev version using very few iterations just to see if the names are correct in the model and if `marginal_effects` works. If so, you will likely have to refit your model. :-( 

If it is still not working, we will have to figure out why your machine (but not mine) abbreviates the factor levels in the parameter names.

**Comment by tomwallis** [comment] 2016-04-15 12:59
Ok, thanks Paul, I will try that.

**Comment by tomwallis** [comment] 2016-04-15 13:14
Ok, something very strange is going on. I just tried the `marginal_effects` plot again, with the same fit object as I sent you, and it now works. I updated to the new dev version this morning and restarted R after that, but I swear I tried it again (and reproduced the bug) before sending it to you. Also, the levels of the factors still appear with numbers if I print the `fit` object.

I have no idea what's going on. 

I'm also not sure if something is caused because I'm fitting the models on a linux (ubuntu 14.04) workstation and doing the plots on OSX. Both R versions are updated, as is the brms toolbox.

**Comment by paul-buerkner** [comment] 2016-04-15 13:26
No worries, I could also reproduce the bug with your model . 

I think the problem may be some global option regarding factor levels (whether to use names or numbers). If this option is set differently when calling marginal_effects than when fitting the model, the bug occurs. Maybe I can find a work around for this problem so that brms will be independent on the exact parameter names.

**Comment by tomwallis** [comment] 2016-04-15 13:32
The only global option regarding factors that gets set is to code the contrasts as orthogonal sum contrasts: `options(contrasts=c('contr.sum','contr.poly'))  `. Perhaps, if I'm not calling this option when I try to plot the model, it creates problems?

**Comment by paul-buerkner** [comment] 2016-04-15 13:33
yes, that's likely.

**Comment by tomwallis** [comment] 2016-04-15 13:47
Sorry for the headache. I didn't realise the global contrast option would affect plotting outside of the fit process.

Is there a neater way to handle this? Perhaps by setting contrast options in the formula itself rather than globally?

**Comment by paul-buerkner** [comment] 2016-04-15 13:51
I didn't realize it either... I am working on a way to "hard code" the contrasts at fitting time so that the global option will no longer be used afterwards. Unfortunately, this will only apply to new models.

**Closed** 2016-04-15 14:13 UTC
Labels: bug

**Comment by paul-buerkner** [comment] 2016-04-15 14:14
The problem should be fixed now for all models fitted with the new dev version. Thank you very much for taking the time to investigate this problem
