### ISSUE TITLE
unspecified re.form overwriting specified re.formula

### ISSUE THREAD

**Issue by tjmahr** [paul-buerkner/brms#1352] opened 2022-05-12 18:54 UTC
I can't pin-point whether this is a brms issue or a tidybayes issue @mjskay. Basically, if I write `add_epred_draws(data, model, re_formula = NA,)` (note the final comma) the `re_formula` becomes `NULL`. 

I figured out that `brms:::posterior_epred.brms()` will overwrite `re_formula` with `re.form` if it shows up in the call.

```
> brms:::posterior_epred.brmsfit
function (object, newdata = NULL, re_formula = NULL, re.form = NULL, 
    resp = NULL, dpar = NULL, nlpar = NULL, ndraws = NULL, draw_ids = NULL, 
    sort = FALSE, ...) 
{
    cl <- match.call()
    if ("re.form" %in% names(cl)) {
        re_formula <- re.form
    }
...
```

So I think at some point from tidybayes to brms, some strangeness with the dots and the trailing comma messes up the call so that `re.form` shows up. Although the problem results from me calling tidybayes code, I wonder if fixing `brms:::posterior_epred.brmsfit` so that it prefers `re_formula` over `re.form` if both appear in the call will resolve the problem.

A reprex appears below. In the three `mean_qi()` calls, the `NA,` case matches the `NULL` case. This does not happen with `posterior_epred()` called directly. 

``` r
library(tidyverse)
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.17.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
library(tidybayes)
#> 
#> Attaching package: 'tidybayes'
#> The following objects are masked from 'package:brms':
#> 
#>     dstudent_t, pstudent_t, qstudent_t, rstudent_t
library(lme4)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
#> 
#> Attaching package: 'lme4'
#> The following object is masked from 'package:brms':
#> 
#>     ngrps
library(cmdstanr)
#> This is cmdstanr version 0.5.2
#> - CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
#> - CmdStan path: C:/Users/trist/Documents/.cmdstan/cmdstan-2.29.2
#> - CmdStan version: 2.29.2

m <- brm(
  Reaction ~ Days + (1 | Subject),
  sleepstudy, 
  chains = 1,
  backend = "cmdstanr"
)
#> Start sampling
#> Running MCMC with 1 chain...
#> 
#> Chain 1 Iteration:    1 / 2000 [  0%]  (Warmup) 
#> Chain 1 Iteration:  100 / 2000 [  5%]  (Warmup) 
#> Chain 1 Iteration:  200 / 2000 [ 10%]  (Warmup) 
#> Chain 1 Iteration:  300 / 2000 [ 15%]  (Warmup) 
#> Chain 1 Iteration:  400 / 2000 [ 20%]  (Warmup) 
#> Chain 1 Iteration:  500 / 2000 [ 25%]  (Warmup) 
#> Chain 1 Iteration:  600 / 2000 [ 30%]  (Warmup) 
#> Chain 1 Iteration:  700 / 2000 [ 35%]  (Warmup) 
#> Chain 1 Iteration:  800 / 2000 [ 40%]  (Warmup) 
#> Chain 1 Iteration:  900 / 2000 [ 45%]  (Warmup) 
#> Chain 1 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
#> Chain 1 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
#> Chain 1 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
#> Chain 1 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
#> Chain 1 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
#> Chain 1 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
#> Chain 1 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
#> Chain 1 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
#> Chain 1 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
#> Chain 1 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
#> Chain 1 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
#> Chain 1 Iteration: 2000 / 2000 [100%]  (Sampling) 
#> Chain 1 finished in 0.6 seconds.

d <- tibble(Subject = "fake!", Days = 7)


d1 <- d |>  
  add_epred_draws(
    m,
    seed = 1,
    allow_new_levels = TRUE,
    re_formula = NA
  ) |> 
  ggdist::mean_qi() |> 
  mutate(formula = "NA")

d2 <- d |> 
  add_epred_draws(
    m,
    seed = 1,
    allow_new_levels = TRUE,
    re_formula = NA,
  ) |> 
  ggdist::mean_qi() |> 
  mutate(formula = "NA comma")

d3 <- d |> 
  add_epred_draws(
    m,
    seed = 1,
    allow_new_levels = TRUE,
    re_formula = NULL
  ) |> 
  ggdist::mean_qi() |> 
  mutate(formula = "NULL")

bind_rows(d1, d2, d3)
#> # A tibble: 3 × 10
#>   Subject  Days  .row .epred .lower .upper .width .point .interval formula 
#>   <chr>   <dbl> <int>  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>     <chr>   
#> 1 fake!       7     1   324.   303.   344.   0.95 mean   qi        NA      
#> 2 fake!       7     1   325.   244.   397.   0.95 mean   qi        NA comma
#> 3 fake!       7     1   325.   244.   397.   0.95 mean   qi        NULL


posterior_epred(m, d, allow_new_levels = TRUE, re_formula = NA) |> summary()
#>        V1       
#>  Min.   :283.3  
#>  1st Qu.:317.9  
#>  Median :324.7  
#>  Mean   :324.4  
#>  3rd Qu.:330.4  
#>  Max.   :364.1
posterior_epred(m, d, allow_new_levels = TRUE, re_formula = NA,) |> summary()
#>        V1       
#>  Min.   :283.3  
#>  1st Qu.:317.9  
#>  Median :324.7  
#>  Mean   :324.4  
#>  3rd Qu.:330.4  
#>  Max.   :364.1
posterior_epred(m, d, allow_new_levels = TRUE, re_formula = NULL) |> summary()
#>        V1       
#>  Min.   :227.7  
#>  1st Qu.:310.2  
#>  Median :329.4  
#>  Mean   :324.3  
#>  3rd Qu.:344.9  
#>  Max.   :412.0
```

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mjskay** [comment] 2022-05-13 18:31
Yeah, I think this is due to the use of `match.call()` for checking if arguments are present.

Using your model above, I can reproduce the problem on `posterior_epred()` by wrapping it in a function:

```r
f = function(re_formula, ...) {
  set.seed(1234) # for comparing the medians below
  posterior_epred(m, d, allow_new_levels = TRUE, re_formula = re_formula, ...)
}
median(f(NA))
#> [1] 324.7867
median(f(NA,))
#> [1] 327.6226
median(f(NULL))
#> [1] 327.6226
```

A simplified example to show how `match.call()` interacts with dots and missing args:

``` r
g = function(a, b, ...) {
  match.call()
}
f = function(a, ...) {
  g(a = a, ...)
}
# g() called directly, these are equivalent...
g(a = 1)
#> g(a = 1)
g(a = 1,)
#> g(a = 1)

# called via f() with dots, they are not...
f(a = 1)
#> g(a = a)
f(a = 1,)
#> g(a = a, b = ..1)
```

A simple fix might be to change the check to `"re.form" %in% names(cl) && !missing(re.form)`. On the simplified example this works:

``` r
g = function(a, b, ...) {
  "b" %in% names(match.call()) && !missing(b)
}
f = function(a, ...) {
  g(a = a, ...)
}
g(a = 1)
#> [1] FALSE
g(a = 1,)
#> [1] FALSE
f(a = 1)
#> [1] FALSE
f(a = 1,)
#> [1] FALSE
f(a = 1, b = 2)
#> [1] TRUE
```

The alternative fix would be to move the optional arguments to be after the `...` in the definition of the function, then the missing arg cannot be accidentally matched to `re.form` (as `re.form` would no longer be a positional argument):

``` r
g = function(..., a, b) {
  match.call()
}
f = function(a, ...) {
  g(a = a, ...)
}
g(a = 1)
#> g(a = 1)
g(a = 1,)
#> g(, a = 1)
f(a = 1)
#> g(a = a)
f(a = 1,)
#> g(..1, a = a)
```

This is a bigger change, but is beneficial anyway, as it prevents other bugs too, like bugs caused by partial matching on those arguments.

**Comment by paul-buerkner** [comment] 2022-05-16 05:39
Thank you for opening this issue and for the provided insights and ideas to fix! I think I would go with the `"re.form" %in% names(cl) && !missing(re.form)` option as this is the leat invasive for now.

**Comment by paul-buerkner** [comment] 2022-05-16 05:42
This should now be fixed on github.

**Closed by paul-buerkner** 2022-05-16 05:42 UTC
Labels: bug
