### ISSUE TITLE
loo() cannot save the PSIS object when reloo = TRUE

### ISSUE THREAD

**Issue by jkruohon** [paul-buerkner/brms#1117] opened 2021-03-05 16:08 UTC
Data file **mydata** is attached below.

To reproduce the problem, we start by setting priors for our categorical multilevel model:

`mypriors <- prior(normal(0, 4), class = Intercept) + prior(normal(0, 4), class = b) + prior(normal(0, 1), coef = "Word.Dist", dpar = "muB") + prior(normal(0, 1), coef = "Word.Dist", dpar = "muC") + prior(normal(0, 1), coef = "Word.Dist", dpar = "muD") + prior(normal(0, 0.2), coef = "Word.Dist2", dpar = "muB") + prior(normal(0, 0.2), coef = "Word.Dist2", dpar = "muC") + prior(normal(0, 0.2), coef = "Word.Dist2", dpar = "muD") + prior(exponential(2), class = sd, group = "CompLemma", dpar = "muB") + prior(exponential(2), class = sd, group = "CompLemma", dpar = "muC") + prior(exponential(2), class = sd, group = "CompLemma", dpar = "muD") + prior(exponential(2), class = sd, group = "trigger", dpar = "muB") + prior(exponential(2), class = sd, group = "trigger", dpar = "muC") + prior(exponential(2), class = sd, group = "trigger", dpar = "muD")
`

Then we fit our categorical multilevel model. 

`mymod <- brm(dep.var ~ (1 | trigger) + (1 | CompLemma) + Actualized + Agentivity + Animacy + Area + Characterizing + CompLemmalogfreq + Extract + ExtraPose + GenericNP + LexicalStative + NegTrig + NonSyntLic + PluralSubject + polarity + PolySem + r.class + S.Person + should.merge + SubjDef + SubVerbSylC + TensePast + ThatOmit + time.period + TrgPoS + trgType + triggerlogfreq + Voice + Word.Dist + Word.Dist2, family = categorical, data = mydata, seed = 2020, prior = mypriors, warmup = 1000, iter = 3500, cores = 4, control = list(adapt_delta = 0.95))`

Next, we try to create a LOO object for subsequent calculation of model diagnostics based on the LOO fit. Unfortunately, this fails because there are 2 observations with excessively high pareto-k values:

`myloo <- loo(mymod, save_psis = TRUE)`
` Warning message:
Found 2 observations with a pareto_k > 0.7 in model 'mymod'. It is recommended to set 'moment_match = TRUE' in order to perform moment matching for problematic observations.`

We can't do `moment_match = TRUE` now because we didn't save all the parameters when fitting the initial model. However, we should still be able to deal with the problematic observations using `reloo = TRUE`:

`myloo <- loo(mymod, save_psis = TRUE, reloo = TRUE)`
`2 problematic observation(s) found.`
`The model will be refit 2 times.`

`Fitting model 1 out of 2 (leaving out observation 1994)`

`Fitting model 2 out of 2 (leaving out observation 2208)`
`Start sampling`
`Error: passing unknown arguments: save_psis.`
 
This fails because the brms variant of **loo()** appears to be unable to do save_psis and reloo in the same call.

[mydata.txt](https://github.com/paul-buerkner/brms/files/6091563/mydata.txt)

**Comment by paul-buerkner** [comment] 2021-03-05 20:07
Thanks for opening this issue! In the future, please provide a *minimal* reproducible example that does not take so long to run. Since the issue seems to be clear here, it is fine this time. :-)

**Comment by jkruohon** [comment] 2021-03-06 05:34
The difficulty in creating a minimal reproducible example is the need to generate a mock dataset that is simultaneously simple and minimal yet still has problematic observations. Without problematic observations, neither reloo nor moment_match is necessary and so the problem doesn't arise.

I'm glad if the complex reproducible example is useful despite its complexity. :-)

**Comment by paul-buerkner** [comment] 2021-03-09 19:07
Should be fixed now.

**Closed by paul-buerkner** 2021-03-09 19:07 UTC
Labels: bug, post-processing
