### ISSUE TITLE
predict throws invalid covariate matrix

### ISSUE THREAD

**Issue by schmettow** [paul-buerkner/brms#127] opened 2016-09-27 20:25 UTC
Hallo Paul,

with the non-linear mixed-effects model I am working on for studying learning curves, predict(object) throws an error:

> Covariate matrix is invalid

With the contained code and data you can reproduce the problem, I guess.
[brms_predict.zip](https://github.com/paul-buerkner/brms/files/496567/brms_predict.zip)

--Martin

**Comment by paul-buerkner** [comment] 2016-09-27 21:35
Thanks for reporting this bug and for providing a reproducable example. The ultimate problem is that your covariate `trial` is logical, which is not correctly handled in the helper functions of `predict` etc. I will fix this issue or prohibit the use of logical variables in non-linear models. 

Two minor comments regarding your data and script. 1. I see that `trial` only contains `FALSE`. Is this intentional? 2. `fitted` is not an exported object of **brms** since `fitted` is a generic function of the **stats** package.

**Comment by paul-buerkner** [comment] 2016-09-27 22:11
The bug is now fixed in the github version of **brms**. To avoid it in the release version, just code the `trial` covariate as numeric instead of as logical. Thanks again for reporting this problem!

**Closed by paul-buerkner** 2016-09-27 22:11 UTC
Labels: bug
