### ISSUE TITLE
Monotonic predictor messes with correct identification of following predictors in the dataframe

### ISSUE THREAD

**Issue by fusaroli** [paul-buerkner/brms#813] opened 2019-12-20 10:26 UTC
While building a model with a monotonic predictor, I noticed this messes up the ability of brms to identify another (following) predictor. 
e.g.
SymptomVoice_Age_f <- bf(Outcome ~ 0 + language + language : mo(Symptom) + language : mo(Symptom) : AgeS + (1 | gr(ID, by = language)))

gives me an error indicating that the last variable does not exist.

"Error in eval(predvars, data, env) : object 'AgeS' not found"

Specifying data$variable in the formula allows brms to find the variable (but messes up the hypothesis() function later on).

If I remove the mo(variable) in favour of variable, then the issue disappears.

Reproducible gist: https://gist.github.com/fusaroli/64d4b4d85221da026cda274647acfb8d
Data for the gist: https://www.dropbox.com/s/pqkgnjj6y80zryo/temp_data.csv?dl=0

**Comment by paul-buerkner** [comment] 2019-12-20 11:08
The problem is that AgeS only occurs in combination with mo() terms and not independently thereof. I will see how to fix that.

**Comment by paul-buerkner** [comment] 2019-12-20 11:33
Should be fixed now.

**Closed by paul-buerkner** 2019-12-20 11:33 UTC
Labels: bug

**Comment by fusaroli** [comment] 2019-12-20 12:35
yeps, it all works now on different syntaxes as well, thanks!
