### ISSUE TITLE
ridge prior?

### ISSUE THREAD

**Issue by zachmayer** [paul-buerkner/brms#423] opened 2018-05-04 01:44 UTC
I've been playing around with the lasso(1) prior.  Is there an equivalent ridge(1) or glmnet(1) prior I could try too?

Love the package— thanks for making it!

**Comment by paul-buerkner** [comment] 2018-05-04 06:02
I suggest using the `horseshoe` prior instead of `lasso` since the former induces better shrinkage. See `?horseshoe` in brms as well as https://arxiv.org/abs/1707.01694.

With regard to your question, do you have some references for these priors?

**Comment by zachmayer** [comment] 2018-05-04 12:47
@paul-buerkner Thanks for the reference, I will try that out.

Here's the reference I have for ridge vs lasso vs cauchy vs horseshoe: http://ftp.stat.duke.edu/WorkingPapers/08-31.pdf

![image](https://user-images.githubusercontent.com/581590/39628603-90487f10-4f77-11e8-9f4a-0ee87528e0f2.png)

Also, I'm pretty new to bayesian modeling— I've previously been using the glmnet package in R for ridge/lasso/elastic net regression (but in a non-bayesian way).

**Comment by paul-buerkner** [comment] 2018-05-04 18:31
Thanks! I will take a look at the reference. @avehtari do you have any experiences with these sorts of priors?

**Comment by paul-buerkner** [comment] 2018-05-08 22:26
@zachmayer Did you try out the horseshoe prior already? I am hesitant to add special support for the ridge prior or similar priors if there is no clear argument why we should favor them over the horseshoe prior.

**Comment by zachmayer** [comment] 2018-05-09 18:56
I've got a dataset where `glmnet` is giving me slightly more accurate models on my test set than `brm`.  I thought that maybe the elastic net regularization was doing something that worked on this data, but the difference is small.

So far the horseshoe prior doesn't improve my results very much.

**Comment by zachmayer** [comment] 2018-05-10 10:25
Logloss on a test set

**Comment by paul-buerkner** [comment] 2018-05-10 12:00
Do you have a case study for me to try out these priors in comparison?

**Comment by zachmayer** [comment] 2018-05-10 12:46
Yes, I will share the dataset and R code.  Let me clean it up and make it presentable, hahaha

**Comment by paul-buerkner** [comment] 2018-06-25 20:47
With the newly added ability of `stanvars` to add custom parameters to the Stan code written by brms (see #459), hierachical normal priors (or other kinds of normal priors subsumed under "ridge regression") are now possible. I don't think any built-in support is really necessary and thus I am closing this issue.

**Closed by paul-buerkner** 2018-06-25 20:47 UTC
Labels: feature
