### ISSUE TITLE
Feature suggestion: re warning message about some Rhats being NA

### ISSUE THREAD

**Issue by tfjaeger** [paul-buerkner/brms#865] opened 2020-03-20 14:49 UTC
Hi Paul,

The new warning message that some Rhats are NA so that the chains might not have mixed is helpful. I imagine though that it is also confusing to some users since it often occurs when none of the Rhats in the standard (print) output of a brmsfit is NA. E.g., in a complex GLMM looking for NAs will mostly return the entries of the upper triangular of the cholesky matrices (which are always NA). So perhaps the warning could include which of the rhats that *should not* be NA are NA? Or perhaps the rhat function could have a way to filter out those expected NAs? Just a (low priority) idea.

Here is an example output where I think only the first NA is actually informative:

                                                                          L_1[1,1] 
                                                                              NaN 
                                                                         L_1[1,2] 
                                                                              NaN 
                                                                         L_1[1,3] 
                                                                              NaN 
                                                                         L_1[1,4] 
                                                                              NaN 
                                                                         L_1[1,5] 
                                                                              NaN 
                                                                         L_1[1,6] 
                                                                              NaN 
                                                                         L_1[2,1] 
                                                                        1.0000134 
                                                                         L_1[2,2] 
                                                                        0.9998615 
                                                                         L_1[2,3] 
                                                                              NaN 
                                                                         L_1[2,4] 
                                                                              NaN 
                                                                         L_1[2,5] 
                                                                              NaN 
                                                                         L_1[2,6] 
                                                                              NaN 
                                                                         L_1[3,1] 
                                                                        0.9998675 
                                                                         L_1[3,2] 
                                                                        0.9999027 
                                                                         L_1[3,3] 
                                                                        0.9999804 
                                                                         L_1[3,4] 
                                                                              NaN 
                                                                         L_1[3,5] 
                                                                              NaN 
                                                                         L_1[3,6] 
                                                                              NaN 
                                                                         L_1[4,1] 
                                                                        1.0000602 
                                                                         L_1[4,2] 
                                                                        1.0000497 
                                                                         L_1[4,3] 
                                                                        0.9999750 
                                                                         L_1[4,4] 
                                                                        0.9997435 
                                                                         L_1[4,5] 
                                                                              NaN 
                                                                         L_1[4,6] 
                                                                              NaN 
                                                                         L_1[5,1] 
                                                                        0.9999693 
                                                                         L_1[5,2] 
                                                                        1.0000419 
                                                                         L_1[5,3] 
                                                                        1.0001414 
                                                                         L_1[5,4] 
                                                                        1.0001204 
                                                                         L_1[5,5] 
                                                                        0.9997478 
                                                                         L_1[5,6] 
                                                                              NaN 
                                                                         L_1[6,1] 
                                                                        1.0000425 
                                                                         L_1[6,2] 
                                                                        1.0002502 
                                                                         L_1[6,3] 
                                                                        0.9999925 
                                                                         L_1[6,4] 
                                                                        1.0000168 
                                                                         L_1[6,5] 
                                                                        1.0001712 
                                                                         L_1[6,6] 
                                                                        1.0000030

**Comment by paul-buerkner** [comment] 2020-03-20 14:54
This warning stems from rstan. In #864 I have stopped this warning from occuring for the case of the cholesky factor you mentioned. There has been a longer discussion about those NA rhats on discourse I believe but I cannot find it right now. In any case, brms has no control over the details of the warning itself.

**Comment by tfjaeger** [comment] 2020-03-20 15:02
Lightning fast! Thank you. 

(I had read that thread; my point was more about allowing an easy way of filtering out the NAs when one uses rhat(), or even something that reminds less experienced users which NAs are expected. But I understand that this would be very low priority).

**Comment by tfjaeger** [comment] 2020-03-20 19:21
I have now installed the github version (2.12.3) but I still into the same issue:

1) I get the warnings:

```
Warning messages:
1: The largest R-hat is NA, indicating chains have not mixed.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#r-hat 
2: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess 
3: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess 
```

2) The summary of the model indicates no issues (specifically, no R_hats that are NA): 

```
Formula: response ~ 1 + bias * dist * (step.1 + step.2) + (1 + bias * dist * (step.1 + step.2) | subject) + (1 + dist * (step.1 + step.2) | item) 
   Data: d (Number of observations: 2469) 
Samples: 4 chains, each with iter = 4000; warmup = 2500; thin = 1;
         total post-warmup samples = 6000

Group-Level Effects: 
~item (Number of levels: 16) 
                                                 Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)                                        0.49      0.19     0.13     0.91 1.00     1797     1354
sd(distfarvs.near)                                   1.44      0.54     0.43     2.59 1.00     1406      696
sd(step.1)                                           1.05      0.73     0.05     2.71 1.00     1675     2135
sd(step.2)                                           0.74      0.51     0.04     1.93 1.00     1203     2306
sd(distfarvs.near:step.1)                            4.73      1.92     1.27     8.92 1.00     1293     1563
sd(distfarvs.near:step.2)                            4.40      1.39     2.03     7.52 1.00     1680     2378
cor(Intercept,distfarvs.near)                        0.17      0.31    -0.46     0.72 1.00     2557     3329
cor(Intercept,step.1)                               -0.08      0.36    -0.73     0.63 1.00     5148     4603
cor(distfarvs.near,step.1)                          -0.10      0.36    -0.74     0.62 1.00     4195     4799
cor(Intercept,step.2)                                0.10      0.37    -0.63     0.75 1.00     4372     4178
cor(distfarvs.near,step.2)                           0.03      0.36    -0.67     0.70 1.00     4561     4511
cor(step.1,step.2)                                   0.08      0.38    -0.66     0.75 1.00     2851     4169
cor(Intercept,distfarvs.near:step.1)                -0.15      0.31    -0.72     0.48 1.00     2699     2963
cor(distfarvs.near,distfarvs.near:step.1)           -0.04      0.31    -0.63     0.56 1.00     2811     3872
cor(step.1,distfarvs.near:step.1)                    0.11      0.35    -0.59     0.73 1.00     1783     3383
cor(step.2,distfarvs.near:step.1)                   -0.07      0.37    -0.74     0.65 1.00     1496     2658
cor(Intercept,distfarvs.near:step.2)                -0.01      0.30    -0.59     0.57 1.00     2052     3373
cor(distfarvs.near,distfarvs.near:step.2)            0.12      0.32    -0.55     0.66 1.00     2211     2900
cor(step.1,distfarvs.near:step.2)                   -0.19      0.36    -0.80     0.55 1.00     1415     2532
cor(step.2,distfarvs.near:step.2)                    0.10      0.36    -0.60     0.73 1.00     1768     3016
cor(distfarvs.near:step.1,distfarvs.near:step.2)    -0.14      0.31    -0.71     0.46 1.00     2141     4059

~subject (Number of levels: 20) 
                                                                         Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)                                                                1.13      0.25     0.72     1.71 1.00     2364     3259
sd(biasS.vs.SH)                                                              0.74      0.31     0.13     1.38 1.00     1800     1268
sd(distfarvs.near)                                                           0.32      0.20     0.02     0.79 1.00     2037     2979
sd(step.1)                                                                   2.18      0.73     0.97     3.82 1.00     2321     2576
sd(step.2)                                                                   2.14      0.63     1.06     3.52 1.00     1867     2433
sd(biasS.vs.SH:distfarvs.near)                                               0.46      0.34     0.02     1.26 1.00     2758     2330
sd(biasS.vs.SH:step.1)                                                       0.97      0.76     0.03     2.82 1.00     3432     3287
sd(biasS.vs.SH:step.2)                                                       1.69      0.96     0.11     3.71 1.00     1128     1837
sd(distfarvs.near:step.1)                                                    1.34      0.97     0.06     3.58 1.00     2733     2775
sd(distfarvs.near:step.2)                                                    0.58      0.46     0.02     1.72 1.00     2654     2438
sd(biasS.vs.SH:distfarvs.near:step.1)                                        1.98      1.51     0.08     5.58 1.00     3146     2882
sd(biasS.vs.SH:distfarvs.near:step.2)                                        1.22      0.90     0.05     3.36 1.00     2709     1642
cor(Intercept,biasS.vs.SH)                                                  -0.11      0.24    -0.55     0.37 1.00     4832     4860
cor(Intercept,distfarvs.near)                                               -0.15      0.26    -0.62     0.39 1.00     6000     4922
cor(biasS.vs.SH,distfarvs.near)                                              0.01      0.27    -0.51     0.53 1.00     5524     4280
cor(Intercept,step.1)                                                       -0.23      0.23    -0.65     0.22 1.00     3994     4604
cor(biasS.vs.SH,step.1)                                                      0.04      0.25    -0.44     0.52 1.00     2735     4037
cor(distfarvs.near,step.1)                                                   0.16      0.27    -0.40     0.64 1.00     2254     3142
cor(Intercept,step.2)                                                        0.12      0.22    -0.32     0.52 1.00     3533     4392
cor(biasS.vs.SH,step.2)                                                     -0.02      0.24    -0.49     0.45 1.00     2436     3685
cor(distfarvs.near,step.2)                                                  -0.04      0.26    -0.54     0.47 1.00     1913     3262
cor(step.1,step.2)                                                          -0.20      0.23    -0.63     0.27 1.00     2705     4013
cor(Intercept,biasS.vs.SH:distfarvs.near)                                    0.01      0.27    -0.51     0.52 1.00     7427     4189
cor(biasS.vs.SH,biasS.vs.SH:distfarvs.near)                                 -0.04      0.27    -0.56     0.50 1.00     6997     4589
cor(distfarvs.near,biasS.vs.SH:distfarvs.near)                              -0.02      0.28    -0.54     0.53 1.00     5505     4597
cor(step.1,biasS.vs.SH:distfarvs.near)                                       0.02      0.27    -0.52     0.54 1.00     6595     4844
cor(step.2,biasS.vs.SH:distfarvs.near)                                       0.06      0.28    -0.48     0.57 1.00     6407     4791
cor(Intercept,biasS.vs.SH:step.1)                                            0.01      0.27    -0.51     0.53 1.00     7369     4639
cor(biasS.vs.SH,biasS.vs.SH:step.1)                                          0.01      0.28    -0.53     0.54 1.00     7241     4553
cor(distfarvs.near,biasS.vs.SH:step.1)                                      -0.01      0.28    -0.53     0.54 1.00     6458     4461
cor(step.1,biasS.vs.SH:step.1)                                              -0.01      0.28    -0.53     0.51 1.00     6497     4748
cor(step.2,biasS.vs.SH:step.1)                                              -0.06      0.28    -0.60     0.48 1.00     6496     4397
cor(biasS.vs.SH:distfarvs.near,biasS.vs.SH:step.1)                          -0.02      0.28    -0.55     0.52 1.00     4901     4927
cor(Intercept,biasS.vs.SH:step.2)                                            0.18      0.25    -0.34     0.62 1.00     4911     4258
cor(biasS.vs.SH,biasS.vs.SH:step.2)                                          0.07      0.27    -0.47     0.57 1.00     3690     4070
cor(distfarvs.near,biasS.vs.SH:step.2)                                       0.05      0.27    -0.48     0.56 1.00     4013     4247
cor(step.1,biasS.vs.SH:step.2)                                               0.03      0.26    -0.46     0.52 1.00     4534     4585
cor(step.2,biasS.vs.SH:step.2)                                              -0.18      0.26    -0.65     0.37 1.00     3436     4454
cor(biasS.vs.SH:distfarvs.near,biasS.vs.SH:step.2)                          -0.00      0.27    -0.54     0.53 1.00     4353     4549
cor(biasS.vs.SH:step.1,biasS.vs.SH:step.2)                                   0.04      0.28    -0.50     0.55 1.00     3965     4961
cor(Intercept,distfarvs.near:step.1)                                         0.03      0.26    -0.49     0.52 1.00     7428     4554
cor(biasS.vs.SH,distfarvs.near:step.1)                                       0.03      0.27    -0.50     0.53 1.00     6137     4835
cor(distfarvs.near,distfarvs.near:step.1)                                    0.02      0.28    -0.51     0.55 1.00     5742     4852
cor(step.1,distfarvs.near:step.1)                                           -0.04      0.27    -0.54     0.48 1.00     5703     4773
cor(step.2,distfarvs.near:step.1)                                           -0.13      0.27    -0.62     0.40 1.00     5563     4696
cor(biasS.vs.SH:distfarvs.near,distfarvs.near:step.1)                       -0.07      0.28    -0.59     0.48 1.00     4150     4825
cor(biasS.vs.SH:step.1,distfarvs.near:step.1)                               -0.00      0.27    -0.53     0.52 1.00     4451     4733
cor(biasS.vs.SH:step.2,distfarvs.near:step.1)                                0.02      0.27    -0.51     0.54 1.00     4925     4475
cor(Intercept,distfarvs.near:step.2)                                        -0.00      0.28    -0.54     0.52 1.00     6453     4762
cor(biasS.vs.SH,distfarvs.near:step.2)                                       0.05      0.27    -0.48     0.57 1.00     6472     4336
cor(distfarvs.near,distfarvs.near:step.2)                                    0.07      0.28    -0.48     0.60 1.00     5940     4650
cor(step.1,distfarvs.near:step.2)                                            0.00      0.28    -0.53     0.54 1.00     6397     5096
cor(step.2,distfarvs.near:step.2)                                           -0.03      0.28    -0.56     0.50 1.00     6365     4941
cor(biasS.vs.SH:distfarvs.near,distfarvs.near:step.2)                       -0.01      0.28    -0.54     0.53 1.00     4611     4474
cor(biasS.vs.SH:step.1,distfarvs.near:step.2)                                0.01      0.27    -0.51     0.54 1.00     4260     4525
cor(biasS.vs.SH:step.2,distfarvs.near:step.2)                               -0.03      0.28    -0.56     0.51 1.00     5036     5099
cor(distfarvs.near:step.1,distfarvs.near:step.2)                             0.02      0.28    -0.52     0.55 1.00     4082     4969
cor(Intercept,biasS.vs.SH:distfarvs.near:step.1)                            -0.07      0.27    -0.59     0.47 1.00     7850     4585
cor(biasS.vs.SH,biasS.vs.SH:distfarvs.near:step.1)                           0.06      0.28    -0.48     0.58 1.00     7008     4400
cor(distfarvs.near,biasS.vs.SH:distfarvs.near:step.1)                        0.02      0.28    -0.49     0.55 1.00     6106     5054
cor(step.1,biasS.vs.SH:distfarvs.near:step.1)                                0.06      0.27    -0.48     0.56 1.00     6660     4464
cor(step.2,biasS.vs.SH:distfarvs.near:step.1)                               -0.05      0.27    -0.55     0.48 1.00     6772     3995
cor(biasS.vs.SH:distfarvs.near,biasS.vs.SH:distfarvs.near:step.1)            0.00      0.28    -0.55     0.54 1.00     4255     4631
cor(biasS.vs.SH:step.1,biasS.vs.SH:distfarvs.near:step.1)                    0.01      0.27    -0.53     0.53 1.00     3894     4553
cor(biasS.vs.SH:step.2,biasS.vs.SH:distfarvs.near:step.1)                   -0.04      0.28    -0.57     0.48 1.00     4732     4833
cor(distfarvs.near:step.1,biasS.vs.SH:distfarvs.near:step.1)                 0.02      0.28    -0.52     0.55 1.00     4308     5001
cor(distfarvs.near:step.2,biasS.vs.SH:distfarvs.near:step.1)                 0.00      0.28    -0.53     0.53 1.00     3951     4682
cor(Intercept,biasS.vs.SH:distfarvs.near:step.2)                            -0.08      0.27    -0.58     0.45 1.00     7688     4629
cor(biasS.vs.SH,biasS.vs.SH:distfarvs.near:step.2)                           0.02      0.27    -0.51     0.53 1.00     6428     4413
cor(distfarvs.near,biasS.vs.SH:distfarvs.near:step.2)                        0.04      0.28    -0.51     0.56 1.00     5739     4487
cor(step.1,biasS.vs.SH:distfarvs.near:step.2)                               -0.01      0.27    -0.53     0.50 1.00     6778     5017
cor(step.2,biasS.vs.SH:distfarvs.near:step.2)                                0.00      0.28    -0.55     0.53 1.00     6804     4994
cor(biasS.vs.SH:distfarvs.near,biasS.vs.SH:distfarvs.near:step.2)            0.04      0.28    -0.50     0.57 1.00     4687     4903
cor(biasS.vs.SH:step.1,biasS.vs.SH:distfarvs.near:step.2)                   -0.02      0.28    -0.55     0.53 1.00     4533     4927
cor(biasS.vs.SH:step.2,biasS.vs.SH:distfarvs.near:step.2)                   -0.01      0.28    -0.53     0.54 1.00     5387     4801
cor(distfarvs.near:step.1,biasS.vs.SH:distfarvs.near:step.2)                 0.02      0.28    -0.52     0.53 1.00     4531     4748
cor(distfarvs.near:step.2,biasS.vs.SH:distfarvs.near:step.2)                -0.02      0.28    -0.55     0.52 1.00     3891     4711
cor(biasS.vs.SH:distfarvs.near:step.1,biasS.vs.SH:distfarvs.near:step.2)     0.01      0.28    -0.52     0.54 1.00     3744     4561

Population-Level Effects: 
                                  Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept                             0.49      0.39    -0.28     1.25 1.00     1356     2266
biasS.vs.SH                           1.80      0.48     0.87     2.77 1.00     2526     3510
distfarvs.near                        0.64      0.51    -0.39     1.66 1.00     2725     3404
step.1                               -9.87      1.07   -12.13    -7.89 1.00     1768     3655
step.2                                2.79      0.88     1.01     4.54 1.00     1973     3119
biasS.vs.SH:distfarvs.near           -0.59      0.90    -2.41     1.19 1.00     2655     3321
biasS.vs.SH:step.1                    0.92      1.24    -1.44     3.47 1.00     3418     3306
biasS.vs.SH:step.2                    0.77      1.11    -1.38     3.01 1.00     3102     3849
distfarvs.near:step.1                -0.99      1.45    -3.86     1.84 1.00     3860     3628
distfarvs.near:step.2                 1.64      1.34    -0.90     4.30 1.00     3728     3968
biasS.vs.SH:distfarvs.near:step.1     1.86      2.35    -2.42     7.02 1.00     4797     4045
biasS.vs.SH:distfarvs.near:step.2     0.34      2.05    -3.57     4.57 1.00     4904     3755

Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
```
There are, of course, NAs for the parameters associated with the Cholesky factor L of the random effects covs, but these are all the elements of the L that are expected to have R_hats that are NA (see Ben Goodrich's comment on discourse, https://discourse.mc-stan.org/t/nas-in-rhats-of-cholesky-factor-but-not-sd-or-cor-in-multi-level-bernoulli-model/13766/4):

```
> r = rhat(m)
> r[which(is.na(r))]
  L_1[1,1]   L_1[1,2]   L_1[1,3]   L_1[1,4]   L_1[1,5]   L_1[1,6]   L_1[2,3]   L_1[2,4]   L_1[2,5]   L_1[2,6]   L_1[3,4]   L_1[3,5]   L_1[3,6] 
       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN 
  L_1[4,5]   L_1[4,6]   L_1[5,6]   L_2[1,1]   L_2[1,2]   L_2[1,3]   L_2[1,4]   L_2[1,5]   L_2[1,6]   L_2[1,7]   L_2[1,8]   L_2[1,9]  L_2[1,10] 
       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN 
 L_2[1,11]  L_2[1,12]   L_2[2,3]   L_2[2,4]   L_2[2,5]   L_2[2,6]   L_2[2,7]   L_2[2,8]   L_2[2,9]  L_2[2,10]  L_2[2,11]  L_2[2,12]   L_2[3,4] 
       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN 
  L_2[3,5]   L_2[3,6]   L_2[3,7]   L_2[3,8]   L_2[3,9]  L_2[3,10]  L_2[3,11]  L_2[3,12]   L_2[4,5]   L_2[4,6]   L_2[4,7]   L_2[4,8]   L_2[4,9] 
       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN 
 L_2[4,10]  L_2[4,11]  L_2[4,12]   L_2[5,6]   L_2[5,7]   L_2[5,8]   L_2[5,9]  L_2[5,10]  L_2[5,11]  L_2[5,12]   L_2[6,7]   L_2[6,8]   L_2[6,9] 
       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN 
 L_2[6,10]  L_2[6,11]  L_2[6,12]   L_2[7,8]   L_2[7,9]  L_2[7,10]  L_2[7,11]  L_2[7,12]   L_2[8,9]  L_2[8,10]  L_2[8,11]  L_2[8,12]  L_2[9,10] 
       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN 
 L_2[9,11]  L_2[9,12] L_2[10,11] L_2[10,12] L_2[11,12] 
       NaN        NaN        NaN        NaN        NaN 
```
So, isn't this a case where the warning shouldn't be shown (if possible)? Or perhaps this is considered an issue of rstan?

**Comment by paul-buerkner** [comment] 2020-03-20 19:59
Please provide a minimal reproducible for the model.

**Comment by tfjaeger** [comment] 2020-03-20 21:42
Here's a dropbox link to the data: https://www.dropbox.com/s/zzsglbxosdxop07/TEMP-data.Rda?dl=0

```
load("TEMP-data.Rda")

library(brms)

model_prior <- c(
  prior(student_t(3,0,2.5), class = b),
  prior(cauchy(0,5), class = sd),
  prior(lkj(1), class = cor))

b = brm(
  response ~ 1 + bias * dist * (step.1 + step.2) + 
    (1 + bias * dist * (step.1 + step.2) | subject) + 
    (1 + dist * (step.1 + step.2) | item),
  data = df.sp,
  family = bernoulli,
  save_all_pars = T,
  chains = 4, 
  cores = 4,
  warmup = 2500,
  iter = 4000
)
```

Without save_all_pars there is not warning. With safe_all_pars = T, there is the NA R_hat warning. I'm using brms 2.12.3.

**Comment by paul-buerkner** [comment] 2020-03-21 14:31
When fitting the model, the described warning pops up but this happens directly from within Rstan and cannot be controlled by brms. However, it does not pop up when running the summary method because of the latest changes I made to brms. Closing this issue now.

**Closed by paul-buerkner** 2020-03-21 14:31 UTC
