### ISSUE TITLE
Truncated distributions

### ISSUE THREAD

**Issue by BERENZ** [paul-buerkner/brms#5] opened 2015-10-03 15:32 UTC
It would be nice if brms would allow to specify truncation for a specified distribution. Stan reference manual specify it in the following way, where L is lower and U is upper bound.

```
 data {
      int<lower=0> N;
      real U;
      real L;
      real<lower=L,upper=U> y[N];
    }
    parameters {
real mu;
      real<lower=0> sigma;
    }
    model {
      for (n in 1:N)
        y[n] ~ normal(mu,sigma) T[L,U];
    }

```

**Comment by paul-buerkner** [comment] 2015-10-03 23:27
That's a great idea!

I just pushed a commit to github providing initial support for truncated models. 

Truncation can be specified directly within the formula argument. To truncate the distribution between, say, 0 and 100 you can use formula = response | trunc(lb = 0, ub = 100) ~ predictors. Of course, you can omit the first or second argument in trunc to create models that are only truncated at one side.

I did not update any S3 methods yet so that the outputs of predict, logLik, etc. will be incorrect for truncated models. This should get fixed in the next couple of days.

**Comment by BERENZ** [comment] 2015-10-04 06:46
Thanks! In addition, I have found note in Stan reference manual "Stan does not (yet) support vectorization of distribution functions with truncation" (p.272, 2.8.0).

**Comment by paul-buerkner** [comment] 2015-10-04 09:16
For full functionality of truncated models, the following things still need to be done:
- [ ] update logLik
- [ ] update predict
- [ ] update fitted
- [ ] write stan functions inverse_gaussian_cdf_log and inverse_gaussian_ccdf_log

**Comment by paul-buerkner** [comment] 2015-10-05 21:46
I have made most of the necessary changes now. 

Currently, the fitted method only works with truncated normal models as the truncated mean is easy to calculate in this case. I hope to also find formulas for the truncated means of other distributions.

If you have time, I would be very grateful if you could fit some truncated models with brms and check if the results appear reasonable to you.

**Comment by paul-buerkner** [comment] 2015-10-05 22:00
I forgot to explain how to specifiy truncated models...

You can use a formula of the form
response | trunc(lb = NUMBER, ub = NUMBER) ~ predictors
to define lower and upper bound of the truncted distribution.

**Comment by BERENZ** [comment] 2015-10-06 05:56
Thanks! I will check it out today. 

However, this is what I've got after installing through github. A poisson model is compiling and estimating during the installation. :) 

```
> devtools::install_github('paul-buerkner/brms')
Downloading GitHub repo paul-buerkner/brms@master
Installing brms
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/zv/md_yv0r16q7btfjq3frjjscc0000gn/T/RtmplgLOXf/devtools25cc35a35e1c/paul-buerkner-brms-cac1493'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

* installing *source* package ‘brms’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Compiling the C++ model

SAMPLING FOR MODEL 'poisson(log) brms-model' NOW (CHAIN 1).

Chain 1, Iteration:  1 / 50 [  2%]  (Warmup)
Chain 1, Iteration:  5 / 50 [ 10%]  (Warmup)
Chain 1, Iteration: 10 / 50 [ 20%]  (Warmup)
Chain 1, Iteration: 11 / 50 [ 22%]  (Sampling)
Chain 1, Iteration: 15 / 50 [ 30%]  (Sampling)
Chain 1, Iteration: 20 / 50 [ 40%]  (Sampling)
Chain 1, Iteration: 25 / 50 [ 50%]  (Sampling)
Chain 1, Iteration: 30 / 50 [ 60%]  (Sampling)
Chain 1, Iteration: 35 / 50 [ 70%]  (Sampling)
Chain 1, Iteration: 40 / 50 [ 80%]  (Sampling)
Chain 1, Iteration: 45 / 50 [ 90%]  (Sampling)
Chain 1, Iteration: 50 / 50 [100%]  (Sampling)
#  Elapsed Time: 0.001414 seconds (Warm-up)
#                0.014879 seconds (Sampling)
#                0.016293 seconds (Total)


SAMPLING FOR MODEL 'poisson(log) brms-model' NOW (CHAIN 2).

Chain 2, Iteration:  1 / 50 [  2%]  (Warmup)
Chain 2, Iteration:  5 / 50 [ 10%]  (Warmup)
Chain 2, Iteration: 10 / 50 [ 20%]  (Warmup)
Chain 2, Iteration: 11 / 50 [ 22%]  (Sampling)
Chain 2, Iteration: 15 / 50 [ 30%]  (Sampling)
Chain 2, Iteration: 20 / 50 [ 40%]  (Sampling)
Chain 2, Iteration: 25 / 50 [ 50%]  (Sampling)
Chain 2, Iteration: 30 / 50 [ 60%]  (Sampling)
Chain 2, Iteration: 35 / 50 [ 70%]  (Sampling)
Chain 2, Iteration: 40 / 50 [ 80%]  (Sampling)
Chain 2, Iteration: 45 / 50 [ 90%]  (Sampling)
Chain 2, Iteration: 50 / 50 [100%]  (Sampling)
#  Elapsed Time: 0.002171 seconds (Warm-up)
#                0.31114 seconds (Sampling)
#                0.313311 seconds (Total)

** help
*** installing help indices
** building package indices
** installing vignettes
   ‘brms.ltx’ 
** testing if installed package can be loaded
* DONE (brms)
```

**Comment by BERENZ** [comment] 2015-10-06 06:28
For a small area model, with known standard errors i've got error. 

```
library(sae)
data(milk)

> res_model <- brm(formula = yi | se(SD) | trunc(lb=0,ub=1.5) ~ MajorArea + (1|SmallArea),
+ data = milk,
+ family = 'gaussian' )
Compiling the C++ model
Error in rstan::stanc(model_code = x$model, model_name = paste0(family,  : 
  failed to parse Stan model 'gaussian(identity) brms-model' with error message:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Parameters in truncated distributions must be univariate.
  Found parameter expression: sigma
  with non-univariate type: real[]

ERROR at line 42

 40:      # likelihood contribution 
 41:      for (n in 1:N) { 
 42:        Y[n] ~ normal(eta[n], sigma) T[lb, ub]; 
                                                   ^
 43:      } 

```

This is due to vectorisation problem for sigma, therefore it should be, in that case:

```
for (n in 1:N) { 
    Y[n] ~ normal(eta[n], sigma[n]) T[lb, ub]; 
} 
```

**Comment by paul-buerkner** [comment] 2015-10-06 13:04
Thanks! I forgot to ensure compatibility with user-defined standard errors. This should be fixed now.

Compiling a model while building the package is necessary to run reasonable automated unit tests on the S3 methods. However, this is mainly relevant for CRAN releases and there is actually no need to have it on Github. So I just commented out the revelant code. ;-)

**Comment by BERENZ** [comment] 2015-10-06 13:23
I've got this…

```
> res_model <- brm(formula = yi | se(SD) | trunc(lb=0,ub=1.5) ~ MajorArea + (1|SmallArea),
+                  data = milk,
+                  family = 'gaussian' )
Compiling the C++ model

SAMPLING FOR MODEL 'gaussian(identity) brms-model' NOW (CHAIN 1).
…..
#  Elapsed Time: 1.7793 seconds (Warm-up)
#                1.29714 seconds (Sampling)
#                3.07644 seconds (Total)

SAMPLING FOR MODEL 'gaussian(identity) brms-model' NOW (CHAIN 2)
…..
#  Elapsed Time: 1.57489 seconds (Warm-up)
#                1.26101 seconds (Sampling)
#                2.8359 seconds (Total)

> fitted(res_model)
Error in fitted_response(object, eta = mu, data = data) : 
  dims [product 129000] do not match the length of object [0]
```

**Comment by paul-buerkner** [comment] 2015-10-06 15:11
Fixed. Again, it was a compatibility issue with user-defined standard errors. I should have this tested more thoroughly...

I have checked all S3 methods again and found no further errors. Hopefully, everything works as expected now.

**Comment by BERENZ** [comment] 2015-10-06 16:46
I've got :(

```
> library(brms)
Error in get(method, envir = home) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/brms/R/brms.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘brms’
```

**Comment by paul-buerkner** [comment] 2015-10-06 16:54
Hmm, installing from Gihub works for me. I think this is caused by trying to install brms while it already has been loaded (this may happen for many packages). I would suggest that you remove the current installation of brms, restart R and then install it again.

**Comment by BERENZ** [comment] 2015-10-06 17:18
Yes, that's right. It works now. :)

**Comment by paul-buerkner** [comment] 2015-10-08 13:38
Great! Since all S3 methods are working now with truncated models, I will close this issue.

@BERENZ Many thanks for the idea of implementing these models and for the testing! :-)

**Closed by paul-buerkner** 2015-10-08 13:38 UTC

**Comment by BERENZ** [comment] 2015-10-08 17:33
@paul-buerkner thanks! I'm happy that I could help :) 
btw. maybe you can also add an issue concerning spatial models as for ARMA residuals?

**Comment by ssalimi** [comment] 2020-05-27 04:29
Dear Paul,
Is there truncation with ordinal response and predictors? 
I need to apply truncation and missingness in my analyses, and I am using your monotonic effect in brms for an ordinal response and predictors. Please kindly let me know. 
Thanks,

**Comment by paul-buerkner** [comment] 2020-05-27 07:11
Truncation is not yet possible for ordinal responses.

**Comment by tcaspi** [comment] 2024-09-12 23:37
Dear Paul,

Is it possible to use truncation with the skew_normal() family? I want to set a lower bound of zero. At the moment, my model will not converge if I include trunc(lb=0) to the response. Thanks!
