### ISSUE TITLE
Within-chain parallelization not working with negative binomial likelihood

### ISSUE THREAD

**Issue by afni-gangc** [paul-buerkner/brms#1047] opened 2020-11-22 02:26 UTC
With no within-chain parallelization, a count dataset worked fine with negative binomial likelihood. However, even with the most recent brms version on github, it threw the following error with within-chain parallelization:

```
brm(y ~ grp+offset(log(X))+(1|cell), data=dat, family = negbinomial(), chains = 4, iter=1000, backend = “cmdstanr”, threads = threading(6))

Compiling Stan program…
Start sampling
Running MCMC with 4 chains, at most 24 in parallel, with 6 thread(s) per chain…

Chain 1 Exception: Exception: neg_binomial_2_log_glm_lpmf: Vector of dependent variables has dimension = 1088, expecting dimension = 1087; a function was called with arguments of different scalar, array, vector, or matrix types, and they were not consistently sized; all arguments must be scalars or multidimensional values of the same shape. (in ‘/tmp/Rtmp37G3Ph/model-2ab8608dabbb.stan’, line 40, column 4 to column 87) (in ‘/tmp/Rtmp37G3Ph/model-2ab8608dabbb.stan’, line 40, column 4 to column 87)
…
Warning: Chain 1 finished unexpectedly!
Warning: Chain 2 finished unexpectedly!
Warning: Chain 3 finished unexpectedly!
Warning: Chain 4 finished unexpectedly!

Warning: Use read_cmdstan_csv() to read the results of the failed chains.

Error in rstan::read_stan_csv(out$output_files()) :
csvfiles does not contain any CSV file name
Calls: brm … eval2 -> eval -> eval -> .fun -> .fit_model ->

In addition: Warning messages:

1: All chains finished unexpectedly!
2: No chains finished successfully. Unable to retrieve the fit.

Execution halted
```

**Comment by paul-buerkner** [comment] 2020-11-22 08:25
Can you please provide a minimal reproducible example?

afni-gangc <notifications@github.com> schrieb am So., 22. Nov. 2020, 03:26:

**Comment by afni-gangc** [comment] 2020-11-22 11:33
Try this:

```
dat <- read.table('https://afni.nimh.nih.gov/sscc/staff/gangc/pub/data.txt', header = TRUE)
options(contrasts = c("contr.sum", "contr.poly"))
library('brms')
require('cmdstanr')
set_cmdstan_path('~/cmdstan')
options(mc.cores = parallel::detectCores())
fm <- brm(Y ~ group+ offset(log(time))+(1|subj)+(group|cell), data=dat, family = negbinomial(), chains = 4, iter=1000, backend = "cmdstanr", threads = threading(6))

```

**Comment by paul-buerkner** [comment] 2020-11-25 08:43
The example you provided starts sampling for me. But the error seems to be related to one observation being off for some reason (as per line `Chain 1 Exception: Exception: neg_binomial_2_log_glm_lpmf: Vector of dependent variables has dimension = 1088, expecting dimension = 1087`). I am not sure what is happening there since I cannot reproduce your problem on my machine.

**Comment by paul-buerkner** [comment] 2020-11-25 08:45
@wds15 do you have any idea why slicing in threading could be off by 1 value?

**Comment by wds15** [comment] 2020-11-25 10:03
It should really not be off by 1. Can you run this model without reduce_sum, but with the partial sum function which you call maybe 4 times? So chunk the data into 4 ideally unequal chunks and run the program.

If that also fails, I can look in more detail.

**Comment by rok-cesnovar** [comment] 2020-11-25 10:05
What is weirder is that we can not reproduce. I also tried running [this](https://github.com/paul-buerkner/brms/issues/1047#issuecomment-731733954) and it runs fine.

**Comment by afni-gangc** [comment] 2020-11-25 13:58
Originally the error occurred on a computer (Fedora 29, 'brms' version 2.14.4; R version 3.6.1). Then I grab brms 2.14.5 from github per suggestion from @rok-cesnovar, but the problem remains when I run it again.

Now I tried the same model on a different computer (Fedora 29; 'brms' version 2.14.4; R version 3.6.1), and it worked fine. So it's something specific to the first computer?

**Comment by wds15** [comment] 2020-11-25 14:45
The example problem runs for me also just fine.

Maybe faulty RAM?

**Comment by afni-gangc** [comment] 2020-11-25 14:58
If it's a faulty RAM, would it manifest the same problem whenever I use within-chain parallelization? I just tried a different dataset with a Gaussian likelihood on that computer, it worked fine.

**Comment by wds15** [comment] 2020-11-25 16:37
I really do not know, but to me this looks as if the problem is this computer and not anything else.

**Comment by paul-buerkner** [comment] 2020-11-25 19:38
Thank you all for investigating! I will close this issue now but feel free to reopin it if you come across a case that reproduces on multiple machines.

**Closed by paul-buerkner** 2020-11-25 19:38 UTC
Labels: bug

**Comment by wds15** [comment] 2020-11-25 20:38
One more thought: what about different seeds on these machines which are faulty? I think closing the issue for now makes sense though.

**Comment by afni-gangc** [comment] 2020-11-27 18:20
Thanks everyone for looking into this! I really appreciate it.

Likely some specific issue with that computer. I just tried zero_inflated_negbinomial on that computer, and came up with a similar error.

**Comment by afni-gangc** [comment] 2021-01-26 20:18
FYI - After CmdStan was updated to version 2.26.0, the issue seems to have been dissolved.

**Comment by paul-buerkner** [comment] 2021-01-26 20:30
Brilliant, thank you!
