### ISSUE TITLE
Consider implementing covariance regressions

### ISSUE THREAD

**Issue by shannonajw** [paul-buerkner/brms#805] opened 2019-12-11 20:42 UTC
Distributional models are already well-implemented in brms (models allowing prediction of mean and variance parameters). Multivariate models are also well-implemented. It would be great if brms could also make it easy to implement covariance regressions, such as in this paper: https://doi.org/10.1177/0049124119882449. Example Stan code (for two outcomes) is provided by the authors in the Supplemental Material section (https://journals.sagepub.com/doi/suppl/10.1177/0049124119882449).

**Comment by paul-buerkner** [comment] 2019-12-11 20:44
So this effectively means predicting (residual) correlations?

**Comment by shannonajw** [comment] 2019-12-11 20:51
Yes, that's right.

**Comment by shannonajw** [comment] 2019-12-18 01:26
Not sure how feasible this is (or if it is already implemented), but on top of modeling the residuals, it may also be worth considering extending this to mixed models - where the variance of the random effects (and possibly even the covariances) can be modeled as a function of covariates. See https://www.jstatsoft.org/article/view/v052i12 for an implementation in R.

Thanks again for considering these features!

**Comment by tfjaeger** [comment] 2019-12-18 15:09
I think this (predicting residual correlations) is already added as a milestone feature for brms 3.0, as of March. 

Paul, have you by chance started on this? I'm also working on a research project that would reduce dozens of analyses into one if that feature was added (assessing differences in talker-level statistics of phonetic categories, which draws brms's multivariate and distributional model abilities). I'm wondering whether I should look into the articles linked here or whether this will be a feature 'soon' to be released in brms. 

(How you manage to do all of these things is beyond me! The conceptual clarity of brms is truly amazing.)

**Comment by paul-buerkner** [comment] 2019-12-19 17:03
I have not and it will take a few months until I can start working on this unfortunately.

**Comment by tfjaeger** [comment] 2019-12-19 18:27
Thanks for the quick response!

**Comment by paul-buerkner** [comment] 2024-01-27 23:30
This seems to be effectively a duplicate of issue #254. Closing this issue here.

**Closed by paul-buerkner** 2024-01-27 23:30 UTC
Labels: feature, formula
