### ISSUE TITLE
An error in coding a categorical model

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#672] opened 2019-05-23 10:14 UTC
I want to assess the effect of a three-level factor on a 5-level response : 
```
> with(Data, table(TechMEF, Groupe, useNA="ifany"))
          Groupe
TechMEF     IC  PM   M
  Gates      8   0   0
  Manuel     1   1   0
  Mixte      2   4   6
  Protaper   8   7   1
  Wave_One 163 141 135
  <NA>       1   2   3
```
However, `brm` (from brms 2.9.0) seems to have problem with this model : 

```
> foo <- brm(TechMEF~Groupe, data=Data, family=categorical)
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

variable "muWave_One" does not exist.
  error in 'model18904d8b89b0_file18902f29e9a4' at line 68, column 66
  -------------------------------------------------
    66:   vector[ncat] mu[N];
    67:   for (n in 1:N) {
    68:     mu[n] = [0, muManuel[n], muMixte[n], muProtaper[n], muWave_One[n]]';
                                                                         ^
    69:   }
  -------------------------------------------------

Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file18902f29e9a4' due to the above error.
De plus : Warning message:
Rows containing NAs were excluded from the model. 
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

variable "muWave_One" does not exist.
  error in 'model18905019d93b_file18902f29e9a4' at line 68, column 66
  -------------------------------------------------
    66:   vector[ncat] mu[N];
    67:   for (n in 1:N) {
    68:     mu[n] = [0, muManuel[n], muMixte[n], muProtaper[n], muWave_One[n]]';
                                                                         ^
    69:   }
  -------------------------------------------------

Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file18902f29e9a4' due to the above error.
> 
```

I get the same error when explicitly using the complete cases...

**Comment by paul-buerkner** [comment] 2019-05-23 11:07
Could it be that the underscore in `Wave_One` causes the error? Can you try to remove it from the name?

**Comment by paul-buerkner** [comment] 2019-05-23 11:44
This problem should be fixed now. Thanks for reporting it!

**Closed by paul-buerkner** 2019-05-23 11:44 UTC
Labels: bug

**Comment by drewkog** [comment] 2019-05-26 23:53
Hey Paul,

I get the same issue and I have the updated version of BRMS. What I found to get my model to finally run was that a. whitespace needed to be removed and b. special characters (such as a period) in the outcome variable names also needed to be removed.

**Comment by paul-buerkner** [comment] 2019-05-27 06:37
In the github version of brms, the following works for me 

```
dat <- data.frame(y = rep(c("a bc", "a..bd", "ab", "a_bef"), 2))
make_stancode(y ~ 1, data = dat, family = categorical())
```

If there is still something that fails in the github version, I would be grateful for a minimal reproducible example.
