### ISSUE TITLE
Error: Unknown column 'trait'

### ISSUE THREAD

**Issue by Atan1988** [paul-buerkner/brms#105] opened 2016-08-10 03:04 UTC
Hi Paul,

     I am trying out a zero_inflated model, but I got the error message:
     Error: Unknown column 'trait'
     fit2 <- brm(IndemCt ~  0 + trait + trait:(EY + EFFYMonth) + offset(log(Termc)),
            family = zero_inflated_negbinomial(link = "log"),  
            data = aggclms %>% filter(Pd1 %in% c("EPIC")), chains = 4, iter = 2000)
     Is this a known issue?

Thanks!
Allen

**Comment by paul-buerkner** [comment] 2016-08-10 06:49
Hmm, I haven't seen this before. Can you try it with the latest dev version from github?

```R
devtools::install_github("paul-buerkner/brms")
```
(please install the latest CRAN version of mgcv before running the command). If this doesn't solve the problem, would you mind providing a reproducible example?

**Comment by Atan1988** [comment] 2016-08-10 14:43
Hi Paul,

    Thank you for the quick reply.
    I tried to reinstall mgcv as well as installing the latest dev version, but the error persists. 
    I wonder whether it's due to the issues within the dataset. (too many 0s?) 
    I tried to run a hurdle_gamma model on the attached dataset, and it also gives the same error message:
    Error: Unknown column 'trait'
    h2 <- brm(IncLR ~ 0 + trait + trait:((EQ|LocationState) + EFFQMonth),
              family = hurdle_gamma(link = "log"),
               data=dat, chains = 4, iter = 2000)
 
   Thanks.
   Allen

    [dat.xlsx](https://github.com/paul-buerkner/brms/files/411361/dat.xlsx)

**Comment by paul-buerkner** [comment] 2016-08-10 17:07
The syntax of your model is not entirely correct. It should rather be:

```R
h2 <- brm(IncLR ~ 0 + trait + trait:(EFFQMonth) + 
            (0 + trait + trait:EQ|LocationState),
          family = hurdle_gamma(link = "log"),
          data=dat, chains = 4, iter = 2000)
```

However, I do not get your error message with your model. Instead brms complains about random effects that are not correctly specified (which makes sense given the incorrect syntax). When using the correct syntax, the model works without complaints (after setting some slightly negative values to zero). Accordingly, I am a little be stuck here. Maybe you can try updating R and all dependencies of brms to the latest version.

**Comment by Atan1988** [comment] 2016-08-10 22:17
Hi Paul,

   Thank you for looking into this.  Would the session info help? I feel all the packages should be installed pretty recently. 
library(readxl)
library(brms)
library(dplyr)
dat <- read_excel("dat.xlsx") %>% mutate(IncLR = ifelse(IncLR < 0, 0, IncLR))

h2 <- brm(IncLR ~ 0 + trait + trait:(EFFQMonth) + 
            (0 + trait + trait:EQ|LocationState),
          family = hurdle_gamma(link = "log"),
          data=dat, chains = 4, iter = 2000)

sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0        brms_0.10.0.9000   rstan_2.11.1       StanHeaders_2.11.0 ggplot2_2.1.0     
[6] readxl_0.1.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      magrittr_1.5     splines_3.3.1    MASS_7.3-45      munsell_0.4.3    statmod_1.4.25  
 [7] colorspace_1.2-6 lattice_0.20-33  R6_2.1.2         minqa_1.2.4      plyr_1.8.4       tools_3.3.1     
[13] parallel_3.3.1   grid_3.3.1       gtable_0.2.0     nlme_3.1-124     DBI_0.4-1        coda_0.18-1     
[19] lazyeval_0.2.0   assertthat_0.1   abind_1.4-5      lme4_1.1-12      tibble_1.0       Matrix_1.2-3    
[25] gridExtra_2.2.1  nloptr_1.0.4     rsconnect_0.4.3  inline_0.3.14    scales_0.4.0     stats4_3.3.1

**Comment by Atan1988** [comment] 2016-08-10 22:38
Paul,

     I think it might be actually caused by a conflict with dplyr. I was able to make it work without loading dplyr. 

Thanks,
Allen

**Comment by paul-buerkner** [comment] 2016-08-11 09:33
Thanks for investigating this further. How did you change your model call to make it work?

**Comment by Atan1988** [comment] 2016-08-11 11:16
I used the model call you recommended, but I didn't load the "dplyr" package.  Would you be able to reproduce the error if loading both dplyr and brms during the same session?  I only get this error if I have loaded the dplyr package.

**Comment by paul-buerkner** [comment] 2016-08-11 11:27
Ok, I get the error now. The problem is that `dat` is not solely of class `data.frame` when changed by dplyr but of class `tbl_df`,  `tbl`, and `data.frame`. I will try getting brm working with dplyr datasets in the next couple of hours.

**Comment by Atan1988** [comment] 2016-08-11 11:46
Great! Thanks, Paul!

**Comment by paul-buerkner** [comment] 2016-08-11 11:48
It should be fixed now. The problem was that dplyr doesn't return NULL when trying to extract a non-existent variable via `[[` out of a data.frame of class `tbl`, but instead returns an error.

**Closed by paul-buerkner** 2016-08-11 11:48 UTC
Labels: bug
