### ISSUE TITLE
error-adding-loo-criterion-to-brms-ordinal-model-with-link-cloglog

### ISSUE THREAD

**Issue by groceryheist** [paul-buerkner/brms#1192] opened 2021-06-24 03:24 UTC
https://discourse.mc-stan.org/t/error-adding-loo-criterion-to-brms-ordinal-model-with-link-cloglog/22600

The model looks fine but when I try to add loo or waic criterion I get the error 
 `validate_ll(x) : All input values must be finite` 

I'm not convinced that the `cloglog` link is appropriate. I get fairly good results using the 'logit' link. The data are very skewed so I was hoping to check.   I'm fairly confident that the `sratio` model is a good model of the data generating process.

```
df <- read.csv("test_error_validate_ll_ordinal.csv")
df[,'wp10'] <- factor(df[,'wp10'],levels=c("stub",'start','c','b','ga','fa'),ordered=T)
fam.cloglog <- sratio(link='cloglog', threshold='flexible')
formula <- brmsformula(wp10 | weights(weight) ~  Stub + Start + B + FA + GA, decomp='QR',center=TRUE)
mod <- brm(formula=formula.main.noC, data=df, family=fam.cloglog)
mod <- add_criterion(model.main.noC.cloglog,'loo')
```
I have uploaded my dataset (n=2000, 258kb) here: https://teblunthuis.cc/outgoing/test_error_validate_ll_ordinal.csv

* Operating System: centos 7.6.1810
* brms Version: 2.15.0

Thank you so much for the help!

**Comment by paul-buerkner** [comment] 2021-06-24 08:54
I think we need to compute things on the log-scale in the post-processing as is done already on the Stan side of brms.

**Comment by fweber144** [comment] 2022-03-02 20:15
Paul asked me to take a look at this, but it seems the link for the data is dead. Could you provide a new one?

**Comment by groceryheist** [comment] 2022-03-03 06:25
I restored the original link. Thank you for looking into this!

**Comment by fweber144** [comment] 2022-03-10 10:28
I took a look at this, but it seems like the issue is not caused by code introduced by my PRs. Nevertheless, I have discussed possible solutions with Paul. Perhaps one of them works.

**Comment by paul-buerkner** [comment] 2022-04-08 11:02
This should now be fixed on github :-)

**Closed by paul-buerkner** 2022-04-08 11:02 UTC
Labels: bug, post-processing
