### ISSUE TITLE
unused argument (opencl_ids = .x4)

### ISSUE THREAD

**Issue by JCruk** [paul-buerkner/brms#1179] opened 2021-06-09 13:36 UTC
I am trying to test the new OpenCL option with the cmdstan backend, but get an error:
`unused argument (opencl_ids = .x4)`

Platform and device ID's
````
Platform #0: NVIDIA CUDA
 `-- Device #0: GeForce RTX 2060
````

My brm call:
````
Mod <- brm(
  fmla,
  data,
  family = student(link_nu = "logm1"),  
  prior = priors,
  inits = 0,
  iter = 2000,
  warmup = 1000,
  chains = 4,
  cores = ncores,
  sample_prior = TRUE,
  opencl = opencl(ids = c(0, 0)),
  save_pars = save_pars(all = TRUE),
  normalize = FALSE,
  backend = "cmdstan",
  control = list(max_treedepth = 12,
                 adapt_delta = 0.9)
)
````

Am I passing the argument incorrectly?

**Comment by paul-buerkner** [comment] 2021-06-09 14:21
Do you use the latest github version of brms? If I am using some minimal information to fill your code above, I works for me. If it continues to not work, please provide a minimal reproducible example.

**Comment by paul-buerkner** [comment] 2021-06-09 14:26
Oh and which version of cmdstanr and cmdstan you are using? Perhaps you need to update those?

**Comment by JCruk** [comment] 2021-06-09 14:51
Thanks, Paul. My apologies for not providing enough information!

I'm using the latest github brms (2.15.9), which I installed this morning. Cmdstanr v0.3.0.9000, and the latest cmdstan dev build (2.27) 

A minimal reprex:

```
# List of needed packages
Pkgs <- c("tidyverse", "parallel","brms", "cmdstanr", "mvtnorm")

# Load packages
lapply(Pkgs, require, c = T)

setwd(here())

## Set computing options
ncores = detectCores()
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

## Make some fake data
sigma = c(10, 15, 10, 20)
rho = c(-0.6, 0.3, 0.6, -0.3, 0.6, -0.3)
cov.mat = matrix(c(sigma[1] ^ 2,
                   sigma[1] * sigma[2] * rho[1],
                   sigma[1] * sigma[3] * rho[2],
                   sigma[1] * sigma[4] * rho[3],
                   sigma[1] * sigma[2] * rho[1], 
                   sigma[2] ^ 2, 
                   sigma[2] * sigma[3] * rho[4],  
                   sigma[2] * sigma[4] * rho[5],
                   sigma[1] * sigma[3] * rho[2], 
                   sigma[2] * sigma[3] * rho[4], 
                   sigma[3] ^ 2, 
                   sigma[3] * sigma[4] * rho[6],
                   sigma[1] * sigma[4] * rho[3], 
                   sigma[2] * sigma[4] * rho[5],
                   sigma[3] * sigma[4] * rho[6],
                   sigma[3] ^ 2),
                 nrow=4, byrow=T)

# Data matrix
data.mat = rmvnorm(n=40, sigma=cov.mat)

# To long data frame
df <- data.frame(data.mat) %>%
  pivot_longer(everything())

# Compile and sample
fit <- brm(value ~ name,
           df,
           family = student(link_nu = "logm1"),
           inits = 0,
           iter = 2000,
           warmup = 1000,
           chains = 4,
           cores = ncores,
           threads = threading(1),
           opencl = opencl(c(0, 0)),
           save_pars = save_pars(all = TRUE),
           normalize = FALSE,
           backend = "cmdstan",
           control = list(max_treedepth = 12,
                          adapt_delta = 0.9))
```

Session info
```
sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8       
 [4] LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mvtnorm_1.1-2        cmdstanr_0.3.0.9000  brms_2.15.9          Rcpp_1.0.6          
 [5] forcats_0.5.1        stringr_1.4.0        dplyr_1.0.6          purrr_0.3.4         
 [9] readr_1.4.0          tidyr_1.1.3          tibble_3.1.2         ggplot2_3.3.3       
[13] tidyverse_1.3.1.9000
```

**Comment by paul-buerkner** [comment] 2021-06-09 15:04
@rok-cesnovar can you reproduce the above problem?

**Comment by rok-cesnovar** [comment] 2021-06-09 16:19
Also cant replicate. The issue you are experiencing is because you need cmdstanr 0.4.0 (last release) or the Github development version. The opencl_ids argument was introduced in 0.4.0.

I would also suggest not specifying `threads = threading(1)` together with OpenCL as its unlikely GPU will be used in this case . In short the Stan-to-C++ compiler has its own set of rules of when to use the GPU and when not and the Stan model with threading is less likely to conform with those rules.

**Comment by paul-buerkner** [comment] 2021-06-09 16:21
Thank you! Closing this issue then.

**Closed by paul-buerkner** 2021-06-09 16:21 UTC

**Comment by JCruk** [comment] 2021-06-09 16:25
Updating cmdstanr from github solved the issue. Thank you, both!
