### ISSUE TITLE
Semantic Error when using decomp = "QR" and threading

### ISSUE THREAD

**Issue by SteveBronder** [paul-buerkner/brms#1086] opened 2021-02-05 07:36 UTC
## Example
```R
# 7aca22a
library(brm)
# 21e2be1
cmdstanr::set_cmdstan_path("~/stan/origin/cmdstan/")
blah = data.frame(foo = runif(1000), goo = runif(1000), whew = runif(1000))
mod = bf(foo ~ goo + whew, decomp = "QR")
fitter = brm(mod, data = blah, threads = 12)
```

Returns

```
Compiling Stan program...
0

Semantic error in 'string', line 21, column 49 to column 51:

Identifier 'XQ' not in scope.


Error in .fun(model_code = .x1) : 
  stanc_ret is not a successfully returned list from stanc
In addition: Warning message:
In (function (x)  : rstan option 'threads_per_chain' not found
```
And with cmdstan

```R
fitter = brm(mod, data = blah, threads = 12, backend = "cmdstanr")
```

```
Compiling Stan program...
Semantic error in '/tmp/RtmpkiQTev/model-44b54259b3204.stan', line 21, column 49 to column 51:
   -------------------------------------------------
    19:      real ptarget = 0;
    20:      int N = end - start + 1;
    21:      ptarget += normal_id_glm_lpdf(Y[start:end] | XQ[start:end], Intercept, bQ, sigma);
                                                          ^
    22:      return ptarget;
    23:    }
   -------------------------------------------------
Identifier 'XQ' not in scope.make: *** [make/program:47: /tmp/RtmpkiQTev/model-44b54259b3204.hpp] Error 1
Error: An error occured during compilation! See the message above for more information.
````

It looks like it's just a typo in `partial_log_lik_lpmf` for `XQ and `BQ`

```stan
// generated with brms 2.14.10
functions {
  /* integer sequence of values
   * Args: 
   *   start: starting integer
   *   end: ending integer
   * Returns: 
   *   an integer sequence from start to end
   */ 
  int[] sequence(int start, int end) { 
    int seq[end - start + 1];
    for (n in 1:num_elements(seq)) {
      seq[n] = n + start - 1;
    }
    return seq; 
  } 
  // compute partial sums of the log-likelihood
  real partial_log_lik_lpmf(int[] seq, int start, int end, vector Y, matrix Xc, real Intercept, real sigma) {
    real ptarget = 0;
    int N = end - start + 1;
    ptarget += normal_id_glm_lpdf(Y[start:end] | XQ[start:end], Intercept, bQ, sigma);
    return ptarget;
  }
}
data {
  int<lower=1> N;  // total number of observations
  vector[N] Y;  // response variable
  int<lower=1> K;  // number of population-level effects
  matrix[N, K] X;  // population-level design matrix
  int grainsize;  // grainsize for threading
  int prior_only;  // should the likelihood be ignored?
}
transformed data {
  int Kc = K - 1;
  matrix[N, Kc] Xc;  // centered version of X without an intercept
  vector[Kc] means_X;  // column means of X before centering
  // matrices for QR decomposition
  matrix[N, Kc] XQ;
  matrix[Kc, Kc] XR;
  matrix[Kc, Kc] XR_inv;
  int seq[N] = sequence(1, N);
  for (i in 2:K) {
    means_X[i - 1] = mean(X[, i]);
    Xc[, i - 1] = X[, i] - means_X[i - 1];
  }
  // compute and scale QR decomposition
  XQ = qr_thin_Q(Xc) * sqrt(N - 1);
  XR = qr_thin_R(Xc) / sqrt(N - 1);
  XR_inv = inverse(XR);
}
parameters {
  vector[Kc] bQ;  // regression coefficients at QR scale
  real Intercept;  // temporary intercept for centered predictors
  real<lower=0> sigma;  // residual SD
}
transformed parameters {
}
model {
  // likelihood including constants
  if (!prior_only) {
    target += reduce_sum(partial_log_lik_lpmf, seq, grainsize, Y, Xc, Intercept, sigma);
  }
  // priors including constants
  target += student_t_lpdf(Intercept | 3, 0.5, 2.5);
  target += student_t_lpdf(sigma | 3, 0, 2.5)
    - 1 * student_t_lccdf(0 | 3, 0, 2.5);
}
generated quantities {
  // obtain the actual coefficients
  vector[Kc] b = XR_inv * bQ;
  // actual population-level intercept
  real b_Intercept = Intercept - dot_product(means_X, b);
}
```

**Comment by paul-buerkner** [comment] 2021-02-05 07:57
Thanks! Should now be fixed on github.

**Closed by paul-buerkner** 2021-02-05 07:57 UTC

**Comment by hsbadr** [comment] 2021-02-06 00:46
Thanks @SteveBronder for reporting this and thanks @paul-buerkner for fixing it. It affects me too!

I've also noticed the following warning in your example:
> ```
> In addition: Warning message:
> In (function (x)  : rstan option 'threads_per_chain' not found
> ```

It's most likely because you use an earlier revision of #887. You may want to checkout the latest revision that supports `threads_per_chain` or use the packages from [the latest artifacts](https://github.com/stan-dev/rstan/actions/runs/541905255).

**Comment by hsbadr** [comment] 2021-02-06 00:48
Thanks @SteveBronder for reporting this and thanks @paul-buerkner for fixing it. It affects me too!

I've also noticed the following warning in your example:
> ```
> In addition: Warning message:
> In (function (x)  : rstan option 'threads_per_chain' not found
> ```

It's most likely because you use an earlier revision of https://github.com/stan-dev/rstan/pull/887. You may want to checkout the latest revision that supports `threads_per_chain` or use the packages from [the latest artifacts](https://github.com/stan-dev/rstan/actions/runs/541905255).

**Comment by SteveBronder** [comment] 2021-02-06 02:44
good catch thanks!

**Comment by carloscells** [comment] 2021-10-02 20:40
I'm getting the same error when using QR decomposition:

> Compiling Stan program...
> Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
>   0
> Semantic error in 'string', line 105, column 2 to column 7: 
> Identifier 'b_y1Q' not in scope.

Here'e a reproducible example nabbed from another post:
library("rstan") 
library("rstantools")
library("brms")
#################
n <- 18
set.seed(21)
#################
dat <- tibble( Group = rep(rep(0:1,each=n/2),2),
               res1 = rnorm( 2*n, 0, 1 ),
               res2 = rnorm( 2*n, 0, 1 )) %>%
    mutate( y1 = Group + res1,
                  y2 = Group + y1 + res2,
                  y3 = y2 + res3,
                  y1 = (y1 - mean(y1))/sd(y1),
                  y2 = (y2 - mean(y2))/sd(y2),
                  Group = factor(Group) ) %>% as.data.frame
###################################
bf1 <- bf( mvbind(y1,y2) ~ Group, decomp="QR") + set_rescor(TRUE)

b_priors <- c( set_prior('horseshoe(1)', class='b', resp='y1'),
                         set_prior('horseshoe(1)', class='b', resp='y2'))

brms_fit <- brm( bf1,
                              prior = b_priors,
                              control = list(adapt_delta=0.999),
                              cores = 4, seed = 1,
                              data = dat, backend="rstan")

─ Session info ──────────────────────────────

 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       macOS Big Sur 11.5.2        
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2021-10-02                  

─ Packages ───────────────────────────────
 rstan          * 2.27.0.9000 2021-09-21 [1] git2r (@69f02d8)                     
 rstantools     * 2.1.1.9000  2021-09-02 [1] Github (stan-dev/rstantools@6fe0dc5) 
 brms           * 2.16.2      2021-09-21 [1] Github (paul-buerkner/brms@de7817c)  
 ... ... ...

**Comment by paul-buerkner** [comment] 2021-10-04 06:01
Thanks. Should now be fixed.
